### ISSUE TITLE
Settings Page Overhaul

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#102]
too many text.
will move descriptions to FAQ.
only checkboxes, and input forms will remain.

**Comment by ReiFan49** [comment]
what about using tooltips, is it still annoys out the user there?

**Comment by dragonjet** [comment]
that works too, though im originally planning to move all texts [to the dedicated wiki](https://github.com/dragonjet/KC3Kai/wiki). No user complains about this though, just my preference coz the page is getting too long xD

**Comment by bamboo3250** [comment]
Wow, the new Settings page is so cool :+1: :open_mouth:

**Comment by dragonjet** [comment]
thanks, though i haven't tested it much xD gonna rest for now

**Comment by Crazyteitoku** [comment]
Very nice @dragonjet :+1: I see myself fitting amongst a whole bunch of developers :stuck_out_tongue_closed_eyes: Still (and you are probably aware of this):
* Quest translations aren't available.
* HP prediction seems to be a null setting.
* (Other issues that I can't remember off the top of my head right now) :smile:

**Comment by bamboo3250** [comment]
@Crazyteitoku I think the quest translation have already been done (but still have some issue related to it), haven't it?

**Comment by Crazyteitoku** [comment]
@bamboo3250 yeah, especially with new quests that were flowing in, tracking issues and what not are somewhat prevalent. However, regardless of how it is the quests translations are a definitive bonus to those who are unable to read Japanese even if it is missing features here or there.
