### ISSUE TITLE
[Bug report] Compass Result: Showing previous result if the next node is a malstrom

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#105]
I found this bug when bringing 2+ DDs into 4-3. The way is A->B->C.

http://kancolle.wikia.com/wiki/World_4:_%E8%A5%BF%E6%96%B9%E6%B5%B7%E5%9F%9F#4-3

Not sure if this bug is reported or not.

**Comment by dragonjet** [comment]
there are related bugs reported but this one is new in its own right, thanks for the report~
