### ISSUE TITLE
[Bug report and feature request] Flame thrower icon missing. Ships that has been sent to the bath and after completion of the repairs the HP gauge should reset without user intervention.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#106]
**Date Seen**:
24-05-2015

**Version**:
- **KC3 Kai v009 (git build) ID**: jljpednjlkddlmahfoljfjlnbollampe 
- **KC3 Kai v009 git revision**: 9758ab2ecdc54eafcae4844280a3490993d97089
-  **Browser**: Chromium 64bit (currently on: 43.0.2357.65 (Developer Build bbd9270c4234d436bb05bd4502b230fc17887d08 Linux)))
- **OS**: Archlinux 64bit (currently on: Linux: 4.0.4-2-ARCH)

**Bug Description**:
Minor issue found during sortie.

Screenshots will be provided.

**Severity**:
Minor.

**Steps to Reproduce**:
1. Sortie your fleet to maps that drops things like flame throwers. I sortied mine to 2-2.

**Actual Behavior**:
A circle is being indicated in place of where a flame thrower icon is meant to be.

**Expected Behavior**:
A flame thrower icon to appear.

**Troubleshooting/Testing Steps Attempted**:
None.

**Workaround**:
None.

**Attachments**:

**Feature request**:
- When ships are sent to bath their HP gauge does not reset back to full after repairs has been completed. Ideally, upon ships that has been flagged for baths and once the timer is up the HP gauge of the ship should be reset back to full automatically.

**Comment by nevrending** [comment]
@Crazyteitoku Perhaps you should move your feature request to a separate issue
