### ISSUE TITLE
Current sortie log

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#108]
I know the current sortie node names are not very useful as has been stated in other issues, but I still would like to have a little list to show what nodes I've been through already. Example: A -> C -> F or something like that.
Here's an example of use. It could be useful if I'm doing some mindless task but need to know where I currently am before continuing. Right now I'm farming for subs while grinding my little ones in 1-5, and I want to stop before I get to the boss node. As boring as that is, I just go do something else, and only get back in between battles to advance to the next one. Most likely I'll have fogotten which node I was at, and since there's little indication about which node I was at on the results screen, I currently need to count on my fingers what was the last node I visited so I know when to turn back.

**Comment by dragonjet** [comment]
You can visit the strategy room in those cases that you forgot where you are and see how many nodes are there in the latest sortie?

**Comment by AlanSchaeffer** [comment]
I did not know you could do this, I just assumed that the strategy room sorties would only update after I was done with it

**Comment by AlanSchaeffer** [comment]
Here's some update I have on this, based on how I feel about it:
- Accessing the strategy room to check this info is just not practical enough, and I ended up never using it.
- The way I've been keeping track of where I am is by leaving the node prediction pop-up open for the whole duration of the sortie

So I still think this kind of info would be useful, but there are other solutions that could be used in place of it that might be more interesting. Maybe a button to re-open the last pop-up? Or a list to view the last handful of events (such as node predictions).

**Comment by bamboo3250** [comment]
@dragonjet I think this issue has been resolved?

**Comment by dragonjet** [comment]
ah yes since we already have nodes on panel, and supply gauges too
