### ISSUE TITLE
Update panel status for repaired ships

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#109]
When ships are sent to bath their HP gauge does not reset back to full after repairs has been completed. Ideally, upon ships that has been flagged for baths and once the timer is up the HP gauge of the ship should be reset back to full automatically. - @Crazyteitoku

**Comment by dragonjet** [comment]
@Crazyteitoku is this the same as the recent feature request that can be closed? xD

**Comment by Crazyteitoku** [comment]
Wait what? oh yeah, yes. :laughing:
