### ISSUE TITLE
[Strategy Room] LSC list is empty, but pagination is working

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#11]
*Oh yeah btw Jet I remember you said you needed some tests on the LSC, when you released the other day in AKCG. Did my post event LSC (booo Hyuuga) and well, the tab is trying to record as a page button appeared but not the construction itself* - [Alexavis](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Alexavis-20150503025433?permalink=243408#comm-243408)

**Comment by nevrending** [comment]
I think this issue has been resolved / is already safe to close

![screen shot 2015-05-19 at 01 45 39](https://cloud.githubusercontent.com/assets/4745298/7687640/d70300b4-fdc8-11e4-8b66-3fc08f5e0350.png)


And here are pics taken from various groups

![ss1]
(https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-xat1/v/t1.0-9/11143577_599238320217930_6497565024852271159_n.jpg?oh=f85356a89cb9b00dd9a8ad9655ee7d71&oe=55C5F0CC&__gda__=1443247379_c6236e473a7bfe7c90aef85167172c58)

![ss2]
(https://scontent-hkg3-1.xx.fbcdn.net/hphotos-xpt1/v/t1.0-9/11150554_994227893922539_8134574286269168458_n.jpg?oh=fa11951f373e01de3698f638f7fc5a40&oe=55D10AC4)

![ss3]
(https://scontent-hkg3-1.xx.fbcdn.net/hphotos-xft1/v/l/t1.0-9/11014653_10200440289445375_8065291990653102195_n.jpg?oh=f7b939780203005ce64664c580c5b550&oe=55C35F67)

**Comment by dragonjet** [comment]
ah thanks for reminding, i forgot this issue existed and did not mention on the commit
