### ISSUE TITLE
Switching ships in the same fleet won't update ship portrait

### ISSUE THREAD

**Issue by bernardocaporto** [dragonjet/KC3Kai#114]
When switching the positions of two ships in the same fleet, only the original position's portrait will be refreshed

Steps to recreate the bug, assuming you have Yamato as your Flagship and Musashi in the second position:

1- Enter the fleet management screen
2- Click on Yamato, in order to replace her with another kanmusu
3- Select Musashi from the ship list
4- Yamato will switch positions with Musashi. The Flagship's portrait will change to Musashi, but the 2nd position's portrait won't refresh, remaining as Musashi as well

**Comment by dragonjet** [comment]
Similar: Issue #3

**Comment by bernardocaporto** [comment]
ah, sorry for the duplicate. I tried to search for "portrait" before I posted but nothing came up

**Comment by dragonjet** [comment]
np~
