### ISSUE TITLE
Morale/Fatigue bug

### ISSUE THREAD

**Issue by rape112** [dragonjet/KC3Kai#119]
sometimes morale counter shows incorect values after nod or sortie
example: before sortie to 1-1 flagship morale was 85 ,  after 1st node it was 93 , after last node it was 85 all nods flagship get mvp

**Comment by dragonjet** [comment]
after every sortie, all ships are deducted 15 morale, which means 85 is the maximum on non-pvp sparkling. If you want to reach 100 morale, do PvP after 85.

See [wikia article on Morale/Fatigue](http://kancolle.wikia.com/wiki/Morale/Fatigue)

**Comment by dragonjet** [comment]
closing issue, but you may still reply here if there are any questions. otherwise you may ask around the wikia, especially the chat box, people around the globe willing to help from there almost 24/7/
