### ISSUE TITLE
[Bug report] "Uncaught TypeError: Cannot read property '3' of undefined." when crafting equipments.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#127]
**Date Seen**:
10-06-2015

**Version**:

**KC3 Kai v009 (git build) ID**: jljpednjlkddlmahfoljfjlnbollampe
**KC3 Kai v009 git revision**: ab7443252e40c61cef5b2f6e95b380c9525a49b9
**Browser**: Chromium 64bit (currently on: 43.0.2357.81 (Developer Build 4d096306deb9e86953c81f08454dd6db07b406b5 Linux))
**OS**: Archlinux 64bit (currently on: Linux: 4.0.5-1-ARCH)

**Bug Description**:
Results from crafting equipment(s) shows "asdasd" regardless of actual equipment being crafted. This only occurs with successful craft(s) - i.e. if the result(s) are penguin and miss cloud this error would not be revealed.

Furthermore an error is shown in both the developer console as well as under the extensions of user's chrome/chromium build.

Please refer to the screenshots provided below.

**Severity**:
Moderate - Major

**Steps to Reproduce**:
1. Go into construction area.
2. Craft any equipment that yields successful equipment result (regardless if that is the desired equipment or not).
3. Equipment shown inside KC3 Kai is shown as "asdasd".

**Actual Behavior**:
Equipment is shown as "asdasd".

**Expected Behavior**:
The actual result of the equipment that came out of crafting. i.e. if the result is going to be 12cm naval gun then it should show as such and not "asdasd".

**Troubleshooting/Testing Steps Attempted**:
None.

**Workaround**:
None.

**Attachments**:
![kc3kai-009-bug0](https://cloud.githubusercontent.com/assets/12234182/8073211/fcd39506-0f5c-11e5-979f-33c69f6a87ea.png)
![kc3kai-009-bug1](https://cloud.githubusercontent.com/assets/12234182/8073212/fcfe77f8-0f5c-11e5-9ce5-462ee9f2f974.png)
![kc3kai-009-bug2](https://cloud.githubusercontent.com/assets/12234182/8073213/fd038784-0f5c-11e5-886e-025524b45c41.png)
![kc3kai-009-bug3](https://cloud.githubusercontent.com/assets/12234182/8073214/fd061468-0f5c-11e5-8890-d4d449a88f8c.png)

**Comment by ReiFan49** [comment]
MasterItem value is false... lol, gonna check reactor
