### ISSUE TITLE
Ship Drop Popup

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#135]
hi again, Dragonjet.

I've taken a look at the compass and equipment craft result notification, and they're pretty good.

Is it possible to make notification message to appear whenever the user gets a new ship he didn't have before from sortie drops? (like, say, the player is notified when he got Akashi for the first time but is not notified when he already Akashi)

--- [Ar-cen-ciel ](http://kancolle.wikia.com/wiki/Thread:254745)

**Comment by LostLogia4** [comment]
Just an afterthought, but I would personally like to get options for notifications for already existing ships of player's choosing if possible (example: Maruyu)
Thanks again for taking this feature in consideration.

**Comment by dragonjet** [comment]
oh, I was thinking of adding notification for all drops. looking at KCV, it always shows ship name regardless if it's new on fleet or not.

but isolating notifications for player-specified ships would be difficult. we'd have to come up with another interface where they can specify who's who,, worst if we'll need a new tab on strategy room. though this is technically possible, it won't be on the priority list.

**Comment by LostLogia4** [comment]
Well, I suppose notification for all drops works just fine except for World 1-1, where it's gonna get really annoying since that's the sparkle map.
Also, most players apart from new players only desires ships (including duplicates) that has the gold rarity or higher, so you can narrow down the list to those, so you can offer the option of:
- Ships with golden/holo rarity, regardless whether it's new or not.
- Ships required for unlocking additional fleets, preferably automatically.
- New ships only.

**Comment by bamboo3250** [comment]
Please let me add one more option.
* Ships that we don't have in the current list (not necessarily new or old, we might get her before but scrapped subsequently).
This option is the most feasible and can be done quickly but not really good for free-to-play players who don't have enough space for all common ships.

The above options are good for anyone (and feasible as well) but it may take a while to build the database for them.

**Comment by dragonjet** [comment]
true what @bamboo3250 said. I forgot that f2p will have this problem.

In concept of auto-detect in list, first obstacles would be determining if that is really not yet in the list or not. IDs change when you remodel it. So Taigei should not be recognized new if you already have Ryuuhou.

Another option is to have an "exception" list. The popup box will contain a button that says "Don't show her drop to me again". With that, we don't need a new interface, and player just keeps on adding common drops to the list everytime he gets it.

**Comment by LostLogia4** [comment]
@bamboo3250 Uh, okay, but what do you mean by the "current list"?
I would've been glad to build the database... except that I'm not good enough at Javascript to code an extension yet... I can only edit it at best.

**Comment by bamboo3250** [comment]
@LostLogia4 I mean the list of ships we have in the base.

Regarding the rare ship notification, I think I can help you build that as long as we have a pre-defined of rare ships. This option doesn't need much code and doesn't affect the database, just an .json file to store the pre-defined list although that means users cannot change it.

@dragonjet what do u think about that? May we give it a try?

**Comment by dragonjet** [comment]
oh about rarity, game code already has it, `api_backs` in raw json. Ranges from 1 to 8 pf its rarity starting from blue to sakura-holo. If we're basing it on rarity, we can set our minimum value to notify.

Although I'm not confident with using rarity since some silvers are actually rarer than golds, etc. For me I don't have silver Hayashimo and Kiyoshimo and I wanna see them notified, but not for golds such as kongou-class.

I guess the best way to move forward in step by step is first implement a "notify-all" drop. Then add a settings item for it. Next time we implement a condition, player will be able to choose it and we just add another code condition to the popup.

**Comment by LostLogia4** [comment]
@bamboo3250 Well, you're rewording my new ships into "ships not in current list".

Then I guess we have the draft for the feature then:
Tier 1 : Notify all unless exempted. You can add the exception list bailout options later.
Tier 2 : Ship class + Rarity base filter (starting from silver)
Tier 3 : Automatic detection of new ships. (hardest to implement)

**Comment by dragonjet** [comment]
:thumbsup:

**Comment by LostLogia4** [comment]
Ready by around v12 I guess?

**Comment by Crazyteitoku** [comment]
An extension to the idea with new ships is to probably run it against the ships that the user already has in their profile. This would notably be very handy for newcomers as they may not know what the names of the ships are and that in most cases they would not have it in their collection. So once that new drop has been added to their collection the notification would no longer reappear again for any subsequent thus duplicate drops.

The only possible drawback to this idea is really for those who are farming specifically for duplicates and does not know exactly know all the names of the ships. Though theoretically by then they wouldn't be a newcomer would they? :stuck_out_tongue:

**Comment by dragonjet** [comment]
:open_mouth:

lel CT, there's on thing I said earlier about auto-detection if its new on your fleet or not

*first obstacles would be determining if that is really not yet in the list or not. IDs change when you remodel it. So Taigei should not be recognized new if you already have Ryuuhou.*

**Comment by Crazyteitoku** [comment]
:hushed: sorry. I thought that point wasn't covered.

**Comment by LostLogia4** [comment]
@Crazyteitoku
We have already covered about this one actually. Same suggestion as me and bamboo3250 for Tier 3 really. Doesn't look like that one would be implemented soon enough, as much I would like that one.

**Comment by dragonjet** [comment]
Since this issue is already addressed in the latest build, where all drops are shown in the battle boxes, we can close this

![ss 2015-07-06 at 02 10 54](https://cloud.githubusercontent.com/assets/557312/8516614/f1d92774-23e8-11e5-9ddc-7307e76a91e6.png)
