### ISSUE TITLE
Fleet composition not updated

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#138]
Pardon me if this is already fixed in the next version, but I thought I would report this bug:
When the fleet member is changed with another in the same fleet, the old slot is not updated, resulting in something like this:
![formationbug](https://cloud.githubusercontent.com/assets/12930396/8200013/1e0b8730-14f1-11e5-820f-6c81d9d23299.jpg)

**Comment by Crazyteitoku** [comment]
I believe this issue is fixed in the github build of KC3 Kai. 

If you can afford to, please try out the [github build of KC3 Kai](https://github.com/dragonjet/KC3Kai/wiki/Setup-development-build) whilst noting some issues as noted in the same link.

**Comment by dragonjet** [comment]
Ah @Crazyteitoku is right, this has been fixed for some time now in b8800b63c0b6071fa0a68fdeb2dfe87355f643b0 for issue #3.

Though I apologize that these fixes are piling up on the unpublished v010. I need to finish the quest module first before all these are released.
