### ISSUE TITLE
Problem with Quest Tracking

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#139]
@dragonjet I know the Quest Tracking is still being developed. I just want to see whether you get the same error message like this or not. And the translation is not displayed properly as well.

![untitled](https://cloud.githubusercontent.com/assets/8078323/8206662/8bffb05a-1536-11e5-8746-ba483d88216f.png)

**Comment by dragonjet** [comment]
ah did you just click on "Delete Everything" button on the Strategy room?

**Comment by bamboo3250** [comment]
I didn't. This has happened since I pulled the code from master. Should I click on it and try again?

**Comment by dragonjet** [comment]
whoops, for a moment there I thought you were @Crazyteitoku coz of the pic XD

for now you can try going to all pages of the quests to fill all data. re-visiting the quest page will avoid these errors. I'll push a fix in a few mins.

**Comment by bamboo3250** [comment]
I clicked on "Everything" button and the translation now is correct but the error message still appears the same.

**Comment by bamboo3250** [comment]
oh yeah you are right. After doing that, it's not happen anymore xD
