### ISSUE TITLE
Quest translation popups not adequately covering the texts

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#140]
Seems like the untranslated texts spilled over over the translation popups.
![questbug](https://cloud.githubusercontent.com/assets/12930396/8213423/5072d1fc-1554-11e5-9dc5-0e7a3821d7f1.jpg)

I would suggest changing the popup's horizontal width from 400px to ~438-440px.

**Comment by dragonjet** [comment]
ah yes, on the latest upcoming version with Quest Translations, that area will be covered by your progress e.g. (4 / 15). thanks for noticing this~
