### ISSUE TITLE
Kc3 Kai not loading

### ISSUE THREAD

**Issue by TheRedCrayon** [dragonjet/KC3Kai#144]
i started Kancolle a few weeks ago and it was suggested too me i use Kc3 kai now as it was it looked awsom downloaded it and got it set up and went too use it i hit F12 clicked the Kc3 kai tab and nuthing....it wont load the only way i can play is by clicking the "play the game anyway" button

**Comment by bamboo3250** [comment]
Can you access to the game after clicking on "Start the game anyway" button?

**Comment by TheRedCrayon** [comment]
yes i can but when i do it that way i get no use out of any other fetures of the kc3 kai

**Comment by bamboo3250** [comment]
Hmm I see... Is there any error shown in the Console?

**Comment by TheRedCrayon** [comment]
not that i can see it just does nuthing at all

**Comment by TheRedCrayon** [comment]
ive re downloaded kc3 kai 2 times to see if that would help but its doing the same thing every time im thinking that something is either keeping it from running or its just not working for me and id like to get it fixxed cus i wanted to use the other things that made Kc3 kai look so apealing

**Comment by bamboo3250** [comment]
Could you try uninstalling KC3Kai and following this instruction while we are trying to investigate this issue?
https://github.com/dragonjet/KC3Kai/wiki/Installation

**Comment by TheRedCrayon** [comment]
ill give it a shot but i installed it that way from the get go well another time wont hurt

**Comment by TheRedCrayon** [comment]
i uninstalled and did what the link suggested and i still have the same outcome

**Comment by dragonjet** [comment]
this is most probably  from your Chrome settings not allowing localStorage

[check the answer on this article for the fix](http://stackoverflow.com/questions/24456891/iframe-in-chrome-error-uncaught-securityerror-failed-to-read-the-sessionstora)

**Comment by TheRedCrayon** [comment]
my god dragon u fixxed it id give u a hug buuut that would be unproffesional

**Comment by Crazyteitoku** [comment]
@TheRedCrayon not that I want to scare you or am assisting you with your issue. However you might want to blur out your API token. Your API token is what allows users such as yourself directly into the game without logging in. See [here](http://kancolle.wikia.com/wiki/Tutorial:_Proxy_Connection#API_Links) for more information.

**Comment by TheRedCrayon** [comment]
u wouldnt scare me when givin advice i removed the pic as an extra precaution as well

**Comment by dragonjet** [comment]
don't worry @Crazyteitoku i still got a copy of his API link on email :innocent: joke. glad to be of help.

**Comment by bamboo3250** [comment]
For a moment, I thought @Crazyteitoku's comment does sound like tsundere's catch-phrase :laughing:   btw, I want to ask this long time before, what is the doujinshi of your avatar?

**Comment by Crazyteitoku** [comment]
@dragonjet :stuck_out_tongue_closed_eyes: I am sure I can still dig up through my cache as well. Of course I don't do that sort of stuff.

@bamboo3250 probably one of the cutest image of 秋月 I can find :stuck_out_tongue_winking_eye:
