### ISSUE TITLE
[Bug report] extra shortbar under each of the quest boxes (github builds only)

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#145]
**Date Seen**:
~15-06-2015

**Version**:

**KC3 Kai v009 (git build) ID**: jljpednjlkddlmahfoljfjlnbollampe
**KC3 Kai v009 git revision**: 63e6b4402217c37476fb701dc8acd65571d4c57a
**Browser**: Chromium 64bit (currently on: 43.0.2357.125 (Developer Build 2d29e0c5afda590f32097f038157799d3015dd99 Linux))
**OS**: Archlinux 64bit (currently on: Linux: 4.0.5-1-ARCH)

**Bug Description**:
Extra bars appear under each of the quests that are selected from within the game.

Please refer to the screenshots provided below.

**Severity**:
Minor (?)

**Steps to Reproduce**:
1. Use KC3 Kai **github build**
2. Notice the quest boxes that was once grey/gray is now filled with data in it however there is an extra bar underneath each of these quest boxes.
3. If the bug is not apparent, try going into quests from within the game and select as few quests then deselect them and exit back out into the main menu (of the game).

**Actual Behavior**:
Extra bars as shown from within the screenshot. Again please refer below.

**Expected Behavior**:
These extra bars should not be shown.

**Troubleshooting/Testing Steps Attempted**:
Updated to the latest github build of kc3 kai. The bug is still apparent. Furthermore this is not an isolated issue.

**Workaround**:
None.

**Attachments**:
![](http://img3.wikia.nocookie.net/__cb20150618103619/kancolle/images/e/e6/Kc3kai-pre-010-bug.png)

**Comment by Crazyteitoku** [comment]
This issue was first sighted on wikia by @dragonjet  and was reposted again as a request from @bamboo3250. Further information can be found in the following link:
* http://kancolle.wikia.com/wiki/Thread:273592#4

**Comment by bamboo3250** [comment]
@dragonjet are u working on this? Do u mind if I read the code of Quest Tracking module?

**Comment by dragonjet** [comment]
ah I'm not working on the frontend right now. rewriting alot of library items before I get back to the panels

**Comment by dragonjet** [comment]
not applicable for the new interface
![ss 2015-06-27 at 08 07 46](https://cloud.githubusercontent.com/assets/557312/8389477/abb6101e-1ca3-11e5-8f85-50ff7a055ee9.jpg)

**Comment by Crazyteitoku** [comment]
:+1: Seems lot better as well with that new UI. Looking forward to it!
