### ISSUE TITLE
Quest A53 is untranslated

### ISSUE THREAD

**Issue by Kyogia** [dragonjet/KC3Kai#149]
![kancolle_2015-05-21_02-22-43](https://cloud.githubusercontent.com/assets/12779591/8268339/171c820c-17bd-11e5-926d-eaeb1b8312ca.jpg)
Maybe because the quest is still new?
My apologies for bothering you over a minor bug.

**Comment by bamboo3250** [comment]
Thanks for your reporting. We will fix this as soon as we can.
