### ISSUE TITLE
[v10] Dashboard: Vertical (Battle Mode)

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#158]
See #156 on what "Battle Mode" is.

To apply on the vertical panel.

**Comment by bamboo3250** [comment]
@dragonjet I noticed there is template for combined fleet in Battle Mode. Should I do it now or wait until event to test it properly? I can create a button to switch between single fleet and combined fleet.

**Comment by dragonjet** [comment]
now that you mention it, i forgot about that. its supposedly auto-detect:
`src/pages/devtools/themes/default/horizontal/horizontal.js`
`line 256` onwards. to test you can just put there `|| true` or something.
so in general we dont need a button since combined interface will only show if you really sortied using a combined fleet. what is currently missing is the actual interface XD I was planning to have it show both fleet 1 and 2 on the same screen without switching tabs

**Comment by bamboo3250** [comment]
yes, I'm also aiming for that. Hopefully I can finish it on this Friday.The one I'm doing now haven't satisfy myself xD

**Comment by dragonjet** [comment]
hm no rush, I'm also planning to delay horizontal's combined mode until next week, since no one will actually be able to use it :3
