### ISSUE TITLE
Remaining Improvement materials not updated

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#167]
<b>Date Seen:</b>
1-07-2015

<b>Version:</b>
KC3 Kai v009 (Chrome Web Store Version)
Browser: Chromium 32bit (currently on: 42.0.2311.152 (Official Build) m (32-bit)
Revision	c707233f90c2f1d16db21143b8f009ff9b14c3bd-refs/branch-heads/2311@{#509})

Bug Description:
Remaining Improvement materials not updated after equip improvements.

Severity:
Minor.

Steps to Reproduce:
1. Go to Akashi's Improvement Arsenal and take note of remaining improvement mats
2. Improve an equipment.
3. Take note of the disparity of the remaining materials displayed in the in-game speech bubble and the Admiral Panel.

Expected Behavior:
The remaining improvement materials are updated after equipment modernization.

Actual Behavior:
The remaining improvement materials remains when it was started.

Workaround:
The factory still displays the number of remaining materials, if the player would actually look at it.
Though this is less-than optimal workaround, returning to the main menu would update the remaining number of improvement mats.

Feature request:
Live update on remaining improvement materials available in (POST /kcsapi/api_req_kousyou/remodel_slot)

**Comment by dragonjet** [comment]
ahh thanks for noticing this
