### ISSUE TITLE
quest counter does not work properly

### ISSUE THREAD

**Issue by dustfan** [dragonjet/KC3Kai#170]
![kc3questcounterbug](https://cloud.githubusercontent.com/assets/12269598/8496732/718a6a8e-21b2-11e5-8c8c-45c6e1ce7103.png)

here's a bug(?) that i found while using the beta v10. i started to install the new kc3 kai extension with the weekly mod quest under 50% mark. but kc3 doesn't seem to start counting from the exact number of my remaining modernization left to do. so i decided to try modernizing one of my ship to see if it will fix this up, but it doesn't seem to work.. now it's.. 

![kc3questcounterbug2](https://cloud.githubusercontent.com/assets/12269598/8496829/30c97ac0-21b3-11e5-8dd0-b69f16723f8c.png)

**Comment by dragonjet** [comment]
ah yes, it's an independent counter that is supposed to be used faithfully in order to count correctly. if something was done outside the extension, or another device, or switching viewers, it will not count those done outside. the same thing happens when kc3 kai is used late on the week, it cannot count things done in the past. correct counting will then be done on the next reset.

unfortunately, game data does not have active counting. it's just something kc3kai is forcing itself to do xD

which you reminded me, there's no way to currently clear quest in case it resets. it may count 15 onwards even after reset

**Comment by dustfan** [comment]
well, then.. i guess i'm going to disable this feature for now..

oh , i'm interested in finding out how the battle environment when it's done.. seems like it's pretty cool to have it around.. would it shows the enemy comps on first hand? or.. do i need to battle them first and have the enemy comps recorded?

**Comment by dragonjet** [comment]
you'll have to discover them first before it shows up on succeeding sorties. once fully discovered, even boss node pattern can be seen right when you start the sortie.

**Comment by dustfan** [comment]
that's neat, thank you for the explanation

**Comment by LostLogia4** [comment]
What about the Weekly Quest 1? That one has four things to count out.

**Comment by McDohl** [comment]
![mcdohl 2015-06-04 02-04-24 92](https://cloud.githubusercontent.com/assets/13024936/8503912/261cc1e8-21f1-11e5-9f2c-b435a17e4c43.jpg)

seems like all quest did not count properly, doing transport or w/e quest not counted

**Comment by dragonjet** [comment]
@LostLogia4 in terms of interface, the 4 requirements will be compressed on the same area, but still, all red quests (sortie) are not counted as of today

@McDohl does this include green pvp, blue expedition, brown crafting, purple modding and yellow supply quests? only red sortie quests are supposed to be not counted.

**Comment by McDohl** [comment]
@dragonjet i didnt notice when i did the craft, repair, modernize and exped so sorry, gonna report in 40 mins or so after quest reset. but i did remember practice not counted too

updated pic for transport
![mcdohl 2015-06-04 02-14-58 17](https://cloud.githubusercontent.com/assets/13024936/8503974/c8d1f2c2-21f2-11e5-8f0f-db20cb5daf39.jpg)

**Comment by dragonjet** [comment]
* **Sorties** never counts :white_check_mark: acknowledged
* **Crafting** Akashi improvement quest not counting :white_check_mark: acknowledged
* **All-Types** did not clear counts after dailies reset :white_check_mark: acknowledged

thanks for the reports, I see now what you meant~

**Comment by dragonjet** [comment]
this issue will track Quest Resetting feature.

two other issues are separated into their own entries
* Sortie Quest Tracking #161 
* Equipment Modding Quest #175

**Comment by dragonjet** [comment]
Implemented a quest reset on latest 10.4 on push 93bd5fb0e32cd62af2dbbef8faf9251f4a7b5fdc

Hovering on the quest list will show 4 buttons where you can specify which quests are to be reset

![ss 2015-07-05 at 04 59 13](https://cloud.githubusercontent.com/assets/557312/8511030/41efa3bc-2337-11e5-9d3b-b84eaf02e631.png)
