### ISSUE TITLE
No Information Pops Up

### ISSUE THREAD

**Issue by SmokeyTheButt** [dragonjet/KC3Kai#171]
So I loaded it up and I noticed nothing displays in the panel. Just a red box.

I did touch the background colors, so maybe that had something to do with it?

![ss 2015-07-03 at 04 50 00](https://cloud.githubusercontent.com/assets/13164250/8497053/ac5ef300-213f-11e5-944f-0db9b6f62d98.jpg)

**Comment by bamboo3250** [comment]
Could you try enabling the local storage in Chrome? 
http://stackoverflow.com/questions/24456891/iframe-in-chrome-error-uncaught-securityerror-failed-to-read-the-sessionstora

Let see if it solves the problem or not.

**Comment by SmokeyTheButt** [comment]
I already had it set to "Allow local data to be sent" it seems.

**Comment by bamboo3250** [comment]
What version are you using? Ver 9 or 10 beta?

**Comment by SmokeyTheButt** [comment]
The Beta so I'd suspect there to be bugs. 
Ver 9 works just fine.

**Comment by bamboo3250** [comment]
I get your problem. You try switching the orientation of the panel by clicking on this button. The one you are using is still under construction.

![untitled](https://cloud.githubusercontent.com/assets/8078323/8498263/a6d52780-21bf-11e5-8e6c-c68b32c2fe76.png)

**Comment by dragonjet** [comment]
WAIT HAHAHAHA its the vertical layout

try docking the devtools to the left

**Comment by dragonjet** [comment]
@bamboo3250 you may also start trying vertical if you want. most of the codes you'll just need yo copy from horizontal, and mostly change just the css xD

**Comment by bamboo3250** [comment]
@dragonjet nice timing :grin: I'll read through your code and start working on it asap :+1:

**Comment by dragonjet** [comment]
Closing issue, we can track its progress via #157 and #158
