### ISSUE TITLE
Weapons equipped are not shown in panel

### ISSUE THREAD

**Issue by hbhbenny647** [dragonjet/KC3Kai#172]
Weapons equipped on ships are not shownin panel when I'm on homescreen. In battle it does show up though. Apparently, EO gauge did not update even when I reentered the map a few times.

![1](https://cloud.githubusercontent.com/assets/13168067/8502095/e7a64cf4-21e6-11e5-8f42-04c942141090.png)
![2](https://cloud.githubusercontent.com/assets/13168067/8502096/e7b24608-21e6-11e5-804f-3d8653863f3e.png)
![3](https://cloud.githubusercontent.com/assets/13168067/8502097/e7b4f1c8-21e6-11e5-9494-f0311f0400d8.png)
![4](https://cloud.githubusercontent.com/assets/13168067/8502207/f6847f06-21e7-11e5-8427-7849cedaab21.png)

**Comment by dragonjet** [comment]
ah yes, I did not notice this, thanks for reporting the equipment icons on normal modes.

about EO gauge, yes gauges are not yet implemented as of 10.3
