### ISSUE TITLE
Battle Mode Interface

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#173]
![kc3](https://cloud.githubusercontent.com/assets/13024936/8504006/5032f90a-21f3-11e5-8243-d2e4c748a212.jpg)

the new interface many features i not know like the yellow space, the numbers shown below gauge and the fuel and ammo modifier. and after you click the exit battle mode screen, how bout give us option to go back to battle mode again

**Comment by dragonjet** [comment]
the numbers below "World 2 -3" are the nodes you have traversed so far. this is similar to the old "compass result" popup, but new results go there. Which also lets you remember which node you are in and how far you are to boss node (might only be helpful if you memorize node IDs).

the yellow space is am upcoming feature which shows battle conditions such as detection, contact, air battle, enemy list, etc.

about fuel/ammo numbers, yes you are right, thanks for the suggestions.

about go back to battle mode, I also felt this while testing, but I'm still trying to find place on the normal mode where to put a button. but that's not all. I might become a drop-down of modes. I also have some other modes in mind: Grind Mode, Sparkle Mode, which does its own thing.

**Comment by McDohl** [comment]
thanks for the reply, look forward for the sparkle mode :+1:  1-1 master sparkle race :joy_cat:

**Comment by dragonjet** [comment]
:+1:
