### ISSUE TITLE
PNG type screenshot not working and screenshot kinda blurred out

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#174]
bug : as title said, its only use the jpg format
expected : pic saved as png format

I think kc3 screenshot image blur compare to external screenshot

screenshot taken by KC3kai beta
![mcdohl 2015-06-04 06-28-31 17](https://cloud.githubusercontent.com/assets/13024936/8505627/198372ea-2216-11e5-89dc-15929a6897d1.jpg)

screenshot taken by microsoft windows printscreen
![prtscr](https://cloud.githubusercontent.com/assets/13024936/8505653/318038d2-2217-11e5-8cd3-9a185ddc4f61.jpg)

**Comment by dragonjet** [comment]
just to confirm, have you refreshed the game after changing the settings? New configuration should only work after refreshing the API webpage

**Comment by McDohl** [comment]
@dragonjet as you said, its working, just ignore the png/jpg then. is there any hope to make the screenshot not blurred out? thanks in advance

**Comment by dragonjet** [comment]
can you add a screenshot of the blurred out png. Chrome is the one taking these screenshots and the internal `quality` setting is only applicable to jpg. I was thinking the png's it takes are already lossless

**Comment by McDohl** [comment]
png version kc3kai
![mcdohl 2015-06-04 07-05-55 28](https://cloud.githubusercontent.com/assets/13024936/8505746/556b8964-221b-11e5-8293-be6fabf43126.png)

png version microsoft windows printscreen
![tes2](https://cloud.githubusercontent.com/assets/13024936/8505747/61ebf3fe-221b-11e5-83a5-56971c601135.png)

**Comment by dragonjet** [comment]
hmm that is odd. i took my own png screenshot on kc3 kai and looks like this

what is your Chrome version?

![dragonjet 2015-06-04 08-10-56 62](https://cloud.githubusercontent.com/assets/557312/8505759/470a5efa-2224-11e5-8a16-850eb502eb5b.png)

**Comment by McDohl** [comment]
![again](https://cloud.githubusercontent.com/assets/13024936/8505792/b9974314-221c-11e5-9605-83128a919c4a.png)

**Comment by dragonjet** [comment]
same version as mine. right now I also have no clue about the png quality. what about OS? are you on windows or mac?

**Comment by McDohl** [comment]
windows 8.1 64 bit, nvm as i search it up on google, seems like its chrome faulty and the solution is to reinstal it... anyway thanks for reply this stupid chrome :/

can close this case already

![mcdohl 2015-06-04 08-19-49 19](https://cloud.githubusercontent.com/assets/13024936/8505944/a2bf6eec-2225-11e5-883a-2fbc791b8999.png)
image is fixed now :ok:

**Comment by dragonjet** [comment]
oh wow thanks for discovering this, I never knew Chrome could behave that way, where a reinstall can fix a bug. closing
