### ISSUE TITLE
Previous undone quest not updated in panel

### ISSUE THREAD

**Issue by hbhbenny647** [dragonjet/KC3Kai#177]
Previous undone quest yesterday are not updated today. The daily quest 4 & 5 is still in 'Current Quest' panel.
![1](https://cloud.githubusercontent.com/assets/13168067/8506716/b66e87f6-225d-11e5-8a44-f7ce84e2d2ef.png)
![2](https://cloud.githubusercontent.com/assets/13168067/8506717/b6732db0-225d-11e5-95ce-bc0f655c8c43.png)

**Comment by Crazyteitoku** [comment]
There is a "spillover effect" whereby the new and active quests shows on top of the old quests.

Another issue imposed is that if the user has 2-3 active quests out of 5 the remaining two quests (even though not selected) are still shown on the bottom. For reference the following snippet of the screenshot has been provided:
![](http://i.imgur.com/ezz0drd.png)

Also another bug is the old recurring quests are not clearing themselves out hence one gets several quests active. Again the following screenshot has been provided:
![](http://i.imgur.com/pSHqnb4.png)

I do not have the ability to select all 6 quests as I have not done the appropriate quest related to it but notice how in between the gaps in the latter screenshot there are still those old quests that are still visible from beneath the gaps of where the new and active quests are shown.

**Possible workaround(s):**
* Clear old quest when the user launches KC3 Kai at start.

**KC3 Kai v010 public beta revision:** 9d3e2b27b5902533c5f316e326ca70515e74cd69
**Chromium build:** 43.0.2357.130 (Developer Build aa8b82d8e6337201aa9477f25c603c289b5d7d0e Linux)

**Comment by dragonjet** [comment]
Implemented a quest reset on latest 10.4 on push 93bd5fb0e32cd62af2dbbef8faf9251f4a7b5fdc

Hovering on the quest list will show 4 buttons where you can specify which quests are to be reset

![ss 2015-07-05 at 04 59 13](https://cloud.githubusercontent.com/assets/557312/8511030/41efa3bc-2337-11e5-9d3b-b84eaf02e631.png)

**Comment by bamboo3250** [comment]
OMG, this is very useful and convenient to reset the quests. I need to update vertical layout to have this :joy: The new Battle Mode of the horizontal layout is also cool :+1:
