### ISSUE TITLE
Akatsuki Kai Ni

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#178]
Not sure if it has been mentioned already, but our lovely lady is missing her avatar image for her k2
![sem titulo](https://cloud.githubusercontent.com/assets/11778507/8509110/d670f16a-2267-11e5-912c-4d626409fa4b.png)

**Comment by dragonjet** [comment]
oh my dear lady you're right, is this webstore version or the recent beta releases?

**Comment by McDohl** [comment]
from the interface it should be webstore, cuz beta release it will have green outline if full hp, yellow outline if shouha and so on

**Comment by AlanSchaeffer** [comment]
That's right, it's the webstore version

**Comment by dragonjet** [comment]
ah yes that's right, we already have 437 Akatsuki on the betas. it will be fixed when v10 is pushed to webstore
