### ISSUE TITLE
2 Aerial Combats in Extra Operation 1-6

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#181]
In EO 1-6, there are Carrier Task Force battle nodes which contains 2 aerial combats, unlike other normal nodes.

![untitled](https://cloud.githubusercontent.com/assets/8078323/8511574/37654fce-2359-11e5-8991-44c2cab89116.png)

![untitled](https://cloud.githubusercontent.com/assets/8078323/8511584/e9a5c740-2359-11e5-9604-bfdad62a5dc7.png)

So here, besides `api_kouku`, we have `api_kouku2` as well. The format of `api_kouku2` is still the same as `api_kouku`.

**Comment by dragonjet** [comment]
ah never knew this. havent actually done 1-6 myself. do we just add the lost planes counts from both 1 and 2?

by the way, whats your json viewer?

**Comment by bamboo3250** [comment]
I did a few test and the result was like this:

kouku1:
`fighters_before_combat1 - fighters_lost_combat1 = fighters_after_combat1`
`bombers_before_combat1 - bombers_lost_combat1 = bombers_after_combat1`

kouku2:
`fighters_before_combat2 - fighters_lost_combat2 = fighters_after_combat2`
`bombers_before_combat2 - bombers_lost_combat2 = bombers_after_combat2`

The `fighters_after_combat1` was not necessarily equal to `fighters_before_combat2` because the fighters here include all the planes that have AA stats (e.g. Fighters, Dive Bombers, Torpedo Bomber and Seaplane Bomber). Likewise for bombers, they include all planes that can attack enemy ships (e.g. Dive Bombers, Torpedo Bomber and Seaplane Bomber). And we don't know exactly know what types of planes was shot down.

So I think we need more calculation if `kouku2` happens:
`fighters_lost_both_combats = fighters_before_combat1 - fighters_after_combat2`
`bombers_lost_both_combats = bombers_before_combat1 - bombers_after_combat2`

I'm using Eclipse and use `Ctrl + Shift + F` to automatically indent elements in json files xD

**Comment by bamboo3250** [comment]
My formula above will exaggerate the lost plane count but it will give accurate the number of remaining planes after `kouku2`. On the other hand, your current formula will give accurately the lost plane count but the number of remaining planes will be litter higher. So it is like a trade-off. It's still the best to show both phases if possible.

**Comment by dragonjet** [comment]
ah right now, we show it as `200 -10`, so I think just adding lost count is ok

if we'll be showing `200 >> 190`, that's the time we'll use your formula

probably in the future we can have settings that user can specify if he wanted to see end plane count or lost plane count

**Comment by bamboo3250** [comment]
That's right. Depending on what we focus on, it will use different formula. That would be great :+1:
