### ISSUE TITLE
Scrollbars not considered in detecting dashboard orientation

### ISSUE THREAD

**Issue by Erupi** [dragonjet/KC3Kai#182]
https://youtu.be/3yaT9BmIgWw
Based on the video I recorded, it seems the dashboard changed on how large is the width / height. Also using more than 3 girls, this happens as well :- http://i.imgur.com/oqNUa7R.png (This only happens when the windows are wider than 817px).

Well even with this "surprise", the dashboard still fine.

**Comment by bamboo3250** [comment]
This looks funny to me xD Actually the threshold to change the dashboard is 800px and that 17px comes from the scrollbar of the browser, which we haven't taken into account.

Thanks for reporting, anyway.

@dragonjet I think we should increase it to 817px or a little more, i guess?

**Comment by dragonjet** [comment]
ahh then I guess we should use `document.width` instead of `window.width` in `detectOrientation`. Let me see

**Comment by dragonjet** [comment]
I've been playing around with the orientation detection mechanism, and it seems the current way is still the best way. The desired effect is in between to only show it if the window is wide enough, and for the horizontal scrollbar to never be activated.

Adjusting the threshold higher or lower will generate mroe undesired results, showing horizontal scrollbar or using the wrong layout even if desired conditions are satisfied.

Currently the desired conditions are:
* **Vertical**: Show only if there is enough width and will not result to a horizontal scrollbar for the panel
* **Horizontal**: Show in any case the vertical panel conditions are not satisfied

Thus, I might mark this as `wontfix` if there are no more concerns about the method of changing layouts.

About the vertical surprise layout, it is known that it's not yet fully finished and is tracked on these two entries #157  #158
