### ISSUE TITLE
Various Ship Icon Updates

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#183]
I finished training my Kako to Kai 2 just now and found out this :smile: 

![untitled2](https://cloud.githubusercontent.com/assets/8078323/8545244/8154d1ce-24e7-11e5-9714-08ffb69d10ca.png)

**Comment by dragonjet** [comment]
ah yes I didn't notice

**Comment by dragonjet** [comment]
Add takanami kai and shouhou kai icons
