### ISSUE TITLE
Battle mode's fleet for pvp

### ISSUE THREAD

**Issue by dustfan** [dragonjet/KC3Kai#184]
this is probably minor since we didn't really have to worry about planes left in the fleet or about the fleet health and morale condition.. but i'd still report this bug anyway..
i was using the 2nd fleet to practice, but when the battle starts, the fleet shown on the battle mode panel was my 1st, not the one that i used to fight the practice match.. 
![pvp](https://cloud.githubusercontent.com/assets/12269598/8552668/8187dd26-2519-11e5-88b3-7baba73341bc.png)

**Comment by dragonjet** [comment]
ah thanks for the report~ oh, and is that also showing a buggy node list (not cleared from previous sortie)

**Comment by dustfan** [comment]
yes, but i was thinking that it will be fixed when v10 is out since it's pretty obvious.. oh.. and also nice "desperate :p" .. great timing when i fail get a t-cross during my transport hunt..
