### ISSUE TITLE
BETA Strategy Room Profile

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#185]
![github](https://cloud.githubusercontent.com/assets/13024936/8553118/7232a2d8-250b-11e5-9e1a-5843be51c532.JPG)
![github2](https://cloud.githubusercontent.com/assets/13024936/8553241/3f9b45a4-250c-11e5-97c2-cf6ae0786033.JPG)

as we can see thru the pics, here is my report 
* Player ID not listed properly (asdasd)
* Player Server is Unknown Server
* Win rate for Sorties is 0.96 where areas mine is 96%, suspected wrong calculation and it divide by 100
* Win rate for Sorties, PvP and Success Rate for Expedition is back to 0% if back to main menu

**Comment by dragonjet** [comment]
ah yes, thanks for the report.

though even after fixing this, the problem remains that we usually wouldn't get the "rate". it's only loaded when you go to the in-game admiral profile screen. I also found out that the real "rate" is not always the percentage between the win vs lose counts, so we can't manually do the math, (*something to do with one being the total throughout your career, and the other being for this month only*)

though I will note that when you go back to home port screen, we should not revert it back to zero if it was already loaded in the profile screen
