### ISSUE TITLE
BETA Ship on KC3Kai panel bugged

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#188]
After doing sparkling run on 1-1, I noticed something wrong at panel.
Below are the images if you scrap your meatshield ship, kc3 panel wont recognize some ship
![bug1](https://cloud.githubusercontent.com/assets/13024936/8561852/6a3a4758-2555-11e5-9dcf-19a5d2de6e5a.JPG)
![bug2](https://cloud.githubusercontent.com/assets/13024936/8561853/6a773f3c-2555-11e5-91a2-12040617aed4.JPG)

and i decide to try it further, seems like kc3kai panel can't recognize the ship index after the scrapped ship but can be easily fixed by go to main port
![wew](https://cloud.githubusercontent.com/assets/13024936/8561930/2cc6a8ac-2556-11e5-80a7-4615e28702c5.JPG)
![wew2](https://cloud.githubusercontent.com/assets/13024936/8561931/2cc6f37a-2556-11e5-833f-ef557526f7e6.JPG)

and one more thing, if you modernize using ship on your fleet, kc3kai still display that they are on fleet, but can be easily fixed by go to main port
![capture](https://cloud.githubusercontent.com/assets/13024936/8561854/6a79e9c6-2555-11e5-8841-729d91a50a60.JPG)

**Comment by McDohl** [comment]
still not work correctly, cmiiw, but i guessed you forget about this 
* kc3kai panel can't recognize the ship index after the scrapped ship but can be easily fixed by go to main port

example : if you have 5 ship, and you scrap ship on index 3, kc3 kai wont replace the index number 3 and so on, instead it will only show 1 and 2.

**Comment by dragonjet** [comment]
ah did you mean the bug where if I scrap the 3rd ship it will disappear including the 4th, 5th and 6th ship from the list, but will re-appear going to the main port?

**Comment by McDohl** [comment]
yes, sorry for bad choice of words :(

**Comment by dragonjet** [comment]
ah, no problem, thanks for pointing this out. didn't notice it myself

**Comment by McDohl** [comment]
another report, 

:negative_squared_cross_mark: seems like the modernized ship not removed from fleet index if it is failure, 

:white_check_mark: if the modernized ship is success then its removed from fleet index.

**Comment by dragonjet** [comment]
hm I'm not I can follow but I'll test this later on when I have some ships to spare for modernization

**Comment by McDohl** [comment]
ah, i think video will show it better than my choice of words :laughing: 
http://youtu.be/mn9AKqwI94Y

**Comment by dragonjet** [comment]
ohhhh i see xD thanks for the vid~
