### ISSUE TITLE
Suggestion on font colors in Dashboard

### ISSUE THREAD

**Issue by Erupi** [dragonjet/KC3Kai#189]
I realized texts like Engagement texts (Green T, Parallel and HeadOn) and getting AS or AS+ is red, wonder if you guys can change it to green so it suits the engagement and Air superiority achieved.

Edit : Somewhat its green now :v
Edit 2 : Looks like the red fonts only shown in PvP, I cant pvp right now since I done all of it, perhaps any of you want to test it? Pretty sure only PvP one only have the red text.

**Comment by bamboo3250** [comment]
If you know some HTML/CSS and how to inspect element in chrome then you will know why xD

@dragonjet I currently have already fixed this issue in my Battle Mode branch for both horizontal.js and vertical.js but if you want to fix it immediately then just go ahead :sparkles:

**Comment by Erupi** [comment]
Oh LOL. I totally didnt think to check HTML and CSS before hand *facewall*. Thanks for the quick fix! And no worry, you have all the time o3o/

**Comment by dragonjet** [comment]
@bamboo3250 ah I'll just wait for that so I can copy :relieved:
