### ISSUE TITLE
Screenshot not taken correctly at high DPI

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#193]
Screenshot not taken correctly at high DPI. Only one part of the game screen is taken.

Application version: 9
Client version: 5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36
Reported date: 6/11/15 4:28 AM
Reported by: A Google User

**Comment by bamboo3250** [comment]
Possibly this issue is also related? #49

**Comment by dragonjet** [comment]
ah yes we can mark this as duplicate and close, thanks for reminder
