### ISSUE TITLE
Panel doesn't update

### ISSUE THREAD

**Issue by URSvAir14** [dragonjet/KC3Kai#194]
When you return from a sortie or log in for the first time, the panel doesn't show the ships in my fleet. However when I click onto another fleet to view it, I can see the ships in that fleet, and when I click back onto my first fleet I can see the ships in that fleet. Sorry if it's hard to understand.

I assume this issue has arose because the panel doesn't update your fleet on the panel when you first log in or return from a sortie, instead only updating the panel when a different fleet is to be viewed.

**Comment by prokia123** [comment]
I have something similar to this, things like morale etc, don't update properly too.

**Comment by dragonjet** [comment]
ah this has been fixed on c0525291f391ed4723d10e95e02709cf9c46b2d2

which is equivalent to  10.8 WebStore version, can you try updating again?
