### ISSUE TITLE
"Air Battle" text cut-off on Battle Mode

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#195]
as reported on facebook message

**Comment by bamboo3250** [comment]
Is there any image for this issue?

**Comment by dragonjet** [comment]
Ah good thing he sent me the [http://puu.sh/iU2gx.jpg screenshot here]

**Comment by bamboo3250** [comment]
I don't have thí issue. I guess we need to do sth about responsiveness of the panel. The way it is now is still not flexible.

![pvp](https://cloud.githubusercontent.com/assets/8078323/8620311/c240ea3c-2759-11e5-9657-ec128148d4be.png)

**Comment by dragonjet** [comment]
hm since this is for the horizontal panel, we'll re-assess when we set the battle mode as main interface. will be doing few tweaks here and there
