### ISSUE TITLE
Status percentage not showing at home

### ISSUE THREAD

**Issue by mrbenz19** [dragonjet/KC3Kai#2]
![image](https://cloud.githubusercontent.com/assets/12208086/7440534/01f02d3c-f0e6-11e4-97e3-73130b4e2597.png)

As you can see from the screenshot, the percentage is not shown.
That is a screenshot from home screen.

PS: Oh, thanks for the quest translation btw :D

**Comment by dragonjet** [comment]
Ah, in order to view the "rates", you must go to the admiral info page in-game, the top-left menu. We also cannot compute this via basic arithmetic, win divided by total, since the game is using a different "rate" system, probably concerns "win rate" on a specific length of time.

**Comment by mrbenz19** [comment]
I see. So basically, this part only show the amount, not the percentage at the time.

**Comment by dragonjet** [comment]
yep
