### ISSUE TITLE
Timer allowance incorrectly applied to construction timers.

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#203]
Worked fine in v9, looks like a new bug in v10.

**Comment by bcc32** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1239097/8629093/28dd9576-270d-11e5-9830-f65e3da026b8.png)
(screenshot)

**Comment by McDohl** [comment]
i noticed it too, KC3Kai timer for construction will DING! at 01:00 ingame screen.

**Comment by dragonjet** [comment]
hm you're right. I forgot construction does not give the 1 minute grace period. thanks for reporting~
