### ISSUE TITLE
Some quest completions not being saved?

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#204]
Shouldn't be possible to have both Daily Sortie 1 and 2 selected.  Daily Sortie 1 didn't disappear when I went through the tabs of the Quest menu either.
![untitled](https://cloud.githubusercontent.com/assets/1239097/8629062/cafa2852-270c-11e5-8e68-7e63199c3700.png)

**Comment by McDohl** [comment]
ah yes, i noticed it too, but as @dragonjet said, in this post
http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Fleux-20150710135142/@comment-Dragonjet-20150710141327?action=history

![manualreset](https://cloud.githubusercontent.com/assets/13024936/8631181/23aa1ed8-279b-11e5-9041-08341409c634.JPG)

**Comment by dragonjet** [comment]
hi, if this was after the quest reset today, you'll need to click on the appropriate reset buttons to clear the statuses and revisit the quest page after that to refill what quests are really active.
