### ISSUE TITLE
Quest tracker not counting certain sortie quest progress

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#205]
![untitled](https://cloud.githubusercontent.com/assets/1239097/8631133/f4ac8b6e-2724-11e5-97d5-eb487979bde6.png)

Doesn't seem to work for sortie quests, as the counts stay at zero even when the quest is completed.  (Daily Quest 7 is also halfway done but displayed as zero).

**Comment by McDohl** [comment]
currently all sorties quest tracking are not working. I don't know about marriage quest since mine done long ago.

**Comment by dragonjet** [comment]
yes all sortie quests aren't tracked at the current version. we can follow this via this issue entry #161 which we'll close this one
