### ISSUE TITLE
Bug reports from other portals

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#206]
* :x: ship exp counter isn't auto-updating per battle
* :white_check_mark: ship being repaired has no indicator on panel
* :white_check_mark: "*Ahhh! You are leaving your girls! Are you sure you want to leave them?*"
* :x: ~~Screenshot/Translations on DMM screen~~ #163
* :x: ~~Back to battle mode button~~ #187
* :white_check_mark: Enemy Composition
* :x: ~~Screenshot button on battle mode~~ #187
* :white_check_mark: `/src/library/objects/Node.js#L149` apply fix to night battle contact
* :white_check_mark: shiplist duplicated. add `loadingFlag` while the list is loading
* :white_check_mark: separate tickbox for quest translation vs quest counting
* :white_check_mark: equipment name too long for the craftbox, multiline overlap
* :white_check_mark: reset all quests not working
* :white_check_mark: bring back the API link!
* :white_check_mark: darker shade of modernization quests box color

**Comment by McDohl** [comment]
ah yes, the screenshot totally missing on both battle mode orientation

**Comment by bamboo3250** [comment]
"Ahhh! You are leaving your girls! Are you sure you want to leave them?" - May I ask wth is this? xD

@dragonjet Regarding Enemy Composition, will you work on the updateDB() in SortieManager soon?

**Comment by dragonjet** [comment]
@bamboo3250  some people just suggested to change the exit confirmation message

about the enemy comp, tbh I didn't inspect what you did last time XD were you saving enemy comps in IndexedDB?

**Comment by bamboo3250** [comment]
@dragonjet I just added enemyId into `battle` object. You can always see the history though xD https://github.com/dragonjet/KC3Kai/pull/126/files

If you are busy, I can give it a try again xD

**Comment by dragonjet** [comment]
ahh I see, let me try it. since enemyId is already a field in the IndexedDB, we can query it directly from the where clause

**Comment by bamboo3250** [comment]
great, I'm looking forward to it :+1:

**Comment by dragonjet** [comment]
@bamboo3250 in relation to:

*darker shade of modernization quests box color*

Horizontal modernization quests color changed to: `#AE76FA`

Old color: `#B7B7FF` in case you wanna find and replace XD

**Comment by bamboo3250** [comment]
lol, let me pull the code first. Just came back from workplace. I will create a PR soon :3

**Comment by dragonjet** [comment]
whats a PR? :3

**Comment by bamboo3250** [comment]
ah pull request xD

**Comment by bamboo3250** [comment]
@dragonjet Have you pushed the change in horizontal layout to master?

**Comment by dragonjet** [comment]
just now xD

**Comment by bamboo3250** [comment]
Btw, what does the :x: mean? the one "ship exp counter isn't auto-updating per battle" has already been fixed, right?

**Comment by dragonjet** [comment]
hm I wasn't sure XD when I checked it didn't happen to me so I thought it was a false report

**Comment by bamboo3250** [comment]
Yeah, It also doesn't happen to me :confused:

**Comment by dragonjet** [comment]
@bamboo3250 enemy compo re-implemented. changed something in horizontal.js about when the faces are shown, under `CompassResult` function

**Comment by bamboo3250** [comment]
very nice, I'll check it now :+1:

**Comment by bamboo3250** [comment]
@dragonjet it works. Do you want to add this feature for Vertical Layout on today or delay to [Beta] v11.1?

**Comment by dragonjet** [comment]
I just uploaded 11.0 on releases xD

we can have it on 11.1 to be published on 15th

**Comment by McDohl** [comment]
just wondering, if we could include enemy formation to the panel XD, although its pretty minor feature

**Comment by bamboo3250** [comment]
Yes, i'll do that for vertical layout but not sure about horizontal because there's not enough space there.
