### ISSUE TITLE
Vertical Orientation PvP Faces

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#207]
![verticalpvp](https://cloud.githubusercontent.com/assets/13024936/8631632/e5ff161e-27a5-11e5-8ca1-d02026dc88c8.JPG)
vertical pvp orientation doesnt show the other player fleet on panel while horizontal is ok

**Comment by LostLogia4** [comment]
Two more things I wanted to report here:
1. the PvP battle panel keeps the previous sortie node numbers. (go to Map 1-1 then PvP to reproduce this bug)
2. I would suggest changing "Abyssal" to "Enemy", since you're fighting against other player's shipgirls, not Abyssal ships.
