### ISSUE TITLE
[feature request] Sync user data via Google Account

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#208]
Since I have to switch between machines quite often (e.g., work/school and home), it would be nice to have data in KC3Kai sync between Chromes.  Not sure how complicated this would be to implement, but it should be possible (chrome.storage API?).

**Comment by dragonjet** [comment]
ah yes, this can be tracked on #17 which was an early suggestion but will be far into the future and has no definite implementation plans right now

**Comment by bcc32** [comment]
Oops, somehow missed it in the Issue List.  And this time I actually checked. :/
