### ISSUE TITLE
Visual bug on Quest box overflow

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#209]
Looks like the sorties was simply not counted in Sortie Quest 1, 2 and 3.

Also, the "Daily Equipment Modernization" text spills over to new line in the quest list.
![questbug](https://cloud.githubusercontent.com/assets/12930396/8631859/774fcdc0-27b5-11e5-8391-00dc845fc78d.jpg)

**Comment by dragonjet** [comment]
sortie quests being tracked here #161

is the spillover from right docking or bottom docking?

**Comment by LostLogia4** [comment]
Bottom docking.

**Comment by dragonjet** [comment]
@bamboo3250 my fix for this on horizontal, since we can't help having limited width for those boxes is to have a sub-div which is 1000px long, and the main div  being oveflow:hidden, just to not make it wrap into a new line xD

**Comment by bamboo3250** [comment]
I fixed this issue in #213

**Comment by dragonjet** [comment]
ah the problem with just `overflow:hidden` is that if text do get cut off "Daily Equipment Modernization" just becomes "Daily Equipment", but what is desirable is we at least see "Daily Equipment Moderni"

**Comment by bamboo3250** [comment]
Oh, please open this issue one more time. I'll try again xD
