### ISSUE TITLE
"Chrome Desktop Notifications" does not work 100% of the time

### ISSUE THREAD

**Issue by DJayDisco** [dragonjet/KC3Kai#21]
As title implies, even when I'm on the game window itself (Playing using API Link), when an expedition ends or construction ends, the notification sound plays, but the pop up notification sometimes doesn't pop up. 

"Chrome Desktop Notifications" is checked in the settings menu. Can't figure out why this is happening.

**Comment by dragonjet** [comment]
Hi, you'll need to dismiss the previous notification of the same type for it to work. You will see a bell icon on your bottom-right taskbar, which are Chrome Notifications. Click that and it will show you messages you have not yet dismissed. If you click on "X" per message, it will work again.

**Comment by DJayDisco** [comment]
ah icic, what will be the easiest way to dismiss such notifications? Will mousing over the notification box count as dismissing it?
