### ISSUE TITLE
Nanamin/JWT - Partially visible panel (No SS)

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#210]
**Date Seen**:
11-06-2015

**Version**:

* **KC3 Kai version**: v10.8 (webstore build)
* **Browser**: Chromium 64bit (currently on: 43.0.2357.132 (Developer Build 20dadcd155faa98cbac3681feb689ec8eb807a01 Linux))
* **OS**: Archlinux 64bit (currently on: Linux: 4.0.7-2-ARCH)

**Bug Description**:
The loading of the profile data failed and the resulting data shown within KC3 Kai frame results in blank screen for where values are meant to be shown e.g. ship counts, equipment counts, fleet listing. Please refer to screenshot for more information.

This is from switching updated version of KC3 Kai github build 7586ee87e86b921438a1173c33a37ae90e702d12 to the webstore build via disabling github build and enabling the webstore build.

**Severity**:
Blocker

**Steps to Reproduce**:
1. Disable KC3 Kai **github build**
1. Enable KC3 Kai **webstore build**
2. Start game as you normally would. The following example is done via refreshing and using new API link.
3. Wait for errors to show up resulting in blank information.

**Actual Behavior**:
Blank player data. Please refer to screenshots attached. Also an error appeared declaring "Updating interface values failed".

**Expected Behavior**:
Player data should be visible within KC3 Kai frame as seen in github builds. Also no errors should be visible.

**Troubleshooting/Testing Steps Attempted**:
None yet - will document more later on.

**Workaround**:
Use github build.

**Attachments**:
![screenshot from 2015-07-11 13-59-26](https://cloud.githubusercontent.com/assets/12234182/8632267/3718bdda-27d7-11e5-9b49-790db72fd0db.png)

**Comment by Crazyteitoku** [comment]
**Update** : By uninstalling KC3 Kai extension from within extensions page and then re-installing KC3 Kai webstore build via Google webstore the issue no longer persist - that is it is working similarly like github build.

**Comment by Poihibited** [comment]
Once you pick up built ships, the max ship/max equipment max updates to 1/100 (ship) and 1/400 (equipment, value may be different with other ships, as I built a DD). But then again, I don't know anything about this, so... I was going to do more testing, but then the problem repaired itself once I completely shut down Chrome, and started it back up. Love the new interface though ^.^

**Comment by Crazyteitoku** [comment]
My guess is that the initial update from v009 to v010 (or v10.8) is really that the update tried to use the old data left behind and instead of downloading as well as formatting the new data to work with the newer one it fails to do so. Hence there were errors and as a result the information as presented results in blank. 

Therefore in theory, if there were any either large improvements between versions and/or new UI changes that are dramatic. The extension should always try and download new data as necessary.

Yeah the new interface is quite nice, looking forward to the features being added from what was available in the v009 github build. Things like enemy formation and enemy fleet composition - i.e. the learning of enemy fleets.

**Comment by dragonjet** [comment]
hm you may be right about the extension might not be compatible with old data anymore, however localStorage between webstore and dev builds are different since they have different IDs. though if you have played on webstore version before trying out the github build, then it is possible.

I may not have followed 100% but is there a problem that still persists?

**Comment by Crazyteitoku** [comment]
Nope the case is closed, I am still running on webstore build and checking for any issues.

Yeah I figured they would be different ID but I am just still going to assume that the old data carried over from 009 may most likely be incompatible with 010.

Also some Mac users are reporting issues with the latest versions of kc3 kai. Both Nanamin and JustWastingTime on kancolle wikia are reporting partially visible kc3 kai interfaces (not in strategy room or whatever just in the main UI).

**Comment by dragonjet** [comment]
hm I jope they do get screenshots xD

**Comment by Poihibited** [comment]
I have a Mac, but I have not been experiencing this problem, but I am using an outdated OSX, so having the latest OSX may have caused the problem... If I do encounter this problem eventually, I will get screenshots of it.

**Comment by dragonjet** [comment]
thanks @Poihibited ~

**Comment by Poihibited** [comment]
I found another bug, which was the quest interface having more than 5 quests (I was too lazy to get the 6th quest slot ._.). It has Daily Sortie 1 and 2 at the same time, and I believe that Daily Sortie 2's requirement is Daily Sortie 1. From what I understand, I believe this bug was caused because I did not complete Daily Sortie 2 yesterday, and activated Daily Sortie 1 today. Here is a screen shot:
![screen shot 2015-07-11 at 11 30 16 pm](https://cloud.githubusercontent.com/assets/13284259/8636546/c73779f8-2825-11e5-9cd3-4f8534644ef0.png)

**Comment by dragonjet** [comment]
ah yes this is expected if you did not click on reset dailies earlier on today. unfortunately, we do not have timer-detection system in place that will automatically reset quests on 5am JST so the users need to trigger resetting counts and states to zero manually.

**Comment by dragonjet** [comment]
hi guys, I didn't notice @Crazyteitoku already uploaded a screenshot for it

This is a problem when you switch from one account to another, not a matter of webstore nor version.

It's already fixed as of 178dd1407588e8a144ccd265b9450b0411dba79f
