### ISSUE TITLE
Daily Development 1 and Daily Sortie 5 quest counting number is wrong.

### ISSUE THREAD

**Issue by nicky008** [dragonjet/KC3Kai#212]
![capture2](https://cloud.githubusercontent.com/assets/10517990/8632831/35c017ee-27e6-11e5-922d-0e0efbcb853b.PNG)

And this...

![capture4](https://cloud.githubusercontent.com/assets/10517990/8632839/8a43a4e8-27e6-11e5-9ea8-cb299c8e9ac4.PNG)

Today, I didn't even do this quest yet.

For the Daily Sortie 5, I did it for 2 in 3 ships total and the counter is shown just 0.

**Comment by Crazyteitoku** [comment]
You need to hit the button to reset the dailies. Just simply hover your mouse over that area of the screen in your second picture. You will also need to do it every week and month as needed.

I saw a similar issue you have posted previously and was going to upload a screenshot depicting on how to go about clearing those recurring quests from kc3 kai UI before real life interrupted me.

![kc3kai-0108](https://cloud.githubusercontent.com/assets/12234182/8632874/0cdaad8e-27f1-11e5-97f7-38328dbc64f2.png)

**Comment by nicky008** [comment]
This solution is just like pressing F5 button method.

I think this method also made the other quests' status, whatever progress is going, reset to zero too. Which mean that the other quests might have no bug unlike this occurring quest but the really main problem is not solved yet.

**Comment by Crazyteitoku** [comment]
As far as I am aware each of the reset buttons should only reset the respective recurring quests. Whilst it is possible for instance hitting reset weeklies button may also inherently reset dailies but that isn't necessarily an issue rather it is more of convenience factor personally.

Ideally, in the near future the need for manual intervention may no longer be necessary.

**Comment by dragonjet** [comment]
Sortie Quests tracking is not yet implemented, and will be tracked here: #161 

About the quest tracking, you need to click on "Reset dailies" at the start of the day, before doing anything else. This will reset all counts to zero, which is what really happens in game. It is advised that you should not start, activate and do some quests before clicking "restart" buttons. That will lead to what happened in your case.

Events should happen in order:
1. Game ticks on reset (5am JST)
2. Reset buttons must be clicked whenever you're available (all dailies go back to 0)
3. Revisit Quests page
4. Re-activate quests you want to do (this re-fills KC3改 list with all 0 counts)
5. Start doing the quests from 0/5 to 1/5... 2/5... 3/5...so on.

Same thing for weeklies. Click [Reset Weeklies] by the time you are available every after Monday 5am JST.
