### ISSUE TITLE
[Webstore version] Reset button does not work

### ISSUE THREAD

**Issue by Erupi** [dragonjet/KC3Kai#215]
So I got a report from a friend that Reset Dailies button does not reset the overlay counters. He had to reset the game to reset the counter after resetting it from Strategy Room panel. Not sure if same issue might happen on weeklies and monthlies too.

**Comment by AlanSchaeffer** [comment]
For me, Reset All did not seem to respond to my clicks while the other three buttons did their stuff

**Comment by dragonjet** [comment]
ah yes mentioned in #206 that reset all quests button doesn't work.

will continue tracking on this issue entry

**Comment by dragonjet** [comment]
Fixed as of 4a9dabc93fd82762d7efd7d122d34dcd8b9935af
