### ISSUE TITLE
Exit Battle Mode -> Hide Battle Mode

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#216]
There are a few infos that are not shown in the battle mode, that at very specific scenarios are relevant to know (in my case, it was the ship count). The way to access these infos is by exiting battle mode, but then you can't go back after that.
If it's possible to detect when you get in/out of a battle, it could have an option during sorties or battles to return to battle mode from normal mode.

EDIT: Great. I read all the other issues and left the one where you enumerated a bunch of adjustments for last and it seems you already referenced something like that there. smh
It does link to another issue where it does not mention going back to battle mode, just that it will be separated in two themes though

**Comment by dragonjet** [comment]
yes there is a plan to use battle mode as a main theme so there is no need for switching

**Comment by AlanSchaeffer** [comment]
I...... I just noticed there actually IS a kanmusu counter below the HQ exp bar. I don't even...
I must be some special kind of stupid lol

**Comment by dragonjet** [comment]
Currently, there is an option to switch theme in the settings page, but V-Ten (*the supposed battlemode-only theme*) is not yet implemented.

hm let's re-assess once we implement V-Ten theme, we'll close this for now.
