### ISSUE TITLE
Battle mode defaults to first fleet

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#218]
It'll display the stats for the 1st fleet, even if I send, say, 2nd fleet for the sortie.

**Comment by bamboo3250** [comment]
I don't have this issue in both orientation. It still shows 2nd fleet when I go sortie with 2nd fleet.

**Comment by LostLogia4** [comment]
Forget to mention but this is in PvP... yeah, it worked fine in regular sorties.
Also, this one's in wide orientation.

**Comment by bamboo3250** [comment]
Did you try the latest github version? I believe it was fixed in 8cc5bd8e48bffed746fc7f46c5fc1a5fa875d0dd

**Comment by dragonjet** [comment]
oh. that fix is not yet included on webstore vers
