### ISSUE TITLE
Vertical Orientation Battle Mode (Combined)

### ISSUE THREAD

**Issue by Erupi** [dragonjet/KC3Kai#219]
http://i.imgur.com/7lo0CIn.png

The LoS number sees like out of place, might want to fix that :3

**Comment by McDohl** [comment]
ah yes, we have same report on this issue
https://github.com/dragonjet/KC3Kai/pull/213

**Comment by McDohl** [comment]
@dragonjet can close this since its already fixed on https://github.com/dragonjet/KC3Kai/pull/222
