### ISSUE TITLE
About changing ships

### ISSUE THREAD

**Issue by Samrael** [dragonjet/KC3Kai#22]
this happens to me when I was moving my ships for repairing them with Akashi
![bug](https://cloud.githubusercontent.com/assets/12229097/7449117/9ff0c5d6-f1eb-11e4-9d22-12c804d4f79e.png)

**Comment by dragonjet** [comment]
Hi, about the HP bars being cut-off, it has been fixed here 51d749aff81f25ac9d9cded386cba5564206d1ed and will be up for v006. thanks~

**Comment by Samrael** [comment]
Yeah thanks I know, but I was talking about the three Kiso's on my fleet~

**Comment by dragonjet** [comment]
ah thanks for reporting~ #3 might be related

**Comment by nevrending** [comment]
I think this can be safely closed as it has been fixed in PR #97 
@Samrael it would be great if you could confirm that the issue has been resolved

**Comment by dragonjet** [comment]
ah yes it's the same bug. @Samrael might not be able to test it now since he might be reporting from the webstore release. The fix is not yet published atm. I'll close it for now

**Comment by nevrending** [comment]
Ah right, my bad. Since I've always pulled mine straight from upstream, made me forgot that there's hasn't been any new webstore release. :laughing:
