### ISSUE TITLE
[Bug report] Overlapping current equipment count and maximum equipment count when sortieing.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#227]
**Date Seen**:
11-06-2015

**Version**:

* **KC3 Kai version**: v10.8 (github build)
* **KC3 Kai github revision**: 9b0e20a1e1197a8ef838d3f8df2981086204f700
* **Browser**: Chromium 64bit (currently on: 43.0.2357.132 (Developer Build 20dadcd155faa98cbac3681feb689ec8eb807a01 Linux))
* **OS**: Archlinux 64bit (currently on: Linux: 4.0.7-2-ARCH)

**Bug Description**:
**This mainly affects for those whom have purchased ship slots and presumably have at least 230 ship slots unlocked in total or more.**
Equipment counts when sortieing is overlapping and may get worse should more slots be enabled in the future.

Please refer to the following screenshot for more information.

**Severity**:
Minor

**Steps to Reproduce**:
**Make sure that your game account has at least 230 ship slots unlocked in total**
1. Sortie your fleet to any random map.
2. Notice that equipment counts are overlapping right next to ship slots.

**Actual Behavior**:
Equipment counts are overlapping and may get worse in the future as progressively more ship slots are enabled along with more equipments being stored over time.

**Expected Behavior**:
Either when sortieing, the equipment slots :
* Be counted by itself and not show as what it is current; current/maximum.
* Has increased gap between current versus maximum so that the digits does not overlap.
* Be placed elsewhere where there is enough space to show current/maximum equipment counts in order to prevent information getting overlapped.

**Troubleshooting/Testing Steps Attempted**:
Testing has been done when one hoards equipments up to 1000 equipments, however the case is not so prevalent if and when the player has less than 1000 equipments as the digits and the respective fields does not overlap.

**Workaround**:
Not really a workaround however, by scrapping the unnecessary equipments one can avoid seeing the equipment counting overlaps when sortieing. This is most likely the only temporary solution available.

**Attachments**:
![](http://i.imgur.com/J157kna.png)

**Comment by bamboo3250** [comment]
Does this happen to Vertical Layout?

**Comment by Crazyteitoku** [comment]
@bamboo3250 the following screenshot is for vertical layout but this issue is apparent on both vertical and horizontal layout.

In fact the horizontal layout it is worse, old quests appears on the bottom whereas when switching back to vertical layout those old quests does not appear.

Please refer to the following screenshots:
![screenshot from 2015-07-13 17-47-24](https://cloud.githubusercontent.com/assets/12234182/8645241/e7aab376-2988-11e5-958b-83be85efcc84.png)
![screenshot from 2015-07-13 17-51-33](https://cloud.githubusercontent.com/assets/12234182/8645240/e7aaaaf2-2988-11e5-8c72-f8a24e1f791c.png)

**Comment by dragonjet** [comment]
whoa a thousand equipment? how is that even possible :open_mouth: what's the max atm?

**Comment by bamboo3250** [comment]
If I'm not wrong, it should be 500 + 40 * 15 = 1100 for 15 times buying 10 ship + 40 equip slots.

**Comment by Crazyteitoku** [comment]
Yeah what @bamboo3250 said. You start off with like 500 equipment slots or whatever and each time you purchase more ship slots it also increments your equip slots at like 4:1. 4 part of equip slots to 1 part of ship slots that is.

**Comment by dragonjet** [comment]
aren't we currently at 220 max ships? 500+ 40 x 11

**Comment by Crazyteitoku** [comment]
No, maximum is 250. Devs tweeted 250 slots sometime before or during Spring 2015 event iinm.

**Comment by dragonjet** [comment]
for someone in charge of wikia recent updates, I don't even know. I'm getting old for that kind of stuff

**Comment by Crazyteitoku** [comment]
lel I think Blasterion also had like 240 ship slots back then. Now he has like 250. Blasterion from kc wikia.

**Comment by bamboo3250** [comment]
tbh I also don't know the maximum number of ship slots but I checked the HQ to see the number of ship slots left up to the maximum :grin:

**Comment by LostLogia4** [comment]
@Crazyteitoku
Well it's already 230 when I started playing the game, 240 sometime before Spring 2015 event, and 250 shortly after the event.

**Comment by Crazyteitoku** [comment]
Wait, you're Blasterion? @LostLogia4

**Comment by dragonjet** [comment]
whoa, while I remember 220 like it was yesterday. I really am getting old for this :(

by the way @Crazyteitoku this is @LostLogia4 on wikia

http://kancolle.wikia.com/wiki/User:Ar-cen-ciel

**Comment by Crazyteitoku** [comment]
@dragonjet ah yeah I had impression @LostLogia4 is Ar-cen-ciel but what? oh separate case with ship slots :stuck_out_tongue_closed_eyes:

**Comment by bamboo3250** [comment]
@Crazyteitoku could you help me check again after #232 gets merged?

**Comment by Crazyteitoku** [comment]
@bamboo3250 will do

**Comment by Crazyteitoku** [comment]
Sorry that had to take a bit of time to get the equipment counts up close to what it was and to double check but it is definitely fixed. Thanks! :stuck_out_tongue_closed_eyes: 
![kc3kai-0110-0](https://cloud.githubusercontent.com/assets/12234182/8717205/7c5bb7f4-2bdc-11e5-8ec0-104c2f565f77.png)
![kc3kai-0110-1](https://cloud.githubusercontent.com/assets/12234182/8717206/7c5d3584-2bdc-11e5-949c-eeb26b9f71bc.png)
![kc3kai-0110-2](https://cloud.githubusercontent.com/assets/12234182/8717207/7c61c22a-2bdc-11e5-8ffb-94f1ccba24a7.png)

**Comment by bamboo3250** [comment]
okay, that's good to hear :+1:
