### ISSUE TITLE
Maelstrom resource type and count shown are wrong

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#234]
*Anyway, I think there is a mistake where when you jump to whirlwind and it is suppose to reduce your ammo. However it shows as reduce in fuel. * - [WongTheThief](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-WongTheThief-20150713090309?permalink=282638#comm-282638)

![kc3fuelerror](https://cloud.githubusercontent.com/assets/557312/8651518/f2aa5d1c-29ab-11e5-8cfa-184570c0d566.jpg)

**Comment by bamboo3250** [comment]
Oops, I saw this bug a few days ago but forgot to create an issue for it xD
