### ISSUE TITLE
Node numbers 

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#240]
Will we get these changed to the letters on the wiki and will they be consistent? (i.e. If you go from node I to Boss node E, will going to Boss node E from another node be see as like Boss node H?)

**Comment by dragonjet** [comment]
there is currently no map to create our own map, nor to pattern it with the nodes on the wikis. right now, we can make do with just showing enemy faces on next node before compass spin.

**Comment by Javran** [comment]
I'm now pretty sure these numbers are for edges.

Just in case we want to change it back to letters and be consistent with wiki maps, I've created a [gist note for this](https://gist.github.com/Javran/c5c7bf8d40524559b7d9) and will be updating it.

Please feel free to comment with your knowledge, as I'm still new to the game and can only get access to limited maps.

And it will help to let more people know about this gist :)

**Comment by dragonjet** [comment]
ah do we make people comment on what number they got and what letter it is on the wiki?

**Comment by Javran** [comment]
I think that will be helpful to also create a wiki page for this(or is there an existing one?), let me know the link and I'll also keep an eye on it :smile:

**Comment by dragonjet** [comment]
you mean wiki on wikia? xD or wiki on github? :v 

I haven't informed the users yet

**Comment by bamboo3250** [comment]
@dragonjet I think we can start doing the conversion from KanColle server Edge Id to Wikia Node Letter by the current data. For the rest, we still show numbers so we will know that they haven't been done yet.

Can I start working on it now?

**Comment by dragonjet** [comment]
sure, something like an `\src\data\edges.json`?

**Comment by bamboo3250** [comment]
yes, I will build it from scratch and load in KC3Meta

**Comment by dragonjet** [comment]
:+1:
