### ISSUE TITLE
New quest counter going over limit

### ISSUE THREAD

**Issue by shinyemerald** [dragonjet/KC3Kai#241]
So this feature that was recently implemented (I believe) allows you to see your progress on quests, but it doesn't reset on completion.

http://puu.sh/iYar3/7a2121db13.jpg

**Comment by dragonjet** [comment]
yes you will need to check the panel, mouse over the mini-quest list, then 4 buttons will show up. you'll need to manually click appropriate reset buttons to get it back to zero. after that you'll need to revisit the quests page to repopulate your active quests
