### ISSUE TITLE
[Feature] Automatically reset counter when navigating quest list and clearing the quest

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#244]
@dragonjet I would like to work on this feature. Is that okay?

**Comment by McDohl** [comment]
if it means that no more manual reset counting then i support :+1:

**Comment by nicky008** [comment]
:+1: too...

**Comment by shinyemerald** [comment]
ohh i found out you could manually reset, but automatic would be fantastic

**Comment by bamboo3250** [comment]
Yes, that means you don't have to manually reset the quests on the next day but still have option to do so. According to my investigation, it's possible and it may take a few days for me to test it thoroughly before I can give others to test it.

**Comment by nicky008** [comment]
So semi-manual mode still be possible for this case, right?

**Comment by dragonjet** [comment]
hmm good idea :+1:

right now what we do is that `if quest.status = 3` (means complete), just deactivate and remove from list. but we can also set counter back to zero during that time. I never thought of this before xD

though after this it will still be recommended to click on reset buttons every day and week for those quests that you failed to finish

**Comment by bamboo3250** [comment]
I won't guarantee that it will work perfectly but will try to cover as many cases as possible. So manually reset function still must be kept.
