### ISSUE TITLE
Night Battle Indicator on Practice

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#248]
I dunno if this is intended but from what i tried night battle indicator on Practice is always cross marked while its actually need to night battle if want to secure better score

![night](https://cloud.githubusercontent.com/assets/13024936/8670450/7d70c5d0-2a47-11e5-914f-4c5d6ce36339.JPG)

**Comment by bamboo3250** [comment]
It sounds like a bug or the API actually doesn't provide that.

**Comment by dragonjet** [comment]
ah @bamboo3250 have you checked the response? I haven't looked at it and still left PvPNight as an empty function

**Comment by McDohl** [comment]
@bamboo3250 after re-checking the image, seems like the fourth eq counts collided with fuel and ammo gauge on single fleet,

**Comment by bamboo3250** [comment]
@dragonjet I'm going to check it now in case you haven't fixed it yet xD
@McDohl oh that's true. I didn't notice it before. Will fix it now :open_mouth:
