### ISSUE TITLE
Toggle between Total, Accumulated and Remaining Admiral EXP

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#251]
The version 8 and 9 shows the remaining EXP, while version 10 shows the accumulated HQ EXP since the last levelup.

Is there a way to make it toggle like the LoS value in Admiral Panel?

**Comment by nicky008** [comment]
:+1: My friends also asked this too. Wonder if there is a button on the panel (or at least a button on the setting page) to toggle it.

**Comment by dragonjet** [comment]
oh I must have missed it, it should always be the remaining exp

**Comment by dragonjet** [comment]
after testing, doesn't happen to me on all 4 states, horizontal normal/battle and vertical normal battle, or probably someone already fixed this in the dev versions?

**Comment by LostLogia4** [comment]
I thought this was supposed to be a feature request?

**Comment by dragonjet** [comment]
hm but showing the accumulated exp instead of remaining is not the intention XD

i also marked this as feature for the switching idea like elos

**Comment by ethrundr** [comment]
this one has been solved, I believe?

**Comment by nicky008** [comment]
Waiting @dragonjet merge this @ReiFan49's fix and we'll test it... :3

**Comment by dragonjet** [comment]
ah yes, it wasn't marked when @ReiFan49 pushed it. I'll manually close now
