### ISSUE TITLE
Quest Tracking covers the 50%/80% indicator

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#253]
Quest Translation Label : 
* Can you move the quest counter overlay slightly to the side so that it will not block the 50%/80% icon? via http://kancolle.wikia.com/wiki/User_blog:Dragonjet/KC3改#comm-282976
* there was also a suggestion to make the label a bit transparent so we can see the 50% n 80%

**Comment by dragonjet** [comment]
Separated heartlock counter into #258

Separated ship totals into #259

**Comment by dragonjet** [comment]
bbe72773ec7574a390f83587aea652f4bce0ed6c

![ss 2015-07-15 at 11 45 57](https://cloud.githubusercontent.com/assets/557312/8690459/1cccf1d6-2ae7-11e5-9951-b5410a99ce9c.jpg)
