### ISSUE TITLE
Quest Reset

### ISSUE THREAD

**Issue by JD-Kurotoshigami** [dragonjet/KC3Kai#260]
separate the Daily/Weekly quest reset buttons into Quest Types: Daily Sortie, Daily Expedition, etc.

**Comment by dragonjet** [comment]
eeeh what for jede?

**Comment by JD-Kurotoshigami** [comment]
earlier... I pressed the daily quest reset since it still had records of the previous day, but I was doing some dailies that time so even the ones i am doing are reset :'D

**Comment by LostLogia4** [comment]
Wouldn't it be easier to code it to reset the tally once the quest is cleared?

**Comment by dragonjet** [comment]
@bamboo3250 talked about it on another thread i forgot which

**Comment by bamboo3250** [comment]
I think this is a new proposed feature, not the one about automatically resetting quest list.

It's like separating Daily reset button into 5 kinds of buttons for Daily Sortie, PvP, Resupply/Repair, Expedition and Modernization.

**Comment by dragonjet** [comment]
ah yes, it was what JD was suggesting, but I think what LostLogia4 said can suffice

**Comment by bamboo3250** [comment]
oh right. I misunderstood what LostLogia4 said xD I'll finish that soon.

**Comment by LostLogia4** [comment]
One thing to note though, the tally still have to be reset at certain intervals, like every 5AM JST everyday for daily quests.

**Comment by bamboo3250** [comment]
Unless we have a mechanism to detect the time and time zone, it's impossible to reset the quest at 5AM JST since the API response doesn't provide enough information. Hence we still have to rely on some workaround, which seems to have the same effect but still potentially has bugs inside.

**Comment by dragonjet** [comment]
I tried to do this before, using server time included in the response header. detecting server time is not a problem, it's a problem of "shall we reset it now? have we passed 5am since the last time he did something?". my old implementation included a timestamp which we store locally every time an API is called. On the next API call it will check if `oldServerTime < 5am < thisServerTime`, which is painful to do by the way - but I postponed the implementation because it really became harder to detect weeklies.

if anyone is up to the task I can provide my old attempt and can continue where I left it

**Comment by bamboo3250** [comment]
@dragonjet omg, I didn't notice that server time in GMT :scream: I would like to see that :sparkles:

**Comment by dragonjet** [comment]
```
// If there was a last quest time
if(typeof localStorage.lastQuest != "undefined"){
	// Convert into Date objects
	var dateQuest = new Date( localStorage.lastQuest * 1000 );
	var dateNow = new Date( utcNow * 1000 );
	// Get number of days since epoch
	var epochDaysQuest = Math.floor(localStorage.lastQuest / 86400);
	var epochDaysNow = Math.floor(utcNow / 86400);
	
	// Check if now is after 8pm AND (last check was earlier today OR anytime in the past days)
	if(
		(dateQuest.getHours() < 20 || epochDaysQuest < epochDaysNow)
		&& dateNow.getHours() >= 20
	){
		resetDailies();
		
		/* HOLY SHIT I HATE JAVASCRIPT DATES
		// Check if triggers a weekly reset as well
		if(
			(dateNow.getDay()==0) // if Sunday (reset is 8pm Sunday during UTC)
			|| (dateNow.getDay() < dateQuest.getDay()) // if last check "day" is more than today, means last check was last week
			|| (dateNow.getDay() == dateQuest.getDay()) // if it's the same day, 
			|| (
				(dateNow.getDay() > dateQuest.getDay()) // if day today is greater than last check
				&& (epochDaysNow - epochDaysQuest > 7) // then must be more than 7 days difference
			}
		){
			
		}
		*/
	}
	
	// Check for monthly reset at midnight
	
}

// Set time now as the last quest time
localStorage.lastQuest = utcNow;
```

**Comment by bamboo3250** [comment]
Thanks, this helps alot :+1:

**Comment by dragonjet** [comment]
for an example on how to get `utcNow`, you can search `\src\library\modules\Kcsapi.js` for `var UTCtime =`

**Comment by bamboo3250** [comment]
@dragonjet can we assume that all players use JST +9? Since the time I started playing KanColle, I has changed my time zone totally so I don't know if it's possible to use a different time zone while playing or not.

**Comment by Crazyteitoku** [comment]
@bamboo3250 it is possible to play kancolle and use their local timezone. I think another idea is to allow users to manually set timezones aka forum style where it prompts you to select a timezone for the date and time display on respective threads/posts.

**Comment by bamboo3250** [comment]
@Crazyteitoku thanks for information :+1:

**Comment by dragonjet** [comment]
hm but its true enough to not worry about using server time or player time. remember that the game will catbomb if you are even 5 minutes late or advanced the real time even if you're on local timezone

**Comment by bamboo3250** [comment]
@dragonjet How aboutaccessing to the game then we change the time zone? It still can pass by that way.

**Comment by dragonjet** [comment]
it's alright if a computer is on its localtimezone. it will only catbomb if the system clock is wrong even on your local time

**Comment by nicky008** [comment]
So, the important part here is how about the accurate of your system clock. Would be a good idea if there is a warning in setting your clock correctly first before using the quest reset system.

**Comment by dragonjet** [comment]
since we have auto-quest reset, we can close this, I'll ask @JD-Kurotoshigami to re-assess the feature after v11 is released
