### ISSUE TITLE
-V11- Cannot load Sortie and Quest page

### ISSUE THREAD

**Issue by kololz** [dragonjet/KC3Kai#261]
Its kololz here again.
As the title said, the problem happens in strategy room. I've tried to go down to v.10.8 but it seems it happens too.
Version: Github v.11.0 (Re-downloaded it just a while before I posted this)
OS: WinXP
Screenshots proof:
![kc3kaistrategy3](https://cloud.githubusercontent.com/assets/12908497/8692679/2cddb9b8-2b03-11e5-9328-56a4d8f1b7a6.PNG)
Strategy room's quest page and sortie page and not working.
![kc3kaierror](https://cloud.githubusercontent.com/assets/12908497/8692685/34445e32-2b03-11e5-8b37-0e2a80fee569.PNG)
Debugged it.
But it seems the debugs is something about the problem using Japanese ver. . Used English ver., no errors, but sortie page still not shows up. However, quest is working.
Edit: Asked CT 'bout the Sortie History and he told me its not yet done in both V10 and V11.
Perhaps the problem is answered... 
Dragonjet might close this now.

**Comment by dragonjet** [comment]
:+1:
