### ISSUE TITLE
Shiplist in Japanese. Ship Types too long

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#263]
*Japanese Translation : The Kanji in the Ship List messed, the "div" is too narrow. I think it needs to be expanded (or decrease the font size). -Thanks-* - [Fujisuke](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Fujisuke-20150715101134?permalink=283262#comm-283262)

**Comment by nicky008** [comment]
Some corrupted pinyin words (I think because of the masking problem) are overlapped the normal one.

**Comment by dragonjet** [comment]
ah it should've been the font size only, the overlapping words are actually the words above them being multi-line

**Comment by kyonmiriam** [comment]
Not only Japanese Translation but also the Chinese Translation(both Simplified Chinese& Traditional　Chinese).I think this problem will appear in every hieroglyphs languages...including Korean. So why not let a single line contains more characters instead of decrease the font-size? Ah...maybe shorten the  translated texts can also solve the problem. After all, two Kanji can represent too many things...:flushed:

**Comment by dragonjet** [comment]
true, our interface issues are growing, especially with localized languages and unicode characters with varying length. coincidentally, I just started a topic about re-thinking our UI options on the other thread #312, though that one is mainly for the F12 panel. This one is for the strategy room shiplist, and the columns there, admittedly are getting narrower and cramped. With the recent addition of the morale column, and without main layout not being responsive, we're moving to a dead end.

I hope we do have shorthands for ship types in other languages though, like for Japanese, instead of the 5 kanji chars, we should use the 1 or 2 shorthands found on the in-game ship thumbnails

**Comment by nicky008** [comment]
Maximum char (kanji, pinyin, hangul etc.) for here should be 3. :ok:

**Comment by dragonjet** [comment]
ah if it's 3 then we can support that as well since english also is max 3

**Comment by c933103** [comment]
i think this should be closed?

**Comment by dragonjet** [comment]
ah yes thanks for noticing
