### ISSUE TITLE
PvP does not show the first ship of the enemy fleet

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#267]
I forgot to take a picture but someone can try that. It also does not show the formation as well. This, at least, happens in Horizontal Layout.

**Comment by dragonjet** [comment]
ah this is probably if enemy ship list also starts index 0 with -1, then starts the actual list on index 1. which they do on sortie battles

**Comment by dragonjet** [comment]
welp, might be the opposite, I did a `enemyList.splice(0,1);` for PvP opponents, which might not be needed. Will check later when I do my PvP on which index the list actually starts
