### ISSUE TITLE
[Translation] Language Options

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#268]
I found that the language options vary among different languages (most likely because some languages were added parallely or new languages came). I'm not sure if it's intended but we should keep them consistent. Otherwise, some languages cannot be seen from others while they can be seen in only English.

**Comment by dragonjet** [comment]
ah since they cannot see other forks' new entries, I try to sync up everyone's translation list like on the following commit: a744afd0c21af070d1d6ff5e1dba4e82a7d31347

**Comment by dragonjet** [comment]
I made this wiki article [Localization](https://github.com/dragonjet/KC3Kai/wiki/Localization) that may help our translators

**Comment by c933103** [comment]
this is resolved, right?

**Comment by dragonjet** [comment]
ah yes thanks for noticing
