### ISSUE TITLE
Readability Issue in Equipment List Total in v11

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#275]
Can we at least bold the "Total XX (XX Worn)" in the equip list like back in v10.8?
It's a little hard to notice the narrow texts there...

**Comment by McDohl** [comment]
how about this? 
![eqcount](https://cloud.githubusercontent.com/assets/13024936/8729858/c7dcea0a-2c17-11e5-928b-b382026ef0c0.JPG)

**Comment by dragonjet** [comment]
I think this has been fixed on #277
