### ISSUE TITLE
Support Expedition Power

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#28]
Show "Support Expedition Power" for fleets 2 to 4 instead of LoS and Air Power... or at least make it switchable between the factors.

This can be implemented on both Share Fleets on Strategy Room or on the panel interface itself.

**Comment by c933103** [comment]
do we know the formula...?

**Comment by dragonjet** [comment]
yep, at least for the [shelling expedition](http://kancolle.wikia.com/wiki/Expedition#Shelling_damage_calculation)
