### ISSUE TITLE
Counting for development off by one

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#286]
It looks like countExisting is 1 immediately upon crafting the first of an item, so the message suggests I should now have 2 Type 14 Air Radars.

![strategy room](https://cloud.githubusercontent.com/assets/1239097/8738959/90918e7a-2bea-11e5-9cd6-1fe02dabe938.png)
![craft](https://cloud.githubusercontent.com/assets/1239097/8738960/90919db6-2bea-11e5-9737-dfce4b5de8cf.png)

**Comment by McDohl** [comment]
afaik, you have XX already summed by +1. maybe better choice of words like Congratulation, You now have xx for this equipment

**Comment by dragonjet** [comment]
hm maybe we should change it to "*You now have xx of this item*"?
