### ISSUE TITLE
Completed quest still in log

### ISSUE THREAD

**Issue by EvaShark** [dragonjet/KC3Kai#300]
![screenshot 2015-07-17 23 32 26](https://cloud.githubusercontent.com/assets/13387397/8758436/235ef6a6-2cdc-11e5-829c-89a603dcb4e4.png)

I completed the "Prepare the Drum Canisters" quest a while ago but it still is listed in the KC3 quest log, this persists after getting a new API link and restarting the game.

**Comment by McDohl** [comment]
hi, thanks for the report. will check it later after clearing weekly submarines

**Comment by dragonjet** [comment]
hm this gave the idea to have a reset for each quest, but might be only be possible for the strategy room flowchart, with a button on the side of each quest entry

**Comment by bamboo3250** [comment]
Is that daily request? If not then daily quest reset will not work on it. 

Maybe he completed while didn't open KC3Kai so it couldn't capture that?

**Comment by McDohl** [comment]
it's weekly, so it will be fine if reset weekly ?

**Comment by bamboo3250** [comment]
yeah, that should be fine.

**Comment by dragonjet** [comment]
though anytime he visited the quest page with it being `status=3` (the time when the indicator is blue and rewards ready to be claimed), it should have already set it closed and inactive

**Comment by bamboo3250** [comment]
What if he claimed the reward before openning KC3Kai? The quest will still be there, right?

**Comment by dragonjet** [comment]
yep should still be there. always recommended to open panel before anything else

or he couldve done it on another device

**Comment by dragonjet** [comment]
2 weeks without confirmation for reporter, closing
