### ISSUE TITLE
Some more features for expedition

### ISSUE THREAD

**Issue by Javran** [dragonjet/KC3Kai#301]
In addition to #30, here are few things I want to add:

* Messages explaining why a fleet is not meeting a requirement, e.g. the expedition requires 4 ships while there are only 3 ships in the current fleet.
* Resource efficiency calculation, there are existing calculators like [this](http://kancollepoi.weebly.com/) and [this](http://www.kancolle-calc.net/expedition.html) but with ship database and fleet composition available, net income can be predicted precisely (taking resupply into account). (maybe also be good combining with #95), as there are limited room in devtool page, it might be better moving this feature into strategy room allowing user to experiment ship combinations without changing the actual fleets.

I have the implementation in mind, but I'm not good at web devs, might write/generate an external javascript lib and leave the question of where to place them and how to visualize open :)

**Comment by dragonjet** [comment]
great ideas :+1: looking forward to any input, don't worry we'll help integrate it seamlessly

**Comment by Javran** [comment]
I just took a look with the new source code, and what to know 2 things:

* how you print out messages? I'm messing around with horizontal.js, I can see many `console.log`s but couldn't find the output anywhere, neither in Console tab or in background's Console tab.
I usually do `alert` but I don't feel productive using that.

* just want to confirm: I can see vertical.js and horizontal.js, but is it true that for now only horizontal.js (for horizontal layout?) is used?

**Comment by dragonjet** [comment]
For example [on this line of horizontal.js](https://github.com/dragonjet/KC3Kai/blob/dd05ab8722d7698847bd0e7c615ed116dd0999ff/src/pages/devtools/themes/default/horizontal/horizontal.js#L524), this function is triggered when we craft an equipment.

We usually first get the data we need, usually from `KC3GearManager` or other related libraries, then output via jQuery, e.g.
```
$(".craftGear .equipName", container).text( PlayerItem.name() );
```
and
```
$(".craftGear .used1").text( data.resourceUsed[0] );
```

When it comes to the expedition qualification of a fleet like you've done last time, it's advised to do it under the [`Fleet` function on the same file](https://github.com/dragonjet/KC3Kai/blob/dd05ab8722d7698847bd0e7c615ed116dd0999ff/src/pages/devtools/themes/default/horizontal/horizontal.js#L219), which is triggered when you switch out ships, or a ship status has been updates / equipped. Those are exactly the conditions of when expedition qualification change so it's the perfect place.

Your expedition helper is under `\src\library\helpers\ExpeditionHelper.js` which you can still use on the mentioned `Fleet` function.

Although if you're open for it, we have a new `Fleet.js` object - a representation of a single fleet. You can find it under `\src\library\objects\Fleet.js`. It would be great if this can be utilized. You might find it easier to use also, with functions such as `KC3Fleet.prototype.countShipsWithDrums`, etc, everything happens within the object. And with the easy `this.ship(0)` and `this.ship(0).master()`, you get all ship data on that current fleet's slot, etc.

**Comment by dragonjet** [comment]
oh and about the vertical / horizontal, both are being used atm and will auto-adjust depending on your orientation. It's also both on the webstire atm

**Comment by bamboo3250** [comment]
I like the idea.

@Javran Do you mind if I make an attempt to implement some basic functions of this?

**Comment by Javran** [comment]
@bamboo3250 That will be great if you can help. Let me know which part you'd like to work on :)

**Comment by bamboo3250** [comment]
@Javran I can help you create a basic UI for the resource efficiency calculation including:
* A dropdown list to select the expedition that the user wants to test the fleet on.
* 6 slots for the fleet, which will show the ships with their fuel and ammo consumption for the selected expediture.

With that, later you can add more code to suggest more efficient composition.

**Comment by dragonjet** [comment]
hm this is becoming for of the expedition planner in #30 :laughing:

**Comment by dragonjet** [comment]
wait, ^ I did a dumb comment - what I meant was, there's a tab on strategy room for expedition planner XD we are not limited to doing this on the small box on panel >.<

**Comment by bamboo3250** [comment]
Oh there is! How come I didn't notice this before lol xD

![untitled](https://cloud.githubusercontent.com/assets/8078323/8763636/96a625a0-2dd9-11e5-9cab-f25362bb9c68.png)

I would start on this after we finish fixing the bug due to the changes in API response 2 days ago.

**Comment by dragonjet** [comment]
ah I already have the fix here but internet went crappy on me last night so I wasn't able to test. Will push this morning

**Comment by bamboo3250** [comment]
Nice :+1:  then I will wait for that :relaxed:

**Comment by Javran** [comment]
@bamboo3250  I'm actually thinking about keeping two lists:

* one for expeditions with details about resource per hour or day, net gain etc. this is to allow user sort by resources. the net gain might change when the fleet composition changes.
* one for ships with resupply cost (bullet & fuel), this doesn't require information about expedition, so the info-dependency isn't circular.

But this will be a little bit complicated than the design you suggested, for now I'll go with your UI design and later we can think of adjusting to a more powerful one.

**Comment by dragonjet** [comment]
just wanna put this on the table before I forget. we can also:

* show 6 slots on the planner page
* user selects an expedition
* one slot will have a suggested face depending on exped requirement and reso usage
* once he puts that ship on the slot in-game, we move on to next slot and suggest the next ship

since we have an "Expedition" section on the strategy room, we're not limited to one of these interfaces. we can do one tab for each xD

**Comment by bamboo3250** [comment]
@Javran How about you draw a draft of the UI? I can use it as reference.

**Comment by Javran** [comment]
@bamboo3250 I just drew one, how about this? (going to sleep, will response lately)

![1111](https://cloud.githubusercontent.com/assets/1096354/8764517/c2a29b10-2dad-11e5-83e1-d0fac64a843a.png)

**Comment by LostLogia4** [comment]
Well, there's gross income, net income, per minute, per hour, per day, etc...
And then there's daily regen below softcap.

**Comment by bamboo3250** [comment]
@Javran that's quite clean and neat. But do we need 3 fleet buttons? This is a planner so we might not need to specify which fleet we will use for expedition, right?

**Comment by Javran** [comment]
@LostLogia4 yep, you are right. Just drafting so feel free to change anything :)

@bamboo3250 the idea is to tell if a ship is used in one fleet, it will not be possible to reuse it in other fleets.

**Comment by bamboo3250** [comment]
So that means this planner is for all 3 fleets at the same time. Am I right? I'll try to create a prototype as soon as possible.

**Comment by Javran** [comment]
@bamboo3250 you are right, this is for all 3 fleets. I think it's a little more convenient as sometimes you just forgot what you have in other fleets.

**Comment by Javran** [comment]
I have been trying to refine this idea for a while,
here are some thoughts on expedition planning, feel free to comment xD

* Planning all 3 fleets together would help

    I suspect all the expedition planners I gave in OP uses a weighted "resource score", the expeditions would potentially be more efficient by letting different fleets focus on different kind of resources(e.g. letting two fleets rush for fuel while another fleet for rushing steel). I already have a prototype and will do some experiment to verify this idea. For only 3 fleets there are only `40*39*38=59280` possibilities, I think it'll be sufficiently fast even for javascript to find the best plan. But for this idea to work, there are some parameters besides priority for each resource, like a penalty for waiting for the expedition to finish (expedition time >= AFK time), and a penalty for "undesired" resouce income ratio (e.g. expecting a 4:1:1:3 priority while the current composition of expeditions is actually 0:1:2:0) -- I'm not sure if it's easy to put some scroll bars in web UI.

* Calculate plans, and let user pick whatever they desire

    For the purpose of working out plans, I'll assume the fleet consumption is already minimal, so there will not be back-and-forth loop (current fleet changed -> re-calculate -> current fleet changed -> ...). 
    Once the plan is determined (user can choose one plan, note that a plan consists of up to 3 expeditions for all 3 fleets) for all fleets, requirements not met, and the calculated minimal net resource income can be printed, then user can sort ships by their fuel / ammo max consumption, filter by ship types (any / BB / AV / carrier types / submarine types, this could be more coarse just for meeting expedition requirements), and the actual net income can be shown on fleet member change alongside the theoretical minimal net income.

**Comment by Javran** [comment]
Now I have a plan for making progress on this, and want some discussions about it:

Thinking about what can be put in the strategy room, I suggest implementing a page that only provides helps about expedition selection, ignoring ships and fleets (for now):

We can first have a list of expeditions as check boxes, this list is to allow users to exclude some expeditions (limited gain / too long). (also good for reducing search space)

Then user can somehow specify resource priorities and afk time, resulting in a table like one below.

Note that at this point the decision about which set of expedition to run is already made, and how to build and optimize fleets is another question.

We can think about how to make it more powerful after this step is done.

Just giving you an idea about what the result would look like:

```javascript
> dbg 2.0 5.0 1.0 1.0 0 0.0
[2,5,21] | 198.000 | 449.048 | 73.333 | 13.333 | 2727.905
[2,5,37] | 60.909 | 442.424 | 171.515 | 13.333 | 2518.788
[1,2,5] | 66.000 | 453.333 | 73.333 | 13.333 | 2485.333
[2,3,5] | 153.000 | 393.333 | 193.333 | 13.333 | 2479.333
[2,5,13] | 148.750 | 398.833 | 73.333 | 13.333 | 2378.333
[2,5,17] | 175.333 | 373.333 | 140.000 | 13.333 | 2370.667
[2,21,37] | 38.909 | 424.805 | 158.182 | 0.000 | 2360.026
[5,21,37] | 208.909 | 358.139 | 111.515 | 13.333 | 2333.359
[1,2,21] | 44.000 | 435.714 | 60.000 | 0.000 | 2326.571
[2,3,21] | 131.000 | 375.714 | 180.000 | 0.000 | 2320.571
[1,5,21] | 214.000 | 369.048 | 13.333 | 13.333 | 2299.905
[3,5,21] | 301.000 | 309.048 | 133.333 | 13.333 | 2293.905
[2,4,5] | 90.000 | 405.333 | 73.333 | 13.333 | 2293.333
[2,13,21] | 126.750 | 381.214 | 60.000 | 0.000 | 2219.571
[2,5,40] | 118.098 | 376.211 | 73.333 | 27.967 | 2218.553
<more results>
```

The priority of 4 resources are 2:5:1:1, with no AFK time
first 4 columns shows net income per hour, and the last column shows the score.

**Comment by dragonjet** [comment]
* I see two zeros on the input, `0` and `0.0`, which one is the AFK time and what is the other parameter?
* what's the formula for each resource score? as I can understand it, shouldn't each record be a single expedition, and not a set of 3 expeds? and he will then likely choose the top 3 of the weighted score. I'm curious about the inner workings and formulas of this xD

**Comment by Javran** [comment]
`0` is the AFK time, the other one is a way of saying "how improtant it is to keep the priority as specified" (currrently it's not working out well so I ignored it).

Basically my algorithm is attempting all possible combination of expeditions, and for each of them, a custom scorer is used to give the expedition score. (the scorer takes hourly net income of each resource, and produces a number as score)

Let me explain this two parts, the net income table and the scorer.

## Table

The table is calculated in the following way:

* First I have a net income table (expedition income + resupply consumption, optimal fleet composition assumed)

* Divided by maximum of expedition time and AFK time (hourly net income table)

* Attempt all possible expedition combinations, for each of them:

    * sum up hourly net income for each resource
    * feed it to the scorer

* Sort by the score, and take the top n of them as candidates.

The hourly net income is first put together before feeding it to the scorer, by doing this you can estimate how can fleets work together to achieve certain resource income goal, instead of sending all your fleets for one specific resource (but you can still do this by using a scorer that only consider a specific resource)

# Scorer

The most naive one is just:

```javascript
function( fuel, ammo, steel, bauxite ) {
  return fuel*fPriority + ammo*aPriority + steel*sPriority + bauxite*bPriorty;
}
```

But consider this case:

Suppose you have the following expeditions (hourly net incomes)

* Exped1: 100/100/0/0
* Exped2: 200/0/0/0
* Exped3: 0/200/0/0

If you set resource priority as 1:1:0:0, you will find all these expeditions have the same score,
while Exped1 might be the most desired one.

The mysterious `0.0` is a penalty applied to expeditions(added to the "naive" scorer above), the formula is quite ad hoc and hard to explain, but basically it's saying Exped1 has "shape" 1:1:0:0, Exped2 2:0:0:0, Exped3 0:2:0:0, the desired priority is 1:1:0:0, so Exped1 will have less penalty than Exped2 and Exped3, and therefore a higher score. But for now this parameter is hard to control, a small number has almost no impact on the result, while a big number will focusing too much on keeping the resource priority. (e.g. if there is an Exped4: 10/20/30/0 and the resource priority is 1:2:3:0, it will have the highest score if the parameter is too big, obviously not a good solution)

**Comment by Javran** [comment]
I just made a prototype [here](http://javran.github.io/tmp/expedition-plan.html).
Feel free to try out xD.

**Comment by dragonjet** [comment]
hm I was thinking one expedition per row, more in the line of:

| Expedition  | Fuel Score | Ammo Score | Steel Score | Bauxite Score | Total |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 24  | `xx.xx`  | `xx.xx` | `xx.xx` | `xx.xx` | `xx.xx` |
| 38  | `xx.xx`  | `xx.xx` | `xx.xx` | `xx.xx` | `xx.xx` |
| 9  | `xx.xx`  | `xx.xx` | `xx.xx` | `xx.xx` | `xx.xx` |
| 36  | `xx.xx`  | `xx.xx` | `xx.xx` | `xx.xx` | `xx.xx` |
| ....  | `xx.xx`  | `xx.xx` | `xx.xx` | `xx.xx` | `xx.xx` |

and that each expedition only goes through this formula
`fuel*fPriority + ammo*aPriority + steel*sPriority + bauxite*bPriorty`

because what if he only wants to do two expeditions coz he's using the other for boss support. on the current one, he won't know which of the three expeditions in top 1 entry is the best two, if I only got `[9,24,38]` result, which looks like sorted by number instead of output.

in the above table, he can easily see it, and decide to send in exped `24` and `38`

----

hm should it already consider resupply cost at this point?
we still don't know if he has all mutsukis and tenryuus
wouldn't it be better if we show him gross income first before deducting costs based on what he has?

**Comment by Javran** [comment]
For the first question, the number of available fleets is actually left as a parameter,  so user is free to consider 1 or 2 fleets instead of 3 at the same time. (he can still consider 1 fleet at a time by setting this parameter to 1)

The algorithm is actually a brute force search to cover all possible combinations, even if we can consider one fleet at a time, and work out a top-5 list, user is still facing a problem of picking 3 out of 5. So taking all fleets into account solves this problem.

Further, if we can let user click header to sort by one resource, he will be able to select a more desired plan: consider now I want to go AFK for 7 hours, and the priority is `2:6:1:1`, the first few candidates are:

13,21,40	97.00	117.86	0.00   14.29	915.43
16,21,40	95.76	110.96	13.33	27.62	898.25
21,37,40 52.00	123.29	38.57	14.29	896.57

If the user is really prioritizing ammo income, he can sort the result by ammo income, and choose the third one instread of the first one (losing few resource score is still okay because we are gaining more desired resource, this is kind of leaving the "shape problem" I mentioned before to the user, my algorithm work out best plans to try, and he can pick up one that satisfies him most)

I think it's reasonable to consider resupply, the table we get here is the optimal net income, even if it doesn't match the real net income (I even use submarines for free ship-type requirements), but at least it's more accurate than the gross income.

An extreme example would be expedition-17, the gross income per hour is 93, 93, 67, 0 but if we take into account resupply cost, it'll become 53, 27, 67, 0, actually this is not a good candidate if we want to have more ammo income. (using non-optimal fleet composition can result in even less income, but never more.)

**Comment by dragonjet** [comment]
ah I see, both aspects looks fine now to me :+1: 
the only problem I see is explaining this to the users :laughing:

**Comment by nicky008** [comment]
Now we have the resource priority selection as point scoring...

Then we have to do the net resource and expedition consuming (choosing ships for doing the expedition -> resupply) next. :dizzy_face:

**Comment by dragonjet** [comment]
@Javran I am getting a `KEP.calcWithExpeditionIdsFleetCountJS is not a function` I think the latest one is not yet merged here?

**Comment by Javran** [comment]
@dragonjet ah yes, the lastest version is not merged, you can it at http://javran.github.io/assets/KanColleHelpers.js I've done some refactoring but all the APIs should be intact.
sorry that I'm working on E5 so don't have time to verify it yet.
