### ISSUE TITLE
Remaining fuel and ammo not updated in resupply menu

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#303]
I've noticed that the remaining fuel isn't updated until the main page is accessed again.

**Comment by dragonjet** [comment]
oh must've been another API change :( let me check

**Comment by dragonjet** [comment]
check on my side and it's updating, which map are you on?

![ss 2015-07-18 at 09 33 41](https://cloud.githubusercontent.com/assets/557312/8759786/270779a0-2d30-11e5-9f60-37be6cbe4cf6.jpg)

**Comment by LostLogia4** [comment]
It's in the resupply menu, not in combat.

**Comment by dragonjet** [comment]
oh you that one, though how are you able to see the gauges without battle mode?

**Comment by LostLogia4** [comment]
It's already implemented in normal mode from version 10 onwards, if you didn't know already.

**Comment by dragonjet** [comment]
oh are you using vertical?

**Comment by LostLogia4** [comment]
vertical 420px.

**Comment by dragonjet** [comment]
ah I see, @bamboo3250 might wanna look at this

**Comment by bamboo3250** [comment]
okay, i'll take a look :ok_hand:

**Comment by LostLogia4** [comment]
derp, accidentally closed this issue.
iirc this one can be implemented just fine with current API calls.
