### ISSUE TITLE
[Translation: ID] quests

### ISSUE THREAD

**Issue by vrarara** [dragonjet/KC3Kai#313]
hey, i want submit my translation quest for indonesian version,
must i edit n upload developers.json file here too? to include my personal link?

**Comment by dragonjet** [comment]
hi, do you currently have a fork, or is this manual?

We do have translators working on Indonesian version, but it seems they haven't submitted the quests.json yet. I'd like to tag them here and get their response, so we can all be up-to speed on how to move forward.

@hufuhufu @freezebear

You can upload the file here if you want, so they may check on it later. Once approved, we will merge/push your work on the master branch. I will add you to `developers.json` myself after this, just post up to 5 desired links for the about page.

**Comment by vrarara** [comment]
i do this manualy

just add my facebook link
https://www.facebook.com/bayuuyab.fu

**Comment by vrarara** [comment]
n where should i upload quests.json
sorry im new in github

**Comment by dragonjet** [comment]
probably pastebin, or puush

**Comment by vrarara** [comment]
allright here's the file link
http://pastebin.com/JaYHv1Ck

**Comment by dragonjet** [comment]
ah thanks for this. I looked also at both of their forks and seems they don't have any `quests.json` on any of their branches. I will push this to master in a while.

Also if you're interested, we added around five new quests just earlier, highlighted here:

https://github.com/dragonjet/KC3Kai/commit/19921a000f36e6e2ae80aeab009ae5f754260ab7

**Comment by vrarara** [comment]
okay i'll learn how to forks and add that quest too

**Comment by McDohl** [comment]
@vrarara i think the translation need better proofreader. I'm indonesian myself and the translation are bad from my point.

**Comment by vrarara** [comment]
@McDohl i will fix it, if u want can u give FB link for more chat :)

**Comment by dragonjet** [comment]
oh good thin i havent pushed this, you guys can discuss it and upload via @McDohl's fork

**Comment by hufuhufu** [comment]
I'm actually just started translating quests.json.
@vrarara I've sent friend request so we could discuss this.

**Comment by vrarara** [comment]
okay
