### ISSUE TITLE
Resource History Broken

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#319]
As reported on Facebook PM

![11749440_1015681955116666_195464424_n](https://cloud.githubusercontent.com/assets/557312/8763846/dbc49d4c-2de3-11e5-8902-c0535173476c.jpg)

**Comment by Crazyteitoku** [comment]
@dragonjet I had this issue sometime before the maintenance that ended on Friday after like getting the quest trackers to work. Not that quest tracking broke anything but pretty sure by then the screenshot I had at the time was broken for two of the three graphs. It looks like the third graph is working ok.

Presumably clearing the resource counts from within dev. console inside strategy page would make it work - at the expense of losing any previous resource history.

**Comment by dragonjet** [comment]
I told him to reinstall and he did, and knowing it clears all your logs, it happened that it wasn't fixed

**Comment by Crazyteitoku** [comment]
Interesting. :open_mouth:
