### ISSUE TITLE
Use battle results in quest tracking

### ISSUE THREAD

**Issue by Javran** [dragonjet/KC3Kai#325]
I assume you are using enemy fleet composition prediction for quest tracking, and I haven't looked at the source code so might be wrong.

I notice after the enemy composition being removed from server response, quests related to sinking ships no longer get tracked, I know it is possible to "replay" the battle by learning `/kcsapi/api_req_sortie/battle`, is it also possible to use it for tracking quest progress?

**Comment by dragonjet** [comment]
ah we haven't implemented the tracking for "hunt" quests yet, only "defeat-boss" quests. The requirement to be able to track sink enemy quests would be battle prediction for us to know which enemies sunk during the battle - which is not sent in by the server by default so we'll need to do damage calculation ourselves

**Comment by Javran** [comment]
Do you have plan of implementing damage calculation? If not yet maybe I can give it a try in my lib.

**Comment by dragonjet** [comment]
Ah that would be perfect, currently the feature is not in my line of sight :laughing:
