### ISSUE TITLE
[Translation: FR] battle, settings, rank, terms

### ISSUE THREAD

**Issue by Arkayda963** [dragonjet/KC3Kai#338]
[Translation: EN to FR] KC3Kai

http://pastebin.com/3HCdXz8u

**Comment by dragonjet** [comment]
hi @Arkayda963 I forgot to put in the guide, but if you're doing non-git translation and if you do have some translation files, you can upload it to pastebin, puush or any preferred text transmission tool and put it here

**Comment by Arkayda963** [comment]
There some translation i done 

http://pastebin.com/3HCdXz8u

**Comment by dragonjet** [comment]
says *This is a private paste. If you created this paste, please login to view it.* it's probably better as unlisted

**Comment by Arkayda963** [comment]
Ok Edited you can go in now i guess

**Comment by dragonjet** [comment]
ah thanks, I'll also tag you in one of the github threads in a bit

**Comment by Arkayda963** [comment]
ho i forgot to say something this translation are on French
