### ISSUE TITLE
An extra comma in weekly sortie 1?

### ISSUE THREAD

**Issue by Javran** [dragonjet/KC3Kai#342]
![2015-07-20_061742_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/8774000/1a520cac-2ea7-11e5-85d7-55b32b99ae5f.png)

I spot this while doing daily sortie, an extra comma after `Weekly Sortie 1`

**Comment by LostLogia4** [comment]
Because this one has multiple conditions to fulfill, about 4 of them in fact.

**Comment by nicky008** [comment]
I felt this would let be more composition (re)works go'n again in the next ver.

**Comment by dragonjet** [comment]
tbh im not sure how to go about this. probably uhm, scrolling each requirement every 3~5 secs?

**Comment by Javran** [comment]
what about just show it as `14/36 ...`, when it counts to `36/36`, hide it and reveal next counter not met, say `9/24 ...`?

**Comment by nicky008** [comment]
@Javran or like in the game's calculating method...

* when 36 sorties counted (`36/36`), hide and next
* then 12 boses slaughtered ('12/12'), hide and next
* finally when 24 times went to bose node ('24/24') counted and finished...

right?

**Comment by Javran** [comment]
@nicky008 yep, this is exactly what I meant :)

**Comment by LostLogia4** [comment]
While we're at it, is it possible to add tooltips on the quests in Battle Mode at least?
