### ISSUE TITLE
Weekly Sortie 1 Stops Counting at 35/36

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#343]
Exactly what it says on the tin. The rest of the counters still increases to their max value as intended iirc.

**Comment by bamboo3250** [comment]
After that did you complete the quest when doing the sortie one more time?

**Comment by LostLogia4** [comment]
No... Haven't completed it yet since I still need 8 boss kills, but I've already gotten well over 36 kills and it stays in 35/36.

**Comment by bamboo3250** [comment]
Do you know how to get the response from server? I would like to see the response when you open the quest list. Otherwise, I'll try to do 36 sorties tonight to find out the truth xD

**Comment by LostLogia4** [comment]
On second thought, I got 36/36 now.

**Comment by bamboo3250** [comment]
Ah, did you count the number of sorties by the battle or by the time you started?

**Comment by LostLogia4** [comment]
By the time I started? Btw it does increment when I do Map 1-1, but it doesn't on Map 2-3 iimn.

**Comment by bamboo3250** [comment]
I mean the first number only increases when you start the sortie from the first node. And the hunting quests haven't been implemented yet though xD

**Comment by LostLogia4** [comment]
Space bananas... I thought it was like the daily sortie 1...

**Comment by dragonjet** [comment]
*the first number only increases when you start the sortie from the first node* eh? xD can you start the sortie then start on other nodes? :laughing:

**Comment by LostLogia4** [comment]
Another one: just finished weekly sortie 10 now. it was stuck at 1/3 until I checked the quest again.

@dragonjet There are more than one "first nodes" in certain maps...

**Comment by bamboo3250** [comment]
@LostLogia4 so you mean when you killed the boss 1-5, the number didn't increase at all?

**Comment by LostLogia4** [comment]
Well, it only increased once. It didn't increase at all on subsequent runs.

**Comment by dragonjet** [comment]
hm. there must be something wrong with out boss detection. I'm using the `bosscell_no` but I haven't tested it in an actual sortie. The variable just seemed perfect for it. Though I'm thinking we really can't rely on that variable since as mentioned before, nodes have different IDs depending on route taken - thus the boss node might have different ID than the one indicated on `bosscell_no`

**Comment by bamboo3250** [comment]
That makes sense. In 1-5, there are two ways to reach boss node. So there should be 2 different IDs for the boss node for each route. We have concluded that the ID is the ID of the route/edge instead of the node in #69

**Comment by dragonjet** [comment]
will check for other variables like `api_event_type` later when I go sortie, I'm sure there's an indicator for a boss node

**Comment by bamboo3250** [comment]
Oh that's right. We should rely on `api_event_id` and `api_event_type`. I remember the boss node has different value from other battle nodes.

**Comment by LostLogia4** [comment]
Which would explains why the counter increments on 1-1 but not in 2-3, since the latter doesn't always start with route 1.
