### ISSUE TITLE
Akashi Timer

### ISSUE THREAD

**Issue by EchoHolic** [dragonjet/KC3Kai#35]
I want to know how long does it take for a repair tick when I set Akashi as a flagship, since I always mess up by a minute or two. Having a timer in-built would be helpful.

**Comment by ReiFan49** [comment]
recalling this as added on natsuiro
but, there's one existing bug that annoys me.

![image](https://cloud.githubusercontent.com/assets/9847780/9378303/8f0b57ae-474a-11e5-90c2-47e2a948482b.png)
moderately damaged ship, or the worse condition one... should be excluded from this calculation.
