### ISSUE TITLE
Battle Mode "Next Node" not working properly

### ISSUE THREAD

**Issue by daaurpoj** [dragonjet/KC3Kai#354]
Hello, ever since the update, I've had the issue that in every battle I go into, it no longer displays the "Next Node" tab info correctly, where it would display the detection and air superiority. Instead, it simply says "Battle avoided!" in every situation unless I go to a resource node. Does anyone else have this issue?

**Comment by bamboo3250** [comment]
Yes, this issue has been fixed in the last Github version. For the reason and further information, you can read this thread #295 

Thank for your report.
