### ISSUE TITLE
Translation Mechanism Change

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#355]
#### To everyone:
As of f693393bcb912a0223293df76818d667f0683705

I'll be pushing a change in our translation mechanism. This is derived from @Diablohu's enhancements which use **synchronous ajax** to load json files. I moved the json loader function from `Meta.js` to `Translation.js`.

Additionally,  `Meta.js` receives data directly not via callback but by return value since its synchronous anyway. e.g.:
```
this._ship = KC3Translation.getJSON(repo, 'ships');
```

Also, it does not extend the English counterparts, for reasons stated on a section below

#### To translators:

The main difference for translators is that `developers.json` and `settings.json` no longer need to be inside your localized folder.

These two files are now common files for all languages and moved to `\src\data\`, **not under `\src\data\translations\xx\`**. To be able to provide translations to itss labels, all of those words were moved to `terms.json`.

Sorry for the inconvenience but those who already have existing translations for `developers.json` and `settings.json`, I ask that you copy paste the words into your `terms.json`. You may check `en` folder's `terms.json` to copy the variable names such as `SettingsCraftBox`, etc.

e.g. ca2b2113243ab45afd7f430b84a589f06a340fca
```
"SettingsGameInfo" : "Game Information",
"SettingsConstructionFaces" : "Construction Faces",
"SettingsCraftBox" : "Crafting Results",
"SettingsCompass" : "Compass and Enemy",
"SettingsBattleData" : "Battle Environment",
"SettingsBossComp" : "Boss Composition",
```

#### Reasons and Advantages
* **About merging all developers and settings**: Now you do not need to subscribe to changes in `developers.json` and `settings.json`. You mostly just need to monitor `terms.json` from now on, which is an evolving file anyways and will get more words in the near future either way, esp when we apply TL to strategy room.
* **About not extending English data**: It is intended that if a file or word is missing from a language, it will show up as a variable such as `MenuSettingsDesc`, and not its English counterpart. This is to let users know that the translation is either new or not yet done, and not conceiving it as a bug that we missed the word somewhere.
* **Other notes**: `Theme` names are really not translated. They are names. So "Dark Theme" is called "Dark Theme" on the choices in all languages. A "V-Ten" theme is also "V-Ten" in all languages.

#### Tag
@nicky008 @kololz @Diablohu @freezebear @hufuhufu @vrarara @Arkayda963 @RanFoxRun @bamboo3250

I have already started a sample for `jp`, hope @nicky008 can continue copying, and there are also new words like "*Coders*", "*None*", etc

Sorry for the inconvenience.

**Comment by nicky008** [comment]
:ok_hand: I will follow that...

**Comment by bamboo3250** [comment]
@dragonjet I got this error message when trying to load the game. This is from the latest commit.

![screen shot 2015-07-23 at 1 41 07 am](https://cloud.githubusercontent.com/assets/8078323/8832533/3615be16-30dc-11e5-92e3-1f63cb2ebd35.png)

**Comment by nicky008** [comment]
Have no problem in The Travis check but have this in the console instead :trollface: 

OK, waiting for @dragonjet to redo this (or these?) ref error.

**Comment by dragonjet** [comment]
ah yes topkek pushed

**Comment by bamboo3250** [comment]
@dragonjet the issue still persists. How about doing that for `api.html`?

**Comment by dragonjet** [comment]
pushed :v I tested f12 on strategy room and didnt notice the api screen bugged too

**Comment by bamboo3250** [comment]
:+1:

**Comment by McDohl** [comment]
@dragonjet you forgot to say new mechanism for ships.js lol other translation (except JP) will suffer Ship name + undefined like below :
![github](https://cloud.githubusercontent.com/assets/13024936/8844926/876b5af6-3144-11e5-9715-eb7011263678.jpg)

that aside, i already made new pull request to fix that parts https://github.com/dragonjet/KC3Kai/pull/363

**Comment by nicky008** [comment]
@McDohl So fast... :dash: If I didn't feel so tired and sleepy ('cause very late night working yesterday), I'd also had been going to fix these too.

**Comment by McDohl** [comment]
@nicky008 well, ytd i'm so tired and sleep early so end up not playing kc (yes expedition not sent). And today i got that report from @freezebear 

that aside, while testing that, i noticed japan quest translation is not unreadable on my end (maybe need further check)
![mcdohl 2015-07-23 15-21-27 56](https://cloud.githubusercontent.com/assets/13024936/8846089/96c5cec8-314e-11e5-86ec-9ffc091f32a7.jpg)

**Comment by dragonjet** [comment]
wait I didn't know about this Kai Ni thing. It's not from my update :open_mouth: 

@McDohl must be the font, can try change font-size a few px via inspector?

**Comment by nicky008** [comment]
@McDohl Font problem... I'd try reducing the font size and it's work.

In my translation, I'd add more notes on some quests for helping and guiding too (used the references from Japaneses Kancolle wiki). It might be so long described for some quests.

**Comment by bamboo3250** [comment]
@dragonjet please correct me if I'm wrong. I find that since we use `KC3Translation.getJSON` to get the translated file and convert it to objects, we should not remove any non-text attributes, right? It's totally different from @Diablohu so we cannot extend from English anymore. I notice there is an issue that if we remove `tracking` from the `quests.json`, it will not show the tracking counter anymore. 

For now, Simplified Chinese and Vietnamese have these fields removed. We should recover them soon.

**Comment by Diablohu** [comment]
Be busy recently, sorry for the late... XD

I personally object to not extending English translation. The reason I introduce extending is to making all strings readable, even there's no translation in specified language.

You said user seeing an English string in other language may consider it is a bug. But in my opinion, seeing MenuSettingsDesc other than "Description for Settings" is more odd to a user, and user may think the program is broken rather than a bug.

And, we have no way to ensure all language translation files keeping up to date.

**Comment by dragonjet** [comment]
@bamboo3250 @Diablohu thinking about it once more, I now understand the significance of extending English. At first I was looking at `en` and other languages as equals, and `en` is just another language. However, we do need an alternative source other than game data that will provide us romanized counterparts.

Going by the aspect to make it easier for translators, extending English does have its perks. Like specify files you only want overridden. That if they still want BB / CV, they don't need to put `stype.json` on their files. Same with `ships.json` if they want romanized ship names.

For now I will modify `Translation.js::getJSON()`, and add an optional parameter, `extendEnglish`, which can be specified `true` or `false` if we want to extend english for that specific file. Right now I added all except `terms.json` for reasons below:

About it being `MenuSettingsDesc` instead of English counterpart, one other reason is to attract more possible translators. For example, a Russian language maintainer became inactive, so these variables start to show up on frontend, then someone who tries to use Russian, then sees these variables will think, "*ah its not updated, these guys need some help*", and might offer us assistance. In contrary to them being frustrated that "*I chose Russian and you show me English!*"

@McDohl @nicky008 seems the Japanese font have some sizing problems, what if we globally decrease `font-size` by a few pixels only for Japanese? Still not sure how to do it but is that a viable solution attempt?

**Comment by nicky008** [comment]
@dragonjet I think, for now, just decreasing `font-size` is still enough for mine.

**Comment by Arkayda963** [comment]
i follow that ! that's can be easier works in the future ^^

**Comment by dragonjet** [comment]
ah yes probably we put if japanese, dont show overlay

**Comment by Diablohu** [comment]
enhancement for the new KC3Translation.getJSON() ([PULL REQUEST](https://github.com/dragonjet/KC3Kai/pull/409))

the extend method is not perfect since it use non-recursive extending. this will fix that

when this commit merged into upstream, non-text content can be safely removed from all translation files except `terms.json`

**Comment by dragonjet** [comment]
:+1:
