### ISSUE TITLE
Repair Timers on HP bars

### ISSUE THREAD

**Issue by EchoHolic** [dragonjet/KC3Kai#36]
![image](https://cloud.githubusercontent.com/assets/8327865/7453534/da25a85a-f29c-11e4-809e-51d647c74894.png)

Some KCVs have a feature where repair timers are shown on HP bars that aren't at full health.

If Akashi is able to repair faster than the dock, it will include her timer as well.

Having this in KC3 as well would be helpful in gauging repair times without going into the dock and checking.

**Comment by Javran** [comment]
Is someone currently working on this? If not I can do it in my lib. But I don't know how to calculate Akashi's repair time though.

**Comment by bamboo3250** [comment]
@Javran Akashi's repair time is `number of HP to recover x 20min`. This is only applied for ships with minor damage or less than that. The type of ship doesn't matter.

**Comment by dragonjet** [comment]
ah I don't think anyone is working on it atm, feel free to xD
I'll integrate it to natsuiro when done

**Comment by Javran** [comment]
@dragonjet ok I'll be woring on that xD

@bamboo3250 From what I've learned so far, we have a formula for docking time [here](http://wikiwiki.jp/kancolle/?%C6%FE%B5%F4#i43fa2e3). I've tried few examples and it seems to be quite accurate.

Just investigated about Akashi's repair time, I think we just calculate `lostHp * 20 min` and `ceil(docking time / 20) * 20` and take the smaller one.

**Comment by Javran** [comment]
Just created a PR #657 

There are things yet to verify:

* Cases where Akashi's repair time is less than the docking time (for now I don't have a high level ship to verify this)
* I'm not sure what are thees 3 ship types: `DDE`, `XBB`, `AP`, the calculation requires a factor which is related to ship types, if there are examples for these 3 types, I might be able to guess their factors.
* Have you guys got Hayasui? What's she's ship type? I suspect she's the first `AP` ship.

**Comment by ethrundr** [comment]
@Javran here's that Kirito... err, I mean, Hayasui:
![screen shot 2015-08-18 at 03 25 45](https://cloud.githubusercontent.com/assets/13522800/9312645/e153c102-4558-11e5-965e-f513ae90916f.png)

Historically, she is belong to `AO` class, don't know whether KC follows it faithfully or categorized her as `AP` instead.

Also, how to trigger these timers? Since I've tried everything I can think on the panel and still can't see it appearing.....

**Comment by dragonjet** [comment]
according to game data she's `stype=22` which is 補給艦

**Comment by Javran** [comment]
@ethrundr what I wrote is just a backend lib that can calculate docking time. for now I think this functionality is not yet implemented in UI.

btw next time when your Hayasui needs a repair can you provide the following information?
This is for determining a ship-type related factor used in docking time calculation.

* she's ship type from Ship List of the Strategy Room
* current hp, full hp, level and repair time

**Comment by Javran** [comment]
@ethrundr never mind, just got some data from my friends, seems Hayasui's repair time is the same as destroyers. (i.e. same level, same HP lost => same docking time).

**Comment by ethrundr** [comment]
@Javran good for you, since I haven't use my Hayasui yet, and probably never until the event ends

**Comment by dragonjet** [comment]
@Javran 

Akashi has 30 seconds docking time while HP is full

![ss 2015-08-19 at 11 30 17](https://cloud.githubusercontent.com/assets/557312/9348189/b4a46fea-4665-11e5-9a13-0c9edead4ec6.png)

**Comment by Javran** [comment]
@dragonjet lol I see, each repair has a base docking time (which is 30 sec), I didn't expect the case when curHp = maxHp, will fix it anyway (also found a bug when ship level is less than 11),
will send a PR soon.

**Comment by dragonjet** [comment]
:+1:

**Comment by ethrundr** [comment]
so, just to make sure... it's:
[ Type, Level, CurHP, MaxHP ]
Timer

Am I got this right, @Javran ?

**Comment by Javran** [comment]
@ethrundr yes :)
