### ISSUE TITLE
[Bug report] Resource graph keeps breaking.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#367]
**Date Seen**:
~18-07-2015

**Version (for reference only, it even affects webstore builds)**:

* **KC3 Kai version**: v12.0 (github build)
* **KC3 Kai github revision**: 7801d898db193a84bcc532089ba5133b3fabcf53
* **Browser**: Chromium 64bit (currently on:44.0.2403.89 (Developer Build a7caae2d2d1297d162779ecd4da09df83831842d Linux))
* **OS**: Archlinux 64bit (currently on: Linux: 4.1.2-2-ARCH)

**Bug Description**:
Resources graph keeps breaking for unknown reason. Happens randomly and affects virtually all v10 versions of KC3 Kai as well as developer builds.

Please refer to the following screenshot for more information.

**Severity**:
Major

**Steps to Reproduce**:
**Currently what triggers this bug remains unknown as no errors has been shown**
1. Go to strategy room.
2. Go into Resources.
3. Resources should be graphed nicely but instead it is broken, and at random moments.

**Actual Behavior**:
Graph is broken and needs resetting.

**Expected Behavior**:
The graph should be working normally and not show all 0.

**Troubleshooting/Testing Steps Attempted**:
* Resetting the graph seems to work temporarily as described [here](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Tsusai-20150719121630/@comment-Crazy_teitoku-20150720072815?permalink=286360#comm-286360). However this needs to manually intervened which inherently loses any historical information on the resources.
* Tried sticking to one git revision of KC3 Kai (which fails).
* Tried stable builds. See [here](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Tsusai-20150719121630?permalink=285766#comm-285766), [here](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Samrael-20150721051923?permalink=287222#comm-287222), and [here](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Samrael-20150721051923/@comment-Novevolpi-20150722105925?permalink=287803#comm-287803)

**Workaround**:
Resetting the graph seems to work temporarily as described [here](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Tsusai-20150719121630/@comment-Crazy_teitoku-20150720072815?permalink=286360#comm-286360). However this needs to manually intervened which inherently loses any historical information on the resources.

**Attachments**:
![kc3-kai-resources-bug](https://cloud.githubusercontent.com/assets/12234182/8850461/a0f02c80-318b-11e5-9a77-5fcac5f4909f.png)

**Comment by bamboo3250** [comment]
It still works for me recently.

![screen shot 2015-07-23 at 9 17 59 pm](https://cloud.githubusercontent.com/assets/8078323/8851294/24f0f268-3181-11e5-8d96-2dff54eef25f.png)

Does it have sth to do with google-analytics? @dragonjet

**Comment by McDohl** [comment]
happened thrice to me already :disappointed:

**Comment by bamboo3250** [comment]
I searched in stackoverflow and found that most of the cases are because it's blocked by other plugins such as Adblock Plus. Is this you guys' case?

**Comment by dragonjet** [comment]
is it possible for it to go back to working condition after this happens? or is it stuck like that once it starts?

**Comment by Crazyteitoku** [comment]
Oh crap I forgot that there was already a duplicate bug report on this. :blush: https://github.com/dragonjet/KC3Kai/issues/319

@bamboo3250 I can't see how adblocker would block the graphs and what not. If such is the case than the dev. console should have reported certain elements to be blocking. The screenshot I provided shows that it blocks google analytics references but that is not necessarily by adblocker itself.

Resetting the resources via dev. console as mentioned [here](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Tsusai-20150719121630/@comment-Crazy_teitoku-20150720072815?permalink=286360#comm-286360) helps but only temporarily before the graph is broken again. The timeframe in which "temporarily" is defined is in matter of a few days but is not consistent.

For reference I do use a combination of adblocker and script blockers myself. One is [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) and the other is [ScriptSafe](https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf?hl=en). Neither of which have had issues to my knowledge that would break the graph until KC3 Kai circa v10.8 above happened as I have been using those aforementioned two other plugins for a good while now. :laughing: 

@dragonjet it doesn't go back after this broken graph first appears. I have had it running for a few days now without clearing the resources graph via dev. console.

I noticed there was another interesting way that may help clarify the issue. Since 7801d898db193a84bcc532089ba5133b3fabcf53 there was an option for one to both export and import game profile into a CSV type file except it does include lots of personal information in there. If it helps I could probably attach that CSV file (except personal information :stuck_out_tongue_winking_eye:) and see if you guys could see that maybe (and just maybe) if perhaps the issue might be related due to some erroneous data inside the localDB that is causing the graphs to break?

**Comment by dragonjet** [comment]
wait, I pushed 4a7ddc045a62df1c263d46394fa115c6f039ef75 which supposedly fixes this. mainly because of wrong index assignment on resource, I started with `1` :laughing: 

However, please do not pull first :open_mouth:  We need to find out if `api_get_member/material` is the real cause of this by reproducing the bug. We just do an action that calls this specific API and see if it bugs right there. If it is, then we can confirm the fix from  4a7ddc045a62df1c263d46394fa115c6f039ef75

**Comment by Crazyteitoku** [comment]
@dragonjet looking forward to this! :+1: Better yet if it helps is to somehow add debug symbols (strings even) which may help in pinpointing the issue.

**Comment by dragonjet** [comment]
I confirmed it in my tests just now that `api_get_member/material` really is the cause of the graph bug. One action where it is being called is when you construct a ship. And when I did construct a ship the graph started to bug. Did this on WebStore version the fix is not yet there.

If you pull the latest the fix should be there already and you'll just need to clear the Idb once again to remove the buggy record. Won't happen again if you start filling data once more.

**Comment by Crazyteitoku** [comment]
@dragonjet ah looks like those affected users of webstore version may get a hotfix it appears.

So I can do git pull? Also by Idb is just for that resources part or do I need to do it for all the other fields? :laughing: I have lost all my historical data anyway since trying to trace down the problem but no matter - it is all for the greater good.

If I can't do git pull at least I sort of have figured out how to use a certain version of kc3 kai git rev. and still do git pull from base (origin) to latest (master) to keep it up to date. :stuck_out_tongue_closed_eyes:

**Comment by dragonjet** [comment]
you can pull now :laughing:
