### ISSUE TITLE
drop report info

### ISSUE THREAD

**Issue by c933103** [dragonjet/KC3Kai#369]
is it possible to denote user's selection of event difficulty when entering event map so that drops can be noted with that difficulty?

**Comment by dragonjet** [comment]
hm tbh I failed to record event-specific API calls, but I'm sure there's a way to determine that. Just that we can only implement it after inspecting the calls when the event starts

**Comment by dragonjet** [comment]
Untested but supposedly supported as of 0a2afc4227c53366b2bb62ca003be85a5ec5b651 and 4b5e8b583950a8c89b69932d281e999596dce225

Keeping this open until verified working.

It's saved on local database entries but not shown on the sortie history interface yet.

**Comment by dragonjet** [comment]
We can now close this as part of #677
