### ISSUE TITLE
[Bug report] Uncaught TypeError: Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#37]
Date Seen:
01-05-2015

Versions:
* KC3 Kai v004 (git build)
* Chromium 64bit (currently on: 42.0.2311.135 (Developer Build 575981d43c6dc74b1443ca77e015c218daf050dd Linux))
* Archlinux 64bit (currently on: Linux: 4.0.1-1-ARCH)

Bug Description:
Error found approximately during the loading of the main page after user clicks "Game start!". Issue is not replicable as the current build of KC3 Kai (v005 now) and newer version of Chromium build. Also because there was no way to clear the amount of accumulated errors it is uncertain as to whether or not has the bug resurfaced or has it been fixed.

Screenshots are provided below where possible as this issue has not been seen again. Also details regarding to stack trace could not be sourced.

Severity:
Unknown - possibly minor.

Steps to Reproduce:
1. KC3 Kai button left click and click on Play via DMM Frame.
2. Click on start the game anyway.
3. Whilst loading Ctrl + Alt + J key was used (as F12 was reserved for another program).
4. Under developer tools click on KC3 Kai tab.
5. Game displays "Start game!" wording.
6. Enter into user's personal page and click on fleet (inside game - not KC3 Kai).
7. Go into Settings under Chromium.
8. Click on Extensions.
9. Error appears as titled in red words.

Actual Behavior:
Unknown. I do not know what is actually happened other than seeing the error.

Expected Behavior:
Unknown - possibly error to not show up.

Troubleshooting/Testing Steps Attempted:
- Tried to play the game normally which appears to have impacted nothing. Other than that no new error messages have since been re-appearing.
- Updated to the latest version of KC3 Kai via 'git pull' and the errors are no longer visible.

Workaround:
None.

Attachments:
![kc3kai-004-bug0](https://cloud.githubusercontent.com/assets/12234182/7453907/0e2a24da-f2a9-11e4-834b-7a3699af2b9c.png)
![kc3kai-004-bug1](https://cloud.githubusercontent.com/assets/12234182/7453911/17f69156-f2a9-11e4-80f6-c1a9cea7c654.png)

**Comment by dragonjet** [comment]
ah this could be because the F12 was loaded late. the correct step should be Ctrl + Shift + J and not click on "Start Game anyway". There is a specific API call during game start that loads all your equipment, if the F12 panel was late to be opened and did not get the equipment list, it will generate error when computing for eLoS

**Comment by Crazyteitoku** [comment]
Thanks for the response! I am starting the KC3 Kai before I click on Game start and it appears to not show up any more errors.
