### ISSUE TITLE
Admiral EXP Gained/HQ Status Update During Sortie

### ISSUE THREAD

**Issue by ReiFan49** [dragonjet/KC3Kai#374]
![image](https://cloud.githubusercontent.com/assets/9847780/8870425/3ace00a2-3218-11e5-8346-ce977ca7d01f.png)
> well, if i remember, last year...
> while sortieing through 1-5 on HQ39.. it suddenly bombs out the experience gauge...
> but during the transition sortie(which is, HQ exp almost level up)--- 
> 
> Node A: HQ39
> Node B: HQ39
> Node C: HQ40
> Node I: HQ40
> 
> something like that...

umm.. maybe i should get back to the point, 
is it okay to have something like current ship/equipment count(which counts drop) and/or HQ exp gained updated during sortie? (commits applied at my branch first)

**Comment by dragonjet** [comment]
sure, though does it not update exp/shipcounts right now during sortie? I haven't actually tried myself or have forgotten it already

**Comment by bamboo3250** [comment]
I confirm that it does not. I can fix it for you if you don't mind xD

**Comment by dragonjet** [comment]
sure xD

**Comment by ReiFan49** [comment]
not yet, still testing it whenever near 100% thingy

(besides that, bar padding is important, or something like this will happen lol)
![image](https://cloud.githubusercontent.com/assets/9847780/8873076/33326850-322d-11e5-8365-c6a5a378ebb1.png)

**Comment by bamboo3250** [comment]
About updating ship/equipment count, we probably will need another json file to store the starter equipments of new ships because the API only includes the ship ID. Is it okay if I add another file for that?

**Comment by dragonjet** [comment]
ohh so that's why, we don't have gear for drops so equipment slots dont get updated. sure you can add a new file but my concern is that we have another file to maintain :v and we don't publish to webstore often so problem may arise when users get new ships. though new ships usually dont drop on sorties, except in the recent events like Roma, and iirc Haya/Kiyoshimo

**Comment by bamboo3250** [comment]
Yes, maintaining is also my main concern but we should consider the benefit it brings together with the hardship we get whenever a new ship is introduced. As you said, new ships are not usually introduced outside of events so it should be around 3 months for each maintainance.If that brings a better experience for the user then I will do it. Please take note that it will take a little time for me to build the file from scratch xD

**Comment by ReiFan49** [comment]
well, for now i'll put the placeholder ship counter update (which increments every drop, and might overflows if possible) bb48cec8b792346d910f6d7221ed164eb6413311
(and i thought Master already holds those thing... so basically no data added to the ShipManager for now...)

if this issue still need open then i'll refer it instead closing it until the actual ship and gear addition to the current player database.

**Comment by dragonjet** [comment]
@bamboo3250 I still have master files from when the data included equipment. I can try to rebuild an object for it, then we'll just need to supply whats missing. iirc it was removed october 2014

@ReiFan49 looks good :+1:

**Comment by bamboo3250** [comment]
@dragonjet thanks, so convenient :grin:

I'll wait for @ReiFan49 's commit to be merged then :+1:

**Comment by dragonjet** [comment]
@bamboo3250 we just need the equipment count per ship right? so something like below can suffice?

```
{
"s1": 2,
"s2": 2,
"s3": 3,
"s4": 2
}
```

**Comment by bamboo3250** [comment]
not really. What we need is the number of equipments that a new ship has to add it to the total number of gears in HQ.

**Comment by dragonjet** [comment]
yea i mean the structure XD

`"s<ship_id>" : <defeq_count>`

**Comment by bamboo3250** [comment]
oh yes, that's what I need :sparkles:

**Comment by bamboo3250** [comment]
btw, it was removed nearly one year ago. How come do you still have that xD

**Comment by dragonjet** [comment]
i keep a copy of all master files since I started decoding back April 2014 :laughing:

**Comment by dragonjet** [comment]
pushed to`src\data\defeq.json` as of 9225efe5bf6a48b6ab09174913994e1588814e8e

**Comment by bamboo3250** [comment]
thanks, I'll handle the rest :+1:
