### ISSUE TITLE
Suggestion for Showcase: last attr-slot for ship change to luck

### ISSUE THREAD

**Issue by Diablohu** [dragonjet/KC3Kai#376]

**Comment by LostLogia4** [comment]
Did you mean change to current luck?
Anyway, luck is very hard to modernize. Unless if Maruyu drops like rain at 1-1 or something.

**Comment by dragonjet** [comment]
hm I'm still not sure what's going on xD

**Comment by LostLogia4** [comment]
Currently the last attribute slot in Showcase Panel shows this:
max luck - current luck = remaining luck.
Somebody thought it should be changed to current luck instead.

**Comment by dragonjet** [comment]
ah i see, alright it makes sense. no one's aiming for 100 luck anyways
