### ISSUE TITLE
KC3 kai Resource History not working

### ISSUE THREAD

**Issue by ATLiV** [dragonjet/KC3Kai#377]
![bug](https://cloud.githubusercontent.com/assets/10157718/8878578/5784305e-325e-11e5-89c9-cf0bb2cb8693.jpg)

**Comment by Crazyteitoku** [comment]
Same issue as mentioned here: https://github.com/dragonjet/KC3Kai/issues/367

You might want to try resetting your resources graph manually via [here](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Tsusai-20150719121630/@comment-Crazy_teitoku-20150720072815?permalink=286360#comm-286360)

**Comment by ATLiV** [comment]
still error after ressting my resources graph 
![error](https://cloud.githubusercontent.com/assets/10157718/8879686/8cbca9fc-3265-11e5-9dcc-baec4971d62a.jpg)
and i got some erorrs from the console 
![error1](https://cloud.githubusercontent.com/assets/10157718/8879697/9df6d6f2-3265-11e5-9ef1-0e89e86ef65a.jpg)

**Comment by Crazyteitoku** [comment]
@ATLiV You do need to let it sit for a minimum of one hour for something to appear in the topmost graph.

Also for your dev. console. Um, your API key is apparent. :scream:

**Comment by ATLiV** [comment]
yeah, thats why im resseting my api now

**Comment by ATLiV** [comment]
btw thanks crazyteitoku
