### ISSUE TITLE
[Bug Report] Wrong equipment number

### ISSUE THREAD

**Issue by mrbenz19** [dragonjet/KC3Kai#38]
![image](https://cloud.githubusercontent.com/assets/12208086/7454196/67e42216-f2ac-11e4-882d-e609d7f1e023.png)

It seems the number of equipment shown in the tab is wrong. Please refer to the screenshot.
I'm not really sure what trigger this, but it seems it somehow persist after I close and open the KC3 Kai panel.

**Comment by mrbenz19** [comment]
I tried to do modernization several time last night and the number decreased correctly. What's weird is when I was asleep the equipment number changed by itself.
![wrongeqnum](https://cloud.githubusercontent.com/assets/12208086/7468492/6d32dd48-f333-11e4-9faa-c95dd3c28cb7.JPG)
It was 522 when I went to sleep. and now it's 549. Note that I used different computer when I opened it again after I sleep.

**Comment by dragonjet** [comment]
Ah those extra counts are ghosts from the old equipment from previous versions that were not deleted before it was fixed.

I'm putting a fix now in the upcoming version to clear the equipment everytime you start the game so there will be no more ghosts not deleted from previous versions.

**Comment by dragonjet** [comment]
As of v006, starting the game would clear and re-load all equipment, thus removing ghost equipment that increase the count: f185cdf36b66fef74d5592a082f1e4f55a380374
