### ISSUE TITLE
Air battle encounter doesn't show up in battle mode's panel

### ISSUE THREAD

**Issue by dustfan** [dragonjet/KC3Kai#382]
so, i've encountered this when i was at 1-6 air battle node. it is shown as "battle avoided" instead of the usual one. is this.. perhaps intentional?...
![air battle not working](https://cloud.githubusercontent.com/assets/12269598/8887465/dd44a44e-32bd-11e5-838e-06ad15097457.png)

the next node battle mode's panel is working fine..
![air battle not working2](https://cloud.githubusercontent.com/assets/12269598/8887938/45613afa-32d3-11e5-808f-c4b39f33322f.png)

**Comment by nicky008** [comment]
Aerial battle node for now has no any reading data functions from it yet. Need @dragonjet for more explaining.

**Comment by bamboo3250** [comment]
This is probably because of the new API response from last week update. I'll take a look at it.

**Comment by nicky008** [comment]
I forgot @bamboo3250 is also around here too. :<
