### ISSUE TITLE
Showcase not working

### ISSUE THREAD

**Issue by razgriz1412** [dragonjet/KC3Kai#386]
<img width="1274" alt="bug2" src="https://cloud.githubusercontent.com/assets/13477940/8887951/490a1fc6-32cb-11e5-945d-2625c53c908c.png">

I'm on OSX 10.10.4, MacbookPro 13" Retina 2013, Chrome Version 44.0.2403.89 beta (64-bit).

**Comment by Crazyteitoku** [comment]
There has been duplicate bug reports on this but also coming from PC users. My best bet would be is to try:
* dev. builds and see if you the problem persists. If it doesn't, then
* wait for another release to be pushed onto webstore builds.

**Comment by dragonjet** [comment]
supposedly fixed on 8eabd2760f6153f29eeb9691f1041a2b4018fec9
