### ISSUE TITLE
Background Image Adjustment.

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#39]
Hiya dragonjet3. I'm having problems with the background image. Specifically when I adjust the resolution on the screen to fit the panel snugly with the game flash object, the background image shrinks and goes BEHIND the flash object. I noticed there's this blue part on the bottom of the flash object that the background image won't expand into. The image below, look under the flash object, you'll see the fail scaled Ayanami picture and this weird blue bottom that the image won't go to:

http://i.imgur.com/9bDraws.png

My friend who does coding said its due to the div tag of the background image being inside the div tag of the game. He said the easiest fix is to create a new separate background div tag outside the game div tag so the the image expands without being limited to the flash object page. Here's the snippet he made circling where the issue lies

http://i.imgur.com/0FDaRvG.png

I have no idea what's going on since I don't code at all, but could you please look into this dragonjet3? Thanks.

**Comment by dragonjet** [comment]
v010 has more settings to let you further customize the background

![ss 2015-06-27 at 08 18 11](https://cloud.githubusercontent.com/assets/557312/8389556/24a064c4-1ca5-11e5-93a1-5b868e753a8b.png)
