### ISSUE TITLE
Cannot show battle detail of Aerial exchange node in 1-6

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#390]
This one is probably because the battle data in Aerial exchange node is different from normal battle node. @Javran Do you mind taking a look at it?

![screen shot 2015-07-25 at 2 39 39 pm](https://cloud.githubusercontent.com/assets/8078323/8888317/51287792-32db-11e5-9dc1-46aef50b0b90.png)

**Comment by Javran** [comment]
Yeah I guess you are right, I also suspect the battle data differs. Do you have a sample for the response?

**Comment by bamboo3250** [comment]
ok, I'll get one for you after finishing the current sortie :blush:

**Comment by bamboo3250** [comment]
```
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_dock_id":1,"api_ship_ke":[-1,528,523,522,501,501,501],"api_ship_lv":[-1,1,1,1,1,1,1],"api_nowhps":[-1,37,31,31,32,32,44,96,70,60,20,20,20],"api_maxhps":[-1,37,31,31,32,32,48,96,70,60,20,20,20],"api_midnight_flag":1,"api_eSlot":[[520,517,524,-1,-1],[520,523,516,-1,-1],[505,506,525,525,-1],[501,-1,-1,-1,-1],[501,-1,-1,-1,-1],[501,-1,-1,-1,-1]],"api_eKyouka":[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],"api_fParam":[[57,54,116,53],[73,93,59,52],[57,84,72,52],[59,89,59,59],[70,87,52,54],[67,88,70,69]],"api_eParam":[[25,0,50,80],[0,0,15,35],[58,42,30,60],[5,15,6,5],[5,15,6,5],[5,15,6,5]],"api_search":[2,1],"api_formation":[3,3,2],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[-1],[7,8]],"api_stage1":{"api_f_count":0,"api_f_lostcount":0,"api_e_count":168,"api_e_lostcount":6,"api_disp_seiku":4,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":0,"api_f_lostcount":0,"api_e_count":109,"api_e_lostcount":48},"api_stage3":{"api_frai_flag":[-1,0,0,0,0,0,1],"api_erai_flag":[-1,0,0,0,0,0,0],"api_fbak_flag":[-1,0,1,0,0,1,0],"api_ebak_flag":[-1,0,0,0,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0.1,0,0,0,0],"api_edam":[-1,0,0,0,0,0,0]}},"api_stage_flag2":[1,1,1],"api_kouku2":{"api_plane_from":[[-1],[7,8]],"api_stage1":{"api_f_count":0,"api_f_lostcount":0,"api_e_count":114,"api_e_lostcount":2,"api_disp_seiku":4,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":0,"api_f_lostcount":0,"api_e_count":61,"api_e_lostcount":22},"api_stage3":{"api_frai_flag":[-1,0,0,0,0,1,0],"api_erai_flag":[-1,0,0,0,0,0,0],"api_fbak_flag":[-1,0,0,0,0,1,1],"api_ebak_flag":[-1,0,0,0,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,6],"api_edam":[-1,0,0,0,0,0,0]}}}}
```

**Comment by Javran** [comment]
Thanks for the data, it does look a little different than what I've expected, will be working on the fix today.

**Comment by Javran** [comment]
I think the problem is fixed, although I don't have ship to actually try 1-6.
Would you mind if I add your data to my lib for testing?

**Comment by bamboo3250** [comment]
Okay, I'm testing it. will tell you soon :+1:

**Comment by bamboo3250** [comment]
Yes, it works perfectly :+1: Now we only need to test for combined fleet.

**Comment by Javran** [comment]
Do you mean support expedition? I have never tried that, would be able to analyze that if I can see some sample responses. For now I think it shouldn't crash my lib but the damage might be incorrect.

And also would you mind if I add your responses to my lib for testcases?

**Comment by bamboo3250** [comment]
I mean the combined fleet used in events. That means the battle will involve 18 ships (12 from ours and 6 from Abyssal) instead of only 12 ships (6 for each side) and the phases probably will be different as well. 

And yes, feel free to use my data posted here :+1:

**Comment by Javran** [comment]
I see, thanks :)
