### ISSUE TITLE
[Bug report] "Uncaught TypeError: Cannot read property 'substr' of undefined". Error not specific to any area.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#393]
**Date Seen**:
25-07-2015

**Version**:

* **KC3 Kai version**: v12.4 (github build)
* **KC3 Kai github revision**: 2a5f2e691ce468b87b45eb971cbeb6dcc0a06a2a
* **Browser**: Chromium 64bit (currently on:44.0.2403.89 (Developer Build a7caae2d2d1297d162779ecd4da09df83831842d Linux))
* **OS**: Archlinux 64bit (currently on: Linux: 4.1.2-2-ARCH)

**Bug Description**:
"Uncaught TypeError: Cannot read property 'substr' of undefined" when I-19 Kai completes bath.

Please refer to the following screenshot for more information.

**Severity**:
Unknown

**Steps to Reproduce**:
**It is unclear if this bug is reproducible or not, what is known is that the substr error occurs randomly.**
1. Send I-19 Kai into bath when she has minor scratches (<= ~5HP)
2. Wait for her to come out of baths whilst you are at the main screen.
3. Error shows up in dev. console around the time when I-19 Kai is due to come out of the baths.

**Actual Behavior**:
Error comes up and possibly no desktop notifications were received.

**Expected Behavior**:
The error is to not show up, this might be something to do with desktop notifications.

**Troubleshooting/Testing Steps Attempted**:
None.

**Workaround**:
None as this issue seems to randomly occur under certain and varied circumstances.

**Attachments**:
![screenshot from 2015-07-25 21-03-14](https://cloud.githubusercontent.com/assets/12234182/8889141/a073eda6-3310-11e5-9050-ec24571e90f8.png)

**Comment by bamboo3250** [comment]
Do you know any other ship creates this bug? I still want to keep my Iku as SS. I tried to repair many ships but no use :sob:

**Comment by Crazyteitoku** [comment]
@bamboo3250 the bug is really random. I had it happening again at random time when I got Maya as a drop from 2-3 when I was subcheesing that map.

Other times were when two expedition fleets that came back, number 2 and 4. One from expedition 6 and the other from 21 I recall and as I went back into the main screen (where you see your office) the bug resurfaces.

It still happens with the most recent git revisions of KC3 Kai. Now on 1ca5e85 and another error happened when I was asleep at 0334hrs (3:34am) with I think an expedition fleet that came back.

**Comment by dragonjet** [comment]
ah I looked at this yesterday, forgot my findings. or maybe I didn't have findings thats why I don't remember any :laughing:

**Comment by bamboo3250** [comment]
@Crazyteitoku I also got this bug a few times before but also failed to replicate it. It's probably not because of any specific ship. I even set up a lot of traps around `Meta.js` and `Ship.js` to catch this bug but it didn't appear anymore after that :joy:

**Comment by dragonjet** [comment]
ah I got the problem

`PlayerManager.repairShips` is a plain array without specific designation which index is which

if you have 2 repairing ships on slot-2 and slot-4, `PlayerManager` will just push the ship ids into `repairShips` and will become `[ 101, 102 ]`

when `Timer.js` used it:
`PlayerManager.repairShips[this.num]`
it assumed that the index is the repair slot, which is not the case

this generates an "undefined" value on that index

**Comment by bamboo3250** [comment]
Oh i see. No wonder why it happens randomly and hard to replicate like that :+1:

**Comment by Crazyteitoku** [comment]
Wow :scream: didn't think it was easy to trace down this bug or perhaps this is one of the few bugs that shares the same error.

Good job nonetheless! :+1: looking forward to a fix and thanks for assisting with the bug.

**Comment by dragonjet** [comment]
pushed an "untested" fix :laughing: 

might break all shens XD

**Comment by nicky008** [comment]
Hope RNG is blessing this fix... :godmode:

**Comment by Crazyteitoku** [comment]
Unfortunately the bug still happens but on different lines within the same files. I had three subs sent to baths, 1 maruyu kai, 1 imuya kai and 1 ro-500.

**Comment by dragonjet** [comment]
ah I know this. on the fixed, I assigned them to the `ndock.api_num` which starts with `1`. and when used by `Timer.js`, index starts with `0`

**Comment by dragonjet** [comment]
another "untested" fix, may Talos bless this build
