### ISSUE TITLE
Request: Screenshot button on Battle Tab

### ISSUE THREAD

**Issue by gdp740** [dragonjet/KC3Kai#399]
~

**Comment by LostLogia4** [comment]
Hmm, Is that one for horizontal mode?

**Comment by bamboo3250** [comment]
I think so. There has already been one in vertical layout and we should resolve this issue by the end of this week.

**Comment by ethrundr** [comment]
supposedly yes, since vertical one already have it.....

**Comment by dragonjet** [comment]
I'm keeping this tab open so I don't forget to do today
