### ISSUE TITLE
Adjusting background image creates strange bugs.

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#4]
I'm having a bug where the health bar of damaged ships is cut up. Like this:

http://i.imgur.com/3wDzwcF.png

The anchor icons for construction reappeared after I constructed some ships, but they vanished completely after changing the background of the flash object through the settings.

Verniy's name is spelled wrong. Comes out as Vernyj

**Comment by dragonjet** [comment]
Thanks for reporting~

The HP bars are fixed on 51d749aff81f25ac9d9cded386cba5564206d1ed

About the construction icons, did you refresh the game screen? If so, you'll also need to refresh the panel as well. The recommended procedure is:

- Refresh game (but do not click the "Start game anyway")
- Close admiral panel
- Reopen admiral panel
- Go to KC3 Kai tab to activate the game

Verniy's name has also been fixed on d73213f430128b95c9d13c7b0b917c516ccceef5

Thanks again~
