### ISSUE TITLE
[Translation: FR] items, battle

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#400]
@Arkayda963

Juuryoushin sent enhancements for the french translations from here

http://kancolle.wikia.com/wiki/Thread:289647

pastebins:
* `items.json` http://pastebin.com/TPH4hQZf
* `battle.json` http://pastebin.com/tGnuX0zR

see if it's alright to merge

**Comment by Arkayda963** [comment]
hum... i talked with him and i'm ok with that :)

**Comment by dragonjet** [comment]
merged, thanks :+1:
