### ISSUE TITLE
Prinz Eugen is not included in ships.json

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#402]
This makes the 改 not translated.

![screen shot 2015-07-26 at 12 05 53 pm](https://cloud.githubusercontent.com/assets/8078323/8892533/cc90f3c4-338e-11e5-9b6e-00ee05c9a4e5.png)

**Comment by nicky008** [comment]
lel...

**Comment by bamboo3250** [comment]
I just added more description. Poor Prinz, she is forgotten for so long xD

**Comment by dragonjet** [comment]
oh toplel

**Comment by dragonjet** [comment]
merged #403
