### ISSUE TITLE
Explain requirements not met for expedition?

### ISSUE THREAD

**Issue by Javran** [dragonjet/KC3Kai#404]
KanColleHelpers is already capable of listing requirements not met for a specify fleet.
I'm just thinking about how to use this feature: now available expeditions are in blue circles, maybe other expeditions can be grayed out and some tooltips can be added to gray circles indicating requirements not met.

The API is already designed for the ease of translation: [Requirements](https://github.com/Javran/purescript-kancolle-helpers/blob/master/src/KanColle/Expedition.purs#L27) are actually defined as algebraic data type, for example `Flagship (ShipDrum 2)` is saying "flagship should at least carry two drums", values can be distinguished by javascript `instanceof`.

Let me know whether you are interested in this. Going to sleep, will response late.

**Comment by dragonjet** [comment]
hm this is interesting, though I doubt we'll need to implement this immediately on the panel. We already have [users complaining about spoon-feeding](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Fackifiknow-20150725052802?permalink=289178#comm-289178) and asking for settings to turn it off. We can retain the blue circles on panel, but the advice for unqualified expedition might be better for the Strategy Room.

**Comment by Javran** [comment]
I see what he's concerning. And here are some suggestions:

* hide these blue circles for fleet 1, as it doesn't seem necessary. Sorry that I forgot to do this after adapting to the new API.
* change the way it works: after my very first hack, I often find myself looking at the list of numbers and see if the intended one is there, maybe we can just keep a drop-down list somewhere. It show nothing by default, but if user choose one expedition, then we print out requirements not met. We can have more features in strategy rooms, but I think it's still good to have this in devtools page, as the strategy room doesn't seem to be responsive about fleet member / equipment changes.

**Comment by Crazyteitoku** [comment]
The same person in question pretty much got worked up over the [unpolished edges of KC3 Kai and called it quits](http://kancolle.wikia.com/wiki/User_blog:Dragonjet/KC3%E6%94%B9#comm-290140), hopefully I can try and alleviate the issue a bit.

**Comment by dragonjet** [comment]
alright, wrote a response to that guy, didn't notice it was the same person complaining

about the expedition, I see the point about not needing to show all qualified, but instead its true that players first decide on the expedition to go to, and build the fleet from there, not the other way around. :+1:

**Comment by dragonjet** [comment]
will be included in #685
