### ISSUE TITLE
[Bug report] Sortie history only shows one entry per page (warning: lots of images).

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#412]
**Date Seen**:
27-07-2015

**Version (for reference only, also affects webstore build)**:

* **KC3 Kai version**: v12.4 (github build)
* **KC3 Kai GIT commit SHA-1 checksum**: 7af2504937d7a743717a4038a74873ba32759bd5
* **Browser**: Chromium 64bit (currently on: 44.0.2403.107 (Developer Build 1914941a92d699e55418434ff976ef3e76944001 Linux))
* **OS**: Archlinux 64bit (currently on: Linux: 4.1.2-2-ARCH)

**Bug Description**:
Sortie history shows only one sortie per page.

Please refer to the following screenshots for more information.

**Severity**:
Major

**Steps to Reproduce**:
1. Open up strategy room.
2. Go into Maps tab (under Sortie)
3. Entries are shown as one per page (when there should more).

**Actual Behavior**:
* Only one sortie history per page. Even if going into the world and map as labelled still only shows one sortie history per page. 19 other entries per page are missing.
* Unsure if this is related but pressing on the Nodes button (labelled as "N") on the only available sortie history doesn't show anything even if you have the Fleets button (labelled as "F") clicked.

**Expected Behavior**:
* Sortie history page should show the usual amounts (20 entries per page).
* Also when clicking on Nodes button it should also display historical information on enemy encounters.

**Troubleshooting/Testing Steps Attempted**:
Tried using latest git commit but still only shows one sortie history per page.

Tried backtracing the issue with some form of success:
* https://github.com/dragonjet/KC3Kai/commit/0418cb538116626b9960a8bd0d8823a906d2b87d shows that the sortie history was definitely full
* https://github.com/dragonjet/KC3Kai/commit/b25bbb09b46499e97027497f14f47a35ff8d238b is where it is broken.

**Will update on this part to see if there were any improvements to the situation.**

**Workaround**:
None yet.

**Attachments**:
![screenshot from 2015-07-27 22-08-13](https://cloud.githubusercontent.com/assets/12234182/8905835/ef8a22e6-34ac-11e5-9874-2abf2b4723f0.png)
![screenshot from 2015-07-27 22-08-55](https://cloud.githubusercontent.com/assets/12234182/8905834/ef8a1120-34ac-11e5-8315-a758beb19603.png)
![screenshot from 2015-07-27 22-09-25](https://cloud.githubusercontent.com/assets/12234182/8905836/ef8e1518-34ac-11e5-8675-01378ad5f69d.png)
![screenshot from 2015-07-27 22-09-46](https://cloud.githubusercontent.com/assets/12234182/8905838/ef90f17a-34ac-11e5-9759-15ef67602d1a.png)
![screenshot from 2015-07-27 22-10-12](https://cloud.githubusercontent.com/assets/12234182/8905837/ef90db72-34ac-11e5-85ab-c7e46bcc7952.png)
![screenshot from 2015-07-27 22-10-26](https://cloud.githubusercontent.com/assets/12234182/8905839/ef92ca86-34ac-11e5-9895-630e65601e66.png)
![screenshot from 2015-07-27 22-10-49](https://cloud.githubusercontent.com/assets/12234182/8905840/efbcea5a-34ac-11e5-9cbf-fe2b0aae616f.png)

**Comment by ethrundr** [comment]
@Crazyteitoku On my place, the Strategy Room behaves correctly and shows all past sorties I've done before. I don't know though, whether it's already fixed yet or not.
![screen shot 2015-07-28 at 02 27 46](https://cloud.githubusercontent.com/assets/13522800/8912894/9cf4f438-34d0-11e5-84c4-87eab1b61a7b.png)

**Comment by dragonjet** [comment]
whoa that's alot of sorties :open_mouth:

**Comment by ethrundr** [comment]
well, I suppose "trying to stay in the rank" explains that massive amount of sorties :p

**Comment by nicky008** [comment]
Why not 5-4? :astonished:

**Comment by bamboo3250** [comment]
this bug happens to me, same as @Crazyteitoku

**Comment by ethrundr** [comment]
@nicky008 oh those sorties were clearing the weeklies. after all weeklies done, I'll back to 5-4 :smile:

**Comment by Crazyteitoku** [comment]
I am fairly certain it was one of the more recent GIT commits (prior to the SHA-1 sum that I made a bug report based on) that may have broke the sortie history. 

Working with the actual GIT command line seemed difficult but I sort of have figured out how to jump to and fro between various commits and what not. So I'll try and backtrace the issue and see which version it was and a diff report on it. Been meaning to do that but never actually having done so.

**Comment by ethrundr** [comment]
@Crazyteitoku imo most likely it is the case of un-synchronised copy.

I've worked with GitHub before in my previous job, and this issue happens a lot when someone forgot to pull all the updates before he push a new one.

**Comment by Crazyteitoku** [comment]
@ethrundr not that I have any experiences with this but just hoping that it is the case of un-synchronised copy. The problem with that now is how to trace down to exactly where the bug is lying. :confused: Thanks nonetheless.

Earlier on I spoke to @Madobe (Nanamin) and apparently git checkout is for branches, if I want to use previous revisions I needed to rebase my git. I am going to leave this as a note for myself hoping that I can find a better way to troubleshoot the issue as I still don't have much of a clue with all the fancy git commands that are available.

**Comment by dragonjet** [comment]
hm let me check this out now once and for all

**Comment by Crazyteitoku** [comment]
Thanks @dragonjet :+1: if only I could somehow also figure out how to make an even more detailed bug report and analysis in the future. This issue seems deep.

**Comment by dragonjet** [comment]
fix up. check the fix commit to uncover the mystery

**Comment by Crazyteitoku** [comment]
'''<script type="text/javascript" src="../../assets/js/KanColleHelpers.js"></script>'''

lel :+1: thanks it worked!

**Comment by Crazyteitoku** [comment]
This bug has resurfaced on git commit: f4bffe73671cb27f5f18742bdc01143abddb7e96

Gonna leave this here and try to remind self to backtrace it.

**Comment by dragonjet** [comment]
Pushed a fix. New bug involves night battle nodes on sortie history.

**Comment by Crazyteitoku** [comment]
Wow quick response, thanks! :+1:
