### ISSUE TITLE
[Suggestion] Battle Node Icons Explanation

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#415]
It'll be a good idea to add some text that will appear while the mouse pointer hovers over these symbols. This short explanation will give details to the user about what those symbols are actually representing. Especially, on these symbols: 
![screen shot 2015-07-28 at 03 28 59](https://cloud.githubusercontent.com/assets/13522800/8914192/d34b47aa-34d8-11e5-8ccd-7441216ddb28.png)

Although for most experienced player those symbols are already obvious, this will be very helpful for newer player, to understand all the symbols there, as well as symbols implemented in-game.

**Comment by dragonjet** [comment]
hm I was sure I added on hovers on these.

also tested it just now for both horizontal and vertical orientations

**Comment by ethrundr** [comment]
ah yeah, it was error on my side. hover texts appears really slow here on my computers.

trying relaunch the panel, hover above them and wait for a while, then it's appearing now.
thanks for the info @dragonjet ~
