### ISSUE TITLE
[Suggestion] Explanatory header text needed for the "Expedition Qualification Checker"

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#416]
Without any explanation, or at least header, I don't think users will now what are those numbers below the fleet composition. So far I've asked my friends, they just know what they are after consulting the GitHub. This supposedly not happen in my opinion. People should be able to easily understand each and every feature even without consulting to the GitHub.

As for example, just try looking to this image. Without any knowledge about what is it, I believe not many that can guess what is this for:
![screen shot 2015-07-28 at 03 43 11](https://cloud.githubusercontent.com/assets/13522800/8914519/d45c38aa-34da-11e5-8d95-615b3deadaad.png)

**Comment by dragonjet** [comment]
ah there's also a discussion on #404 where the blue circles will be removed and will be changed with a feature where the player selects a specific expedition, and test the fleet for its requirements, and tell which else is missing from your fleet comp or equip

the main argument there was, the player first aims for an expedition via its resource output, etc, then build the fleet upon it.. not the other way around where you build a fleet, then check which expedition to go to

**Comment by ethrundr** [comment]
kinda agree with that argument. the blue circles gives no information whatsoever for me personally, since at the first time I don't even know what is it for.

**Comment by dragonjet** [comment]
Closing because of new plans for Expeditions in #722, no more balls
