### ISSUE TITLE
[Suggestion] Improvement for the Paging on the Sortie History

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#417]
It'll be a good idea to trim the paging into only 10 pages and the last page, then hide the rest. The idea is just like the paging you can see on most all search engine's result: they only display number of pages, followed by three dots, then the last page (Like: 1 2 3 4 5 6 ... <Last>). As the page progressing, then the preceding page will be trimmed into: first page, three dots, several previous page, current page, several following page, three dots, last page (Like: 1 ... 4 5 6 7 8 ... <Last>, if the user now is in page 6).

Then, to allow user to jump to a specific page, just add a box for user to input their desired page destination and a button to confirm it. I know this gonna be some work, but it'll be better than having stacks of pagelist at the top of the sortie history like we have now. Also, this should only be applied in the "All Runs" and "All World X" tabs, since these tabs has the highest potential to have lot of pages of history.

Finally, since each history is expandable, adding a "Expand All" and "Collapse All" button might be a good addition, but this is not that needed for now I think.

**Comment by dragonjet** [comment]
ah this is true, after seeing your screenshot XD

**Comment by ethrundr** [comment]
lol XD
to be honest I'm also surprised when first time see the page after knowing it's already working again
90 pages!

**Comment by dragonjet** [comment]
lol this was included in all Event Priority thread but kept getting moved.

@ethrundr can wee see how long your sortie history pagination is now? xD

**Comment by ethrundr** [comment]
@dragonjet just this long XD
![screen shot 2015-08-21 at 14 37 14](https://cloud.githubusercontent.com/assets/13522800/9401979/30715018-4812-11e5-8eb7-2b41fc9acf79.png)

the old (and long) one is on the Webstore version, gotta take a screenshot after the update is implemented~
