### ISSUE TITLE
[Bug] Equipment count after modernization

### ISSUE THREAD

**Issue by IILLMASTER** [dragonjet/KC3Kai#42]
I think the equipment re-counting after we do modernization still not fixed yet
![image](https://cloud.githubusercontent.com/assets/12247000/7467620/84488012-f326-11e4-9d97-ed29cca06230.png)

**Comment by dragonjet** [comment]
same as #38

Ah those extra counts are ghosts from the old equipment from previous versions that were not deleted before it was fixed.

I'm putting a fix now in the upcoming version to clear the equipment everytime you start the game so there will be no more ghosts not deleted from previous versions.

**Comment by dragonjet** [comment]
As of v006, starting the game would clear and re-load all equipment, thus removing ghost equipment that increase the count: f185cdf36b66fef74d5592a082f1e4f55a380374
