### ISSUE TITLE
[Bug] "Battle Avoided" For Night Battle Nodes

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#421]
Just recently do my daily 5-4 runs, and noticed that at node 6 (night battle node), sometimes it's appear as "Battle Avoided", instead of the enemy formation. The other Day Battle nodes are working perfectly, though.

Here's some screenshot on the node 6:
![screen shot 2015-07-28 at 14 31 49](https://cloud.githubusercontent.com/assets/13522800/8924180/bfd59cf4-3535-11e5-8d9b-c2b894ea6941.png)
![screen shot 2015-07-28 at 14 31 55](https://cloud.githubusercontent.com/assets/13522800/8924181/bfd6154e-3535-11e5-99e2-1513f87083c7.png)

While on the next node (node 10):
![screen shot 2015-07-28 at 14 35 08](https://cloud.githubusercontent.com/assets/13522800/8924208/13785324-3536-11e5-92ab-0dfab4f5edb1.png)
![screen shot 2015-07-28 at 14 37 10](https://cloud.githubusercontent.com/assets/13522800/8924237/46bff6ce-3536-11e5-985b-5455881de14c.png)

Haven't tested this on the other map yet, though.....

**Comment by bamboo3250** [comment]
Could anyone check the API response of map 5-4? I'm stuck at 5-3 :sob: 

btw, there is also a issue about map 5-4 here #120 but I'm not sure they are the same or not.

**Comment by ethrundr** [comment]
@bamboo3250 poor you :laughing: 

about that issue, I also see it, but since not sure what it is talking about, so I decided to make a new thread.

**Comment by bamboo3250** [comment]
Haha, it trolls me as hell :joy: I'll make an attempt to clear it after the event and LCS :angry:

**Comment by dragonjet** [comment]
hm maybe I should try clearing 5-3. iirc my fleet can take it but unable to compass to boss

**Comment by nicky008** [comment]
Or... waiting for some NB nodes in the upcoming Summer event? :trollface: 

I'd tried passing this node and saw the same problem too. (No special condition checking in the current code?)

**Comment by LostLogia4** [comment]
Explored that midnight node in your stead. I'll send you the gathered info shortly.

**Comment by dragonjet** [comment]
pushed an untested fix attempt at it. is there any other night battle node earlier than 5-4?

**Comment by ethrundr** [comment]
Haven't tested on map other than 5-4 though.
Give me time, I'll try testing it on 4-5, 5-3 and 5-5.

**Comment by ethrundr** [comment]
@dragonjet managed to test on 4-5 and 5-3, and it seems that all night battle nodes are experiencing the same bug with 5-4 night battle node posted above.

Here's the screenshot:
![screen shot 2015-07-29 at 08 31 59](https://cloud.githubusercontent.com/assets/13522800/8946707/8a192cfa-35cd-11e5-853a-0b029d383420.png)
![screen shot 2015-07-29 at 08 32 06](https://cloud.githubusercontent.com/assets/13522800/8946706/8a18dd72-35cd-11e5-96f9-cbadb2ca25bb.png)
![screen shot 2015-07-29 at 08 33 44](https://cloud.githubusercontent.com/assets/13522800/8946708/8a1ec354-35cd-11e5-840b-e9cfe80e492e.png)
![screen shot 2015-07-29 at 08 33 51](https://cloud.githubusercontent.com/assets/13522800/8946709/8a225316-35cd-11e5-85a1-af9f235105d3.png)

**Comment by dragonjet** [comment]
I tested on 5-3 with a sub so I can get a night battle node, pushed a fixed now
