### ISSUE TITLE
Furniture Box Icon on Resource Node

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#426]
Broken for Medium and Large Boxes.

**Comment by bamboo3250** [comment]
Have you checked the latest github build? I think it has been fixed here #396

**Comment by ethrundr** [comment]
@SanaNoHana all I can say, unless you want to update yourself with each commit the KC3kai's developer had on the GitHub, just wait for the v13 to be released, since those fix already included as v13 milestone as far as I know.
