### ISSUE TITLE
Resource History and Sortie data shows in Excel

### ISSUE THREAD

**Issue by URSvAir14** [dragonjet/KC3Kai#43]
I opened up Excel earlier in the week and when I opened it up I got a message saying "Recovering data from previous session". Straight after I had got 2 excel files (or one with 2 sheets). One of which contained sortie data with a collection of images and the ships I used, and the other one was a wall of text showing my resources count at various points. I assume these were from KC3 Kai and it is how you store the Strategy Room data. This happened shortly after my resource graph for the last 24 hours went blank from a certain time period, which has happened repeatedly.

Is there a way to stop this from happening?

**Comment by dragonjet** [comment]
KC3改 saves its data on browser's "localStorage" and "IndexedDB", not excel files. Did you use KCV before? It's KCV that saves those data in excel files

**Comment by URSvAir14** [comment]
Oh okay, that must be it. Thanks for the help
