### ISSUE TITLE
Transport quest tracking

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#431]
So, I did 3-5 and noticed that the red transports from the boss node do not count towards the tracking of the Weekly Sortie about sinking 20 transport ships (I'm feeling kinda dumb right now, I just clicked on the reset weekly sorties button thinking it would take me to a page that lists only my progress on weekly quests to get the name of it, as I just closed the game and do not feel like opening it again, I'm kinda tired). I believe they count for that one

**Comment by dragonjet** [comment]
ah you mean the Elite Wa? does the normal Wa count on the same node?

**Comment by AlanSchaeffer** [comment]
Yeah;
There's no normal Wa there though; if you mean the flagship one from the final formation, I haven't yet faced against it

**Comment by bamboo3250** [comment]
I think they use other IDs for flagship and elite abyssal, probably in form of `[ Transport Ship, Flagship/Elite]`

**Comment by nicky008** [comment]
Some elite types of these abyssal ship classes are not shown for now too, not only this transport class.

**Comment by AlanSchaeffer** [comment]
@nicky008 haven't had the chance to test yet, kinda stuck on this final kill crap. I'll get back here as soon as I can verify if it counts

**Comment by bamboo3250** [comment]
I think Elite transport ship is still counted properly. This is my screenshot in 3-5. Pay attention to Weekly Sortie 4 (kill 50 transport ship). 

Before battle, it was 5/50.

![screen shot 2015-08-01 at 4 07 44 am](https://cloud.githubusercontent.com/assets/8078323/9016384/6587b5d6-3803-11e5-9a49-40c70d63ca2b.png)

After battle, 2 elite transport ship were sunk and it became 7/50.

![screen shot 2015-08-01 at 4 09 23 am](https://cloud.githubusercontent.com/assets/8078323/9016386/695f8e22-3803-11e5-8c8e-b8a9c290a7fb.png)

**Comment by AlanSchaeffer** [comment]
I finished the map yesterday and the flagship enemy did not count either - actually I forgot to check it, and was kinda worried since the month reset today but I remembered this was a weekly quest, so it should still be the same count. So, Weekly Sortie 3 - sink 20 abyssal transport ships is still reading 0/20, despite me having it active for the entire duration of my 3-5 last minute struggle. I remember it tracked perfectly when I did 2-2 for the transports, could it be that this one quest in particular is not counting the evolved transports? I could quickly run 2-2 again and tell you if the normal transports there will increase my count or not, brb

**Comment by bamboo3250** [comment]
I see. Are you using Webstore version? I guess @dragonjet hasn't released the latest version yet.

**Comment by McDohl** [comment]
@bamboo3250 seems so, since my transport quest counted properly

**Comment by bamboo3250** [comment]
I just checked the milestone. That fix is marked as v13, which is scheduled to release on Aug 3rd :kissing_closed_eyes:

**Comment by dragonjet** [comment]
ah so we can mark duplicate and close?

**Comment by bamboo3250** [comment]
let's wait for @AlanSchaeffer to confirm the version he is using.

**Comment by AlanSchaeffer** [comment]
Yep, using Webstore here!

**Comment by bamboo3250** [comment]
Thanks for confirming it :+1:
