### ISSUE TITLE
Quest Translation 

### ISSUE THREAD

**Issue by si54l2e** [dragonjet/KC3Kai#435]
![image](https://cloud.githubusercontent.com/assets/13566391/8976597/5a436320-3644-11e5-87e7-1a393e67a1f5.png)
Correct me if I'm wrong, but shouldn't the language used for quest translation match the global language chosen in the settings panel?  I am getting Vietnamese translations while I have English selected.  Is this a side effect of commit e073fa0fa46c03485d75e3dd1392731236c80e56?

**Comment by bamboo3250** [comment]
Oh yes, you're right. I made a mistake there. I will fix it right now. :scream:

**Comment by si54l2e** [comment]
Much appreciated! ^_^
