### ISSUE TITLE
[Bug] Fleet tab in strategy room goes kaput

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#437]
If you had scrap/modfodder any of the ships currently in the 1st fleet and go to the current fleet tab, the strategy room would hang and give this error:

Uncaught TypeError: Cannot read property 'substr' of undefined

**Comment by ReiFan49** [comment]
i guess this is caused because there's no update while destroying the ship (with any way) to the fleet data.. using fleet swapping technique might works hmm (gonna check on it)
