### ISSUE TITLE
Abukuma Kai Ni icon is missing

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#441]
No screenshot but I know she is still missing until this point. Just a reminder :smile:

**Comment by nicky008** [comment]
I'd reminded @dragonjet for a nearly week ago... :smirk:

**Comment by dragonjet** [comment]
eh? user page? :open_mouth:

**Comment by McDohl** [comment]
<a href="http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-Nicky008-20150724131622?action=history"> userblog*</a>

**Comment by dragonjet** [comment]
got me there :laughing:

**Comment by dragonjet** [comment]
tbh this is part I hate on kc3 kai, have to redownload updated swfs, compile photo, slive, upload to photobucket
