### ISSUE TITLE
Event Priority

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#444]
We list here the bugs, features and enhancements most needed for the event, and link the entries so we don't forget anything. Good to have it on hand. Will update main post when replies are posted.

Our users should not add new suggestions or reports here. If it is new, create a new issue and link it here if needed for the event.

**Before-Event**
:white_check_mark: #29 Battle Prediction
:white_check_mark: #399 Screenshot for Horizontal Battle Mode
:x: #471 Combined fleet mode for Horizontal (*only for natusiro*)
:white_check_mark: #485 Prediction for Support kills
:white_check_mark: #461 Support FCF ship statuses
:white_check_mark: #369 Detection of event difficulty selection

After-event API verification and other issues will be further tracked on #461

**Comment by bamboo3250** [comment]
My opinion: 
Battle Prediction #29
Screenshot button on Battle Tab #399
Improvement for the Paging on the Sortie History #417

**Comment by nicky008** [comment]
It's a sad story that there is no "sticky posts" option or "announcements" option on Github like many webboards there.

PS. Ah @dragonjet, this 444th number is your intending or just about the RNG? :relieved:

**Comment by dragonjet** [comment]
RNG :laughing:

**Comment by Crazyteitoku** [comment]
Somewhat better than 444th number than 666 or 616 :stuck_out_tongue_closed_eyes: 

Note am somewhat reserving this post position for suggestions to be added.

**Comment by c933103** [comment]
Top priority would be decode how the bew combined fleet api is formed and let kc3 kai accomodate with that.
Also #369 drop report info

**Comment by ethrundr** [comment]
I found some minor glitch that should be tested and fixed just a while ago. Complete report is in #471

**Comment by dragonjet** [comment]
updated main post

**Comment by nicky008** [comment]
v016? Just be after or during in the Summer event?

**Comment by dragonjet** [comment]
ah I think all except
* #461 Verify all Event API calls are supported
* #369 Drop reporting per event difficulty

are possible before the event

**Comment by dragonjet** [comment]
that v16 milestone is supposed to be during the long maintenance, so it's the same as being before-event

**Comment by c933103** [comment]
poi's dev mentioned that he can no longer find info about plane slot distribution on new abyssal ships from api_start2 after the most recent api update. Is this a problem here as well or is there some other methods to obtain the info?

**Comment by dragonjet** [comment]
yep, iirc and equipment and possibly planes slots as well were removed from `api_start2` since October 2014, or at least the equipment is. If the plane slots remained after october, it might have been removed as well in the same API update where we also lost compass prediction.

the way to get enemy plane count right now is via the battle APIs where it specifically says total plane count (not per slot) and how many were shot down inside data: `api_koukou`

**Comment by c933103** [comment]
If i understand corrwctly, then in case a new abyssal ship equipped with 2 different type of torpedo bombers and 2 different type of dive bombers, we have next to no way to find out do is it 10-20-30-40 or 25-25-25-25?

**Comment by ethrundr** [comment]
In my opinion, these two also need to be resolved by the time event starts:
#482 Battle prediction update for night battles
#485 Ship sunk by support expedition is not marked in the prediction

**Comment by dragonjet** [comment]
@c933103 hmm somewhat right, we won't know the plane slot combination, but we might be able to know the plane type combination. the battle APIs include equipment IDs used by the enemy, that's why when they shoot on the in-game animation, we can see their equipment on the pop-in CG. but that's only icons, not telling how much stat that equipment is, and how many slots that is/

#482 is resolved now I think, we just have to test
#485 yes will add it

**Comment by c933103** [comment]
then, #28

**Comment by c933103** [comment]
#533

**Comment by dragonjet** [comment]
omg omg so much to do i dont know anymore

i still need to prepare the decoders for later asdf asdf

:sob:

**Comment by nicky008** [comment]
@dragonjet Beware catbomb overloading :cat2:

**Comment by dragonjet** [comment]
we do have a way to test while maintenance though >:)

Go to `chrome-extension://xxxxxx/pages/test/index.html`

**Comment by dragonjet** [comment]
After-event API verification and other issues will be further tracked on #461
