### ISSUE TITLE
[Bug report] JPG screenshot creates 0 length files.

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#446]
**Date Seen**:
01-08-2015

**Version**:

* **KC3 Kai version**: v12.4 (github build)
* **KC3 Kai GIT commit SHA-1 checksum**: dc9e60345a43ee269f208da37e405cae354aadc5
* **Browser**: Chromium 64bit (currently on:44.0.2403.125 (Developer Build 62769abba637a751ff0a7f904cc3658c5e3e741c Linux))
* **OS**: Archlinux 64bit (currently on: Linux: 4.1.2-2-ARCH)

**Bug Description**:
Clicking on the screenshot button when the type of image format to be created for screenshot is jpg results in zero length file.

This does not happen if one chooses to use png image format instead of jpg format.

Please refer to the following screenshots for more information.

**Severity**:
Minor

**Steps to Reproduce**:
1. Open game up normally with KC3 Kai via API link.
2. Make sure that you have Developer tools on and that under Developer tools it is showing either Kancolle or DevKC3Kai.
2. Press the screenshot button a few times.
3. Under Developer tools, switch the view to Console.
6. Watch the errors show up

.

**Actual Behavior**:
* Errors appear within the background view.
* Under the pre-set download area: ~/Downloads/KanColle the JPG files all appear to indicate zero length.

**Expected Behavior**:
The JPG file to be created normally and that it should work just like if one chooses to use PNG.

**Troubleshooting/Testing Steps Attempted**:
* Switched across to PNG for image type creation as opposed to JPG.
* Updated to git commit: 5d455590fe642b477eb5f8bfc85583ded9fd24bd and errors still persists.

**Workaround**:
* Use PNG format as opposed to JPG.
* Alternatively, the use of third party tools such as LightShot also works.

**Older attachments**:
![screenshot from 2015-08-01 21-50-40](https://cloud.githubusercontent.com/assets/12234182/9021894/64accc1c-38a0-11e5-8b0d-9de4b02f5ab3.png)
![screenshot from 2015-08-01 22-14-43](https://cloud.githubusercontent.com/assets/12234182/9021893/64aa0aa4-38a0-11e5-8915-d07b58d17cef.png)
![screenshot from 2015-08-01 23-00-58](https://cloud.githubusercontent.com/assets/12234182/9021916/37590c20-38a1-11e5-8e71-03fc9d8586ee.png)

**Newer attachments**:
![](http://i.imgur.com/l4Di2n2.png)
![](http://i.imgur.com/7PTPFS2.png)

**Comment by Crazyteitoku** [comment]
Just a minor update that I have given google-chrome (the official Chrome that is endorsed by Google) - as suggested by @dragonjet and that the JPG screenshot function works without any errors.

The issue is now really bizarre as both Chromium build as well as Chrome build are the exact same versions: 44.0.2403.125

Two likely possible causes as to why JPG screenshot function doesn't work and PNG does work under Chromium build might be:
* A third party tool that I have installed may have "hooked" to reserving the JPG function.
* Due to historical licensing issues (e.g. issues with the use of MP3 licences) the JPG functionality isn't officially implemented.

As stated the issue is minor and it is unlikely that users will face such issues I am thinking of just closing the issue. It really is an isolated case at this point.

**Comment by dragonjet** [comment]
oh so it's a problem with chromium dev build?

**Comment by Crazyteitoku** [comment]
@dragonjet yeah I'd likely say that would be the case. Thanks for your help nonetheless :smile:

I will have another attempt again at the Google chrome store build as the first time when I tried it, a few unexpected things happened on other fronts. Nonetheless it is unlikely those unexpected things could have influenced the outcome of the bug.
