### ISSUE TITLE
development's screen icon

### ISSUE THREAD

**Issue by dustfan** [dragonjet/KC3Kai#45]
it's minor, but the icon in this picture is wrong.. it happened 2 times, but i only ss'd the last.. the first is 12.7mm MG with Autogyro icon and type 14 Air Radar with AP shell icon..
![image](https://cloud.githubusercontent.com/assets/12269598/7489906/93012e06-f416-11e4-8660-c54e15017b37.png)

**Comment by dragonjet** [comment]
thanks for reporting this~
