### ISSUE TITLE
Battle Spoiler/Prediction is wrong for vertical orientation

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#452]
![70dac1f3d6a76c703cdb1f539856e97e](https://cloud.githubusercontent.com/assets/13024936/9024838/4ec9a412-3911-11e5-9517-b1356de30c3a.png)

![e0885a4bd516d76f17818fc3c5d2c772](https://cloud.githubusercontent.com/assets/13024936/9024859/da0c1afa-3911-11e5-8877-52e4cb20cccd.png)

was sparkling at 1-1 and noticed this.. so i encountered jintsuu and shimakaze at 1-1 eh? :P 
P/S : they were my opponent for my last pvp

**Comment by bamboo3250** [comment]
That's weird, I didn't get the bug in 1-1. :open_mouth: 

![screen shot 2015-08-02 at 2 02 06 pm](https://cloud.githubusercontent.com/assets/8078323/9024945/41632182-391f-11e5-9c90-baca344e2a5e.png)

**Comment by McDohl** [comment]
it's from latest version o.O

**Comment by bamboo3250** [comment]
Okay, I know the reason, will push the fix in a few minutes.

**Comment by McDohl** [comment]
thanks for fast reply :+1:

**Comment by bamboo3250** [comment]
You are welcomed. It only happens after you go to PvP so hopefully you haven't finished today PvP yet :sweat_smile:

**Comment by McDohl** [comment]
I always PvP at 1 hour left before it's reset. But since it's for testing, will try now.

Thanks its working already :+1:
