### ISSUE TITLE
Strategy Room Operations - Fleets Tab Error

### ISSUE THREAD

**Issue by Nilvaren** [dragonjet/KC3Kai#46]
When opening Strategy Room then select the Fleets tab from Operations. After Fleets tab is selected then I can't change to the other tab like Home, Ships, etc. Tried updating, and Re-Installing the Extension but nothing works.

**Comment by dragonjet** [comment]
are you from **Saiki Bay Anchorage** by any chance?

**Comment by Nilvaren** [comment]
I'm from Iwagawa Airfield.

**Comment by dragonjet** [comment]
hm there had been multiple reports before about fleets tab stopping everything else, though we never got to the bottom of it, can you open F12 on the Strategy Room fleets tab, but check the console if there are any errors? thanks~

**Comment by Nilvaren** [comment]
Umm there's 'Uncaught TypeError: Cannot read property 'api_id' of undefined' error.
Here's the screenshot http://gyazo.com/51775f416a499ee8352cf21d5a227100. Thanks before c:

**Comment by dragonjet** [comment]
ah thank you for this~ I'm pushing a fix for this now. It happens when you open Fleets tab when there are no ships saved on local (which should be done by the panel).

The fix will include a message box that will say "*Unable to load your ship list.*" instead of a silent error.

**Comment by Nilvaren** [comment]
Thanks now it's perfectly clickable c:
