### ISSUE TITLE
Mostly blank pages in strategy room.

### ISSUE THREAD

**Issue by Horadrimus** [dragonjet/KC3Kai#469]
After updating KC3 to 13.1 
Strategy room shows blank pages on all pages but construction

**Comment by dragonjet** [comment]
This is fixed on a06387a59362bffbf1157c68aa41123733ccbaf1 and is processing on the webstore

**Comment by bamboo3250** [comment]
How come we didn't get this issue in developer mode? Is there any way to test the webstore version before it gets released to other players?

**Comment by ReiFan49** [comment]
sounds like we **did not need to check Gruntfile.js** while the webstore **does**.

**Comment by dragonjet** [comment]
yep, expected this to happen since the importing and packing of assets is still widely untested. It's actually the first time we release via the grunt build so it's fine.
