### ISSUE TITLE
Strategy Room not loading any stats

### ISSUE THREAD

**Issue by Asyrus** [dragonjet/KC3Kai#47]
No tab is selectable and there are no information except my name. F12 Console shows me this error log:

Uncaught ReferenceError: ip is not defined                                  Meta.js:63

KC3.Meta.serverByNum @ Meta.js:63
TabHome.show @ TabHome.js:15
$.ajax.success @ strategy.js:67n.
Callbacks.j @ jquery-2.1.3.min.js:1
n.Callbacks.k.fireWith @ jquery-2.1.3.min.js:1
x @ jquery-2.1.3.min.js:3
n.ajaxTransport.k.cors.a.crossDomain.send.b @ jquery-2.1.3.min.js:3

also, dont know if this is also part of the problem, the gamescreen console shows me an error too:

GET http://203.104.209.7/gadget/script/jquery.min.map 404 (Not Found)                  jquery.min.map:1

**Comment by dragonjet** [comment]
Hi, this is a problem with **Saiki Bay Anchorage**

Refer to: http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-176.189.255.76-20150506023857?permalink=246763#comm-246763
