### ISSUE TITLE
[Suggestion] Gained Experience Relocation

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#473]
As for current version, the total experience gained from each sortie or pvp is located under the total required exp to the next level:
![screen shot 2015-08-04 at 06 46 51](https://cloud.githubusercontent.com/assets/13522800/9048521/c899c6fa-3a74-11e5-9d10-e185852c29ad.png)

However, having three numbers (required exp, gained exp, max eq slot) stacking up without any space looks too cramped over there. Therefore, I suggest to relocate the gained exp numbers, to the space above the total required exp, since not a lot of player who will have a name too long that would interfere with the number being there.

ps: About the max ship slot on my screenshot, I was late on loading the Panel, so the max slot was not updated to its actual amount, which supposed to be 240. Please disregard it.

**Comment by dragonjet** [comment]
tbh I haven't followed the HQ exp enhancements earlier, I know @ReiFan49 added an option to switch between which of the exp values will show, so I guess we don't need the -75 below it, since it's the same as switching into "total gained" from settings?

**Comment by bamboo3250** [comment]
I think it's still useful to know how many exp we get in the sortie. Moving above seems better to me.

**Comment by ReiFan49** [comment]
sounds like this?

**16 px from top (tested with 12 full-width characters)**
![image](https://cloud.githubusercontent.com/assets/9847780/9108697/181ba2b6-3c5a-11e5-8324-8ab550f6c9c5.png)
