### ISSUE TITLE
[Bug] char for Kai in v13.2 becomes gibberish

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#474]
Windows 7 SP1, latest Chrome Portable version, Could view Hanzi just fine, but...

![snip](https://cloud.githubusercontent.com/assets/12930396/9051104/8b8a9a0a-3a88-11e5-836d-3fd5f686c8a3.png)

**Comment by dragonjet** [comment]
yep, everyone has that, Chrome doesn't recognize unicode characters on the panel tabs. will switch it back to just "KanColle" next ver

btw what's Hanzi? if it's also a unicode tab name, we could probably check how they did it

**Comment by LostLogia4** [comment]
@dragonjet Hanzi literally means "Han character", It's the Chinese's term for kanji (Japanese term) and hanja (Korean term), referring to the exact same calligraphy that is used for Chinese writings.
