### ISSUE TITLE
PvP only shows first opponent ship

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#476]
Found something in PvP battles. Battle Mode panel only shows the enemy flagship.

* http://i.imgur.com/kB9IAUK.jpg
* http://i.imgur.com/H2pKvRv.jpg
* http://i.imgur.com/jOI6dOG.jpg

Normal sorties seem OK so far. Been subcheesing 2-3 and 1-2 for dailies and weeklies.

Using version 13.2.

reported by [84.90.161.45](http://kancolle.wikia.com/wiki/User_blog_comment:Dragonjet/KC3%E6%94%B9/@comment-84.90.161.45-20150803205922?permalink=293441#comm-293441)

**Comment by bamboo3250** [comment]
I get the problem, will push the fix in a few minutes after finishing testing.

**Comment by LostLogia4** [comment]
In vertical mode it only shows the first 3 opponent ships iirc.
