### ISSUE TITLE
Repair Ship Notification Text

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#48]
I'm a grammar Nazi. It says something like !-19 is out of their repair docks.

Change 'their' to 'her' only one girl comes out of the dock and also all the ships are girls. :V

Also change docks to dock since you only use on dock per ship .:V

**Comment by dragonjet** [comment]
lol thanks for noticing this, the actual text was:

" is out of *ther* repair docks!"

I'm prone to typo, so thanks~
