### ISSUE TITLE
battle prediction not updated for night battle

### ISSUE THREAD

**Issue by dustfan** [dragonjet/KC3Kai#482]
i encountered this.. i thought i won't have to waste a bucket for this run..
![bug](https://cloud.githubusercontent.com/assets/12269598/9075119/ca9951aa-3b4b-11e5-8c78-0e652b1be10d.png)

**Comment by bamboo3250** [comment]
Oh is it Boss node 3-5? I am about to test it now.

**Comment by ethrundr** [comment]
to add details, Night Battle predictions only update the enemy that sink during the battle, but not our ship's HP bar, and this is applied to every map, including PvP.

**Comment by bamboo3250** [comment]
That's right. I forgot to copy the code to update our ships' HP when going to night battle. The pull request should fix that now. And the PvP is intended not to update in the night battle because the code to handle that hasn't been done yet. Probably it'll be fixed in the near future.
