### ISSUE TITLE
[Bug] With an easy reason but easy fix I hope

### ISSUE THREAD

**Issue by CardinalSan** [dragonjet/KC3Kai#488]
The Prediction if the enemy abyssals are destroyed does not count the ones support expeditions had killed. That's all, fix it or not I'm fine with it.

**Comment by NicolaosGreene** [comment]
Isn't this the same as #485?

**Comment by LostLogia4** [comment]
One thing I need to tell you though, bug reports should have a descriptive title for this issue like "Battle Prediction doesn't predict support expeditions" instead of a half-hearted title since the devs simply fixes them whenever they would anyway.

**Comment by dragonjet** [comment]
tbh I was confuzzled at first when I first saw on notifications but i think we can let this one pass, gave me a bit of giggle inside. I am able to edit the issue titles anyways. seems @CardinalSan is new on github as well (signed up today) so it's understood. i also do hope that next report titles would be relevant tho :laughing: thanks for reporting~
