### ISSUE TITLE
Clear new equipment preview when development is unsuccessful

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#492]
If you turn away to look at another tab, say, while you are making equipments, it's a bit difficult to tell whether the contents of the new equipment preview are for the current attempt or the last successful one.  Granted, you could just wait a few seconds to see the penguin but that rather defeats the purpose of having the equipment preview eh?

**Comment by bcc32** [comment]
Actually just reading the source code I found you could close the CraftGear box by clicking on it.  Still a suggestion though.

**Comment by dragonjet** [comment]
gotcha :+1:

**Comment by LostLogia4** [comment]
Or better yet, just display a "penguin" icon with "Equipment crafting failed" notification for a few seconds before it clears off.

**Comment by bamboo3250** [comment]
For this issue, I would go for "display penguin icon with `Equipment crafting failed` text and leave it for users to close it by themselves"
