### ISSUE TITLE
Cannot click the buttons in strategy room

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#50]
For some reason, the buttons seem to do nothing on the Strategy Room for me.
As in, I click the Ships button and it does not show the Ships panel for me, stays on the index panel.

I asked a friend to test it and he says it works for him.

I see nothing on the F12 console when I click a button, but I do get this when the Strategy Room page loads:

Uncaught ReferenceError: ip is not definedKC3.Meta.serverByNum @ Meta.js:63TabHome.show @ TabHome.js:15$.ajax.success @ strategy.js:67n.Callbacks.j @ jquery-2.1.3.min.js:1n.Callbacks.k.fireWith @ jquery-2.1.3.min.js:1x @ jquery-2.1.3.min.js:3n.ajaxTransport.k.cors.a.crossDomain.send.b @ jquery-2.1.3.min.js:3

EDIT 1 - I just now noticed the home screen is also completely blank; I believe I saw more people commenting on this issue, and on how it worked before last update. I also read your reply regarding the server not being defined, I'm not sure on what server I play, I'd be glad to help if you can tell me how to get a meaningful value for you on this. I think the server I play on has been around for a while, I joined KC about 2 months ago I believe;
EDIT 2 - just checked an old API link I generated for this one and it is the same IP that the guy posted on the wiki comments aka 203.104.209.55
I believe this issue will already get fixed then

**Comment by dragonjet** [comment]
Fixed as of either d5bf1e0455beb430e359ff615234ef3a4fda0fed or 5027d0dead529f341769ef1182aabb966526f46d
