### ISSUE TITLE
Sortie history is not showing dead-end nodes

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#503]
I was doing 5-5 and have hit a rather large number of the dead ends this month and deiced to look at the history to check to see how many, but when I went back to look none of them were recored there. There were just 2-5-17 paths even though there should have been several 2-5-17-13 paths. I suspect this to be some sort of bug in how it is recording the data for dead end nodes.

**Comment by dragonjet** [comment]
Ah this is intended, only **battle** nodes are included in sortie history. Even resource nodes (most noticable on 2-3 runs) are not recorded as well. Will mark this as won't fix
