### ISSUE TITLE
PVP Yasen Battle Prediction does not work

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#504]
Title says all.

**Comment by ethrundr** [comment]
@ReiFan49 it's your part, I believe?

**Comment by ReiFan49** [comment]
the current one only take care the **current PvP node**, but its node is inaccessible for the yasen check on pvp because of that,
fixing this (while waiting to test whether its already OK or NG though)

**Comment by dragonjet** [comment]
oh my, the "PvP Practice Battle" box is overflowing :v

**Comment by ethrundr** [comment]
lol :laughing: 
how about to leave it just like that?
