### ISSUE TITLE
chrome.cookies not available in chrome v44 (stable) so API Link mode cannot active

### ISSUE THREAD

**Issue by Diablohu** [dragonjet/KC3Kai#510]
In the latest stable build of Chrome (44.0.2403.130), the `chrome.cookies` method is not available.

As result, both `Play via API Link` and `Refresh API Link` are not available, for both functions need the method.

**Comment by dragonjet** [comment]
oh my truly? did they remove it?

**Comment by Diablohu** [comment]
maybe you are right

I found that `chrome.cookies` is available in web store version...

**Comment by dragonjet** [comment]
Updated cookie method: 12e4b634f9e06f65a1c90f14774384103aba6c15
* Remove cookie writing for "**Play via api link**" since it doesn't direct to DMM
* Change back "**Refresh API Link**" to direct write
* "**Play via DMM**" cookie writing moved from the menu to `web.js` "Start Game" button
