### ISSUE TITLE
Clean-up unused settings

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#515]
I wanted to clean up unused settings, and would like to ask if anyone is using these settings?

* `pan_size`
  * @bamboo3250 
  * (Panel Size) has small / big, under Panel section

* `info_delta`
  * @ReiFan49 
  * Says "hidden and false by default. { altering the default feature of HQ update }"
  * we now have `hqExpDetail` so I think we don't need the `info_delta`?

Also I disabled most of the settings under "DMM Gameplay", only retaining "Force Cookie hack". Will re-enable when we do implement DMM script injection.

**Comment by bamboo3250** [comment]
The panel size is for 300px/420px choice in Vertical Layout. If we remove that, the user has to select the size of Vertical Layout every time he reloads the page.

**Comment by dragonjet** [comment]
ah I see, we'll keep it then

**Comment by ReiFan49** [comment]
after discussing with @ethrundr,
and rethinking back about two issues (that i've posted) regarding this, i guess i should put `info_delta` onto my private branc---- (like my ritou boss compo lol)

oh damn, i hope i could make a branch about those two-to-three thingy that might be not-for-pull lol,

**Comment by dragonjet** [comment]
ahh, though for `info_delta`, just wanna know its purpose, if it is the same as `hqExpDetail` or does it involve another feature?

**Comment by ReiFan49** [comment]
uh oh sorry,

its not.
but the red bar that acts as delta given along the blue bar experience bar on battle mode
```
|||||||||----- (blue bar)
|||||||||||--- (red bar, underlay the blue bar)
```
the blue bar / current player HQ exp is not updated, but its gained experience is updated as always,
and forces the blue bar to reset to 0% if the red bar at least reaches 100%,

using info_delta, is not an effective thing for really high level admirals (100k exp requirement above)

**Comment by dragonjet** [comment]
ahh so delta involves the UI of sorts. alright then. I won't interfere with those settings xD
