### ISSUE TITLE
[Suggestion] Predicition: Night Battle HP Update

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#518]
As for now, when entering the night battle, the one that being updated is the final HP on the below part of the kanmusu HP.

Why not we do this: update the actual HP (on the upper part) using the final value from the day battle, and the prediction below stay as is. This way we can track and guess the final HP based on the difference between the end of day battle and the prediction for night battle one?

Maybe @ReiFan49 can help explain the basic idea?

**Comment by c933103** [comment]
how about 3 parts?

**Comment by ReiFan49** [comment]
`api_data` on night battle,
`nowhps` on each ship is based `afterHp` of day battle.

so the afterHp that reflects the night battle result, the currentHp reflects the day battle result.

**Comment by dragonjet** [comment]
yep @ReiFan49 is right. though I'm not sure where this falls, if still under @Javran's script, or the calculation just needs to be re-triggered when entering night phase

**Comment by Javran** [comment]
Night battle has its own "nowhps" ([example](https://github.com/Javran/purescript-kancolle-helpers/blob/master/test/BattleData.js#L110)), my script uses that field for both normal and night battles, accumulating damage through aerial combat, shelling, torpedo stages and remove them from nowhps.

**Comment by dragonjet** [comment]
hm wait, I remember a recent pull that deals with this or am I confusing it with something else
