### ISSUE TITLE
Sortie History: Make room for a menu with 7 maps

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#519]
upcoming event has 7 maps. right now it fits only 6.

**Comment by ethrundr** [comment]
how about adding new tab to specifically store all the event sortie histories?

**Comment by dragonjet** [comment]
hm wait, actually before all this, I just notice we actually don't have sortie history for events :open_mouth: right now we only have menus for the 6 worlds

**Comment by McDohl** [comment]
yeah DJ, event's map history is high priority

**Comment by dragonjet** [comment]
oh God help us
