### ISSUE TITLE
B47 Quest Misleading

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#523]
It says Abukuma. You need Abukuma Kai Ni for the quest to count.

**Comment by ethrundr** [comment]
it's the second Abukuma sortie quest, am I right?

**Comment by McDohl** [comment]
wait, let me check it

**Comment by SanaNoHana** [comment]
Oh shit. I derped. Nevermind! Close htis xD

**Comment by dragonjet** [comment]
XD
