### ISSUE TITLE
Undefined selectedFleet in Natsuiro Listener 

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#526]
I was trying to use Natsuiro theme at the latest commit.

![screen shot 2015-08-09 at 3 34 03 pm](https://cloud.githubusercontent.com/assets/8078323/9153948/46fa789c-3eac-11e5-94c4-a5af3b7e28cd.png)

**Comment by ethrundr** [comment]
ah this happened to me as well, and the Inspection screen stays in the "Waiting" mode

**Comment by bamboo3250** [comment]
This issue and #527 actually are the same bug report, just different description. :sparkles:

**Comment by dragonjet** [comment]
ah I merged back `Listeners.js` to the main script file xD
figured this was more trouble than I hoped for so... kek
will push later

**Comment by ethrundr** [comment]
@bamboo3250 oh lol XD

**Comment by dragonjet** [comment]
can check latest push if still error? thanks :)

**Comment by bamboo3250** [comment]
@dragonjet it works :+1:

**Comment by dragonjet** [comment]
aye thnx
