### ISSUE TITLE
[Bug] Natsuiro Theme: Auto-load won't work

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#527]
When the theme was set to the `Natsuiro`, navigating to the extension mainpage (`chrome-extension://mpbmijbpaidcombbkjalbfloocoopafh/pages/game/web.html`) and loading the Inspection tab (in this case, the `DevKC3Kai`) won't do the auto load as usual in the `Default` theme. It stay as it is.

In `Natsuiro` Theme:
![screen shot 2015-08-09 at 17 16 29](https://cloud.githubusercontent.com/assets/13522800/9154080/e1a0edf0-3eba-11e5-973e-12c1882a71b0.png)

In `Default` Theme:
![screen shot 2015-08-09 at 17 19 43](https://cloud.githubusercontent.com/assets/13522800/9154081/e537c790-3eba-11e5-8e53-54e04cf612ed.png)

**Comment by dragonjet** [comment]
can check latest push if still error? thanks :)

**Comment by dragonjet** [comment]
checked on my side, works now
