### ISSUE TITLE
[Bug] Night Battle: Just Another Bug

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#529]
Night Battle node detection is not working again.....
Might test it later on other night battle nodes~
![screen shot 2015-08-09 at 17 42 36](https://cloud.githubusercontent.com/assets/13522800/9154169/340b17f2-3ebe-11e5-98fa-37087c7ce74c.png)

edit: Day-to-Night battle works just fine.

**Comment by bamboo3250** [comment]
5-4 again... ; ; Do you know any night battle node not from 5-4 or above? @ethrundr

**Comment by ethrundr** [comment]
@bamboo3250  yes I do have: 5-3 also NOT working when battle start from night
![screen shot 2015-08-09 at 17 50 12](https://cloud.githubusercontent.com/assets/13522800/9154196/2701c53c-3ebf-11e5-858f-56e56f13fb2f.png)

**Comment by bamboo3250** [comment]
That's right. For some reason, night battle is considered as day battle and it tried to read air battle data, which is only available for day battle, and it caused that undefined error.

**Comment by dragonjet** [comment]
lol

https://github.com/dragonjet/KC3Kai/wiki/Changelog%3A-Version-15#fixes

**Comment by bamboo3250** [comment]
@dragonjet ah, I forgot to mention this. `"Fighting" changed to "Day Battle"`, it will change to "Night Battle" if the we engage battle at night since the commit 102a1d3

**Comment by McDohl** [comment]
@bamboo3250 2-5 north route and 4-5 south route also had night battle node :smirk: . anyway thanks for the fix

**Comment by dragonjet** [comment]
ah its alright, i dont think anyone will report that xD

**Comment by ethrundr** [comment]
just read the changelog and lol'ed really hard XD
