### ISSUE TITLE
planes proficiency system.

### ISSUE THREAD

**Issue by c933103** [dragonjet/KC3Kai#533]
Report from real life event at yokohama stated that it would be the new system to be implement. Please think about how to present and calculate them and what would be affected by it.

**Comment by dragonjet** [comment]
hmm i think this will be included on `slotitem` master, together with the akashi remodel and itemlock variables.

although akashi upgrade is already called `api_level`

since planes cannot be upgraded on akashi, maybe they will use the same `api_level` for the new system

all my speculations tho xD

**Comment by nicky008** [comment]
Or waiting more data about new API keys... :3

**Comment by dragonjet** [comment]
slotitem will contain `api_alv` if it's an air-valid equipment, and the value is integer. I've seen 1 at least, no 0 yet

I'm not sure how to fit that onto our equipment icons now at the panel

**Comment by bamboo3250** [comment]
I think it's `level`, which can have value above 1.

**Comment by dragonjet** [comment]
I've seen it too, but for us maybe we can just put the number in, no need for those lines xD
I'm actually exited, doing this right now for natsuiro, very difficult to fit in tho.

on the side, we should also have note somewhere we also need to have it on the strategy room equip list :open_mouth:
