### ISSUE TITLE
[Natsuiro UI] All Images and Icons in the Battle Tab still has no Tooltips

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#547]
The title already explain everything :smile: 

edit: It seems that the drop ship face is not appearing yet as well... still working on it?

**Comment by dragonjet** [comment]
wait, as I can see expedition, repair and construction icons have tooltips
equipment on the shiplist has tooltip
quest description has tooltip, and tracker also has tooltip with bug on #550

these are the ones without yet:
* flags icon tooltip for support, night, rating, drop

**Comment by dragonjet** [comment]
closed by dbbc6bb5a97c75019d46f9688049643b90876606
