### ISSUE TITLE
[Natsuiro UI] Basic and Battle Tab Switching

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#548]
On Natsuiro, when we start a sortie the tabs on the left automatically switched into "Battle" tab, don't matter where it was at that time.

However, when the sortie ends, the tab stays at "Battle" tab, which supposedly switched back to the "Basic" tab which display the info needed while in the Homeport.

**Comment by dragonjet** [comment]
oops, didnt close automatically by commit dbbc6bb5a97c75019d46f9688049643b90876606
