### ISSUE TITLE
[Wiki] Clarification on regular maps: sortie history

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#553]
It may be a good idea to mention in the section for sortie history that it does not display resource or dead end nodes for anyone who becomes confused by that fact.

**Comment by Crazyteitoku** [comment]
Thanks for the report, been busy elsewhere and so I got around to dealing with it. The wiki page should be updated however I think those sortie history page needs an overhaul considering it was from the v009 days of KC3 Kai. :laughing:
