### ISSUE TITLE
[Wiki] Punctuation and consistency on the developers notes for Strategy Room: Construction, Strategy Room: Crafting, and Strategy Room: LSC

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#554]
In the following line of the developer's notes there appear to be some errors: "Color codes are Hex color codes and they are as follows: #c1ffc1, #dfd7b3 , #CCCCCC , #FFDCA8". First, there is inconsistency in the capitalization of your Hex codes, which I know does nothing to effect how they function but it looks cleaner when they are uniform. I would recommend making them all capital to be consistent with W3schools standards on HTML codes, but there is not a hard or fast rule for this. Second, the commas should come immediately after the codes rather than being spaced 1 after. Finally there should be an and after #CCCCCC's comma. Based on my suggestions I would recommend using the following as your line: "Color codes are Hex color codes and they are as follows: #C1FFC1, #DFD7B3, #CCCCCC, and #FFDCA8"

**Comment by nicky008** [comment]
I personally prefer capital letter for these codes though.

**Comment by NicolaosGreene** [comment]
Here I was talking just about the wiki.

**Comment by NicolaosGreene** [comment]
Hadn't looked at it yet when I wrote this issue, but what I wrote here also applies to the LSC page as well since it appears to have the same notes as the other two pages

**Comment by Crazyteitoku** [comment]
@NicolaosGreene Thanks for the report I have edited the relevant wiki pages for now. :laughing:

**Comment by NicolaosGreene** [comment]
Alright closing it then
