### ISSUE TITLE
[Suggestion] Hide battle result

### ISSUE THREAD

**Issue by Yukinyaa** [dragonjet/KC3Kai#561]
Some fun of kancolle comes from randomness.
showing battle result makes it less...random.
but since we need to check status of our girls' status, it's impossible not to check battle mode window.

So, some settings for this can be made.

(P.S. low-priority Suggestion.)

**Comment by bamboo3250** [comment]
The battle result can be switched of by unchecking the Battle Prediction option in Settings page.

**Comment by Yukinyaa** [comment]
k sry it was in korean so i was bit confused with other setting
