### ISSUE TITLE
Combined fleet for Horizontal (Default Theme)

### ISSUE THREAD

**Issue by SanaNoHana** [dragonjet/KC3Kai#566]
http://s10.postimg.org/47b3rfljd/KC3_Kai_Combined_Fleet.png

Haiiii

**Comment by bamboo3250** [comment]
Combined Fleet is not supported in Horizontal Layout. You can use Vertical Layout of Default theme or Natsuiro theme instead.

**Comment by dragonjet** [comment]
yea, people had been reporting that. I always just ask them to try out natsuiro theme

**Comment by dragonjet** [comment]
As of 94cdf14ce2cf1659de9efd0bf211c10a9defa25e Combined Mode is completely disabled for horizontal in default theme
