### ISSUE TITLE
Uncaught ReferenceError: KC3Panel is not defined

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#577]
The ship list suddenly disappeared when engaging battle.

![screen shot 2015-08-11 at 4 56 22 pm](https://cloud.githubusercontent.com/assets/8078323/9193952/387b5fa8-404a-11e5-87ac-d9b8cb168155.png)
![screen shot 2015-08-11 at 4 56 03 pm](https://cloud.githubusercontent.com/assets/8078323/9193953/391e3200-404a-11e5-997f-0337df91ba85.png)

**Comment by ethrundr** [comment]
adding details, this happened when one of the our ship has HP below 0 (instant-taiha), and still non-sink-able (from chuuha condition or above):
![screen shot 2015-08-11 at 19 39 28](https://cloud.githubusercontent.com/assets/13522800/9195831/d3166d12-4060-11e5-988f-e25744ff653f.png)

**Comment by dragonjet** [comment]
ah that's true. and there's not alot reporting this since it requires stamps to be enabled which is by default off.

though I've seen it many times already but what is `isSunkable` variable? xD

**Comment by ReiFan49** [comment]
isSunkable only Sortie / PvP marker,
which differentiates the way of the Stamp shows out.

**Comment by dragonjet** [comment]
ahh I see, for now in natsuiro I will default it to "knocked out", means PvP

**Comment by dragonjet** [comment]
wait, how were you guys able to see this? you all went kuso? XD XD

**Comment by bamboo3250** [comment]
@dragonjet lol, I don't dare to do that xD I found out the cause in this afternoon. It is because our Damage Calculation keeps redirect the damage on the escort fleet to the main fleet so the HP sometimes  become negative. Then that issues happens.

**Comment by ethrundr** [comment]
@dragonjet well on the calculation, if one ship get damaged more than her HP, the prediction will shows negative values.

On the panel, rather than set it back to only 1 HP remaining (which the game actually do upon getting final negative result and the status is not sunkable yet: either in PvP, or not yet reached Taiha condition previously), it goes boom! :laughing:
