### ISSUE TITLE
Combined Fleet Prediction

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#578]
Title explains everything.

**Comment by ReiFan49** [comment]
wip on #461

**Comment by ethrundr** [comment]
ah haven't read that one :laughing:

**Comment by dragonjet** [comment]
ah this is alright, most of the items being tracked on #461 have their own threads, and this one can be the dedicated one for the combined fleet indexing

**Comment by ReiFan49** [comment]
sad that the "digital sutra" is already linkified on the main thread (too lazy too open with this slow connection :sob: )

**Comment by dragonjet** [comment]
lol I didn't even know what sutra was so I kept quiet :laughing:

**Comment by LostLogia4** [comment]
@ReiFan49 Sorry for that... it's to keep the thread tidy enough to keep up with the progress.
If we could've make a collapsible spoiler boxes here in github, then we won't have to linkify it...

**Comment by ReiFan49** [comment]
@LostLogia4 nevermind lol, what i really think is.. "move the sutra to this one" :laughing: 
specific thread sounds *OK* while the general/large thread sounds *NG*.

ps: it's possible to request it to the github to make a spoiler boxes (iirc, because skimmed most of the MDing part)

**Comment by LostLogia4** [comment]
"request it to the github"? You mean asking the github devs to introduce collapsible boxes?

**Comment by ReiFan49** [comment]
after checking around, maybe linkify it for the best solution...

**Comment by dragonjet** [comment]
@Javran did multiple revisions done on prediction since then.
Will close this issue now, and probably just re-open in case there are still reports after v17 release
