### ISSUE TITLE
Battle conditions reminder

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#58]
Expanding on the battle prediction proposed before, I'd like to suggest something that might be useful too to those that do not wish to see the prediction itself.
There could be a panel that would be shown during battles to view those parameters that are only shown briefly at the start of the battle, in case I miss it because I wasn't looking at the game, for example. It could show the engagement type (the green/red T thing etc), which side got air superiority, and that scout thing that happens which is said to do stuff, but I have no clue what it does (even though it is on the wiki lol).

**Comment by bamboo3250** [comment]
I have a liking to this suggestion :+1: Probably this is what I will do next.

**Comment by bamboo3250** [comment]
@dragonjet please close this issue. I forgot to put "fix" in the comment.

**Comment by bamboo3250** [comment]
@AlanSchaeffer I added the feature u requested here #148

**Comment by dragonjet** [comment]
will need to reimport for v010

**Comment by bamboo3250** [comment]
okay, no problem :+1:

**Comment by dragonjet** [comment]
by the way, we will have a special interface for battle mode, when user starts a sortie. see new issues I made under horizontal battle mode.

The compass and enemy list will not be popup boxes but will have their own always-present box in the dashboard. though I still haven't started on this "battle mode". I'll notify you again on this thread when the box is ready to be filled.

**Comment by dragonjet** [comment]
Forgot to close but has been addressed on
9d3e2b27b5902533c5f316e326ca70515e74cd69
f7ec1dc38d95d5503550eb25a7a4eaf6f52c9af7
5e50f5c0edbb3e236e233fece35c11553b281f06
