### ISSUE TITLE
Shiplocking Planner

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#580]
New tab on strategy room under fleet
* 5 boxes of different colors
* List of ships under them (by shiptype / has level indicator)
* Can drag ships from the bottom to a specific color box
* Ship will stay on the box, will become face icon only instead of original box (no more level indicator)
* It will be saved and remembered so can be revisited

* When visited the first time, and there are ships already locked on data, will automatically move them to correct boxes, and be marked with a padlock to signify this ship is already locked in-game

![shiplock_planner](https://cloud.githubusercontent.com/assets/557312/9196350/2032d24c-405d-11e5-881d-a838894f7a78.png)

**Comment by ethrundr** [comment]
@dragonjet those ships that already locked in-game is also locked in this feature: user will be unable to move them around.

also, if possible, add some small color indicator at the bottom-right of each ship's icon in the panel, to indicate their locks. this will not bring extra information to the user, but just to indicate that this ship is already locked for certain event maps.

**Comment by dragonjet** [comment]
on panel?

hmm I'm thinking the shipface icon area is alrady cramped, now that we'll also add the 5th equipment near the face XD

what if just the icon border color?

**Comment by dragonjet** [comment]
Complete as of 9fbddeafb385356cb6d8f11ebe95de8e85d54f56
