### ISSUE TITLE
Reinforcement Expansion: Show 5th slot

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#581]
With the introduction of [Reinforcement Expansion](http://kancolle.wikia.com/wiki/Reinforcement_Expansion), we also need to show the item on the shipgirl's 5th slot. This will not be added to equipment list with capacity, but recommended beside the face icon of the ship girl. Like the expedition number on the timer, overlaid on the bottom-right of the face.

**Problem**: who has data on this? xD

right now ships gave 5 elements on their `api_slot` parameter, but right now its always `0` for me since I haven't used the new mechanic yet. Will it be a number? The slotitem_id? or the icon_id?

**Comment by ReiFan49** [comment]
so basically this one won't be included in strategy/fleets tab?

**Comment by dragonjet** [comment]
ah true, we also need to have it there xD
with strategy room in mind, on shiplist, we should also add another column

**Comment by bamboo3250** [comment]
Ehhh I have 2 Reinforcement Expansion so probably I can collect the data about it. But now the problem is "__who should I give to to?__" xD

**Comment by ReiFan49** [comment]
personally, i'll give them to the one that easily targeted by RNG lol..

RJ and Jun'you is the main target, and never forget the last event, 2 damecon consumed of 3 taiha run on boss node.

**Comment by bamboo3250** [comment]
`/kcsapi/api_get_member/ship3` <= this weird API appears right after I put Damecon to my Akizuki's 5th slot
http://pastebin.com/HA1et5QN

**Comment by dragonjet** [comment]
wow whats `api_slot_ex`

**Comment by dragonjet** [comment]
alright so now we confirm that

`api_slot_ex` contains the "`rosterId`" of the equipment. Not the `icon_id`, not the `slotitem_id`

**Comment by bamboo3250** [comment]
yep, that's probable the item ID of one of my Damecon, the `api_slot` still doesn't change.

**Comment by dragonjet** [comment]
can check if an icon shows up near the face for natsuiro theme?
I still don't have any reinforcement expansion xD

**Comment by bamboo3250** [comment]
I just commented on the code. After that fix, it will work.

**Comment by ethrundr** [comment]
anyway, anyone has the screenshot on how this will appear in the Strategy Room and Panel?
since I haven't used any of my Reinforcement yet XD

**Comment by dragonjet** [comment]
I saw a screenshot on Facebook, and it works well, I haven't tried it myself though xD

**Comment by ethrundr** [comment]
@dragonjet mind bringing it here? XD

**Comment by dragonjet** [comment]
ah I lost it from the tides of event screenshots on the feed.
maybe someone here already used the item XD

**Comment by ethrundr** [comment]
it seems @bamboo3250 already used it, seeing from the comment above...
mind sharing with us, bamboo? XD

**Comment by McDohl** [comment]
I used mine on accident (staring at Akashi), can test it for you

**Comment by bamboo3250** [comment]
I used on Akizuki. Here is on the panel. There is no difference in the strategy room though xD

![screen shot 2015-08-21 at 6 16 14 pm](https://cloud.githubusercontent.com/assets/8078323/9406204/ee03e6d6-4830-11e5-8b60-0527ece4a01a.png)

**Comment by McDohl** [comment]
![image](https://cloud.githubusercontent.com/assets/13024936/9406224/198b0a1e-4831-11e5-9af6-061a1635f80b.png)
no visual change on strat room

**Comment by ethrundr** [comment]
@McDohl so... Akashi is using her own fairy form.... XD
anyway thanks for both of you~
