### ISSUE TITLE
Natsuiro Tasks

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#582]
:white_check_mark: #581 Show 5th slot
:white_check_mark: #533 Aircraft Level on Panel
:white_check_mark: #577 JS bug
:white_check_mark: #587 Enemy Armor
:white_check_mark: #590 Better appearance of killed abyssals
:white_check_mark: #604 not readable resource nodes
:white_check_mark: #609 Night battle enemy HP bars
:white_check_mark: #35 Do not include orange/red on highest akashi
:white_check_mark: #36 Do not show akashi time if orange/red
:white_check_mark: Basic Fleet indicators
:white_check_mark: eLoS toggle
:white_check_mark: Crafting results
:white_check_mark: HQ exp toggle

#### From thread #684
:black_medium_square: #337 Morale Timers
:black_medium_square: Color Schemes
:black_medium_square: Include 420px version in vertical
:black_medium_square: Switch the between day battle and night battle background
:black_medium_square: Expedition helper to activity tabs
:black_medium_square: Level tooltip on combined ship boxes

**Comment by LostLogia4** [comment]
You might want to look at Issue #587, cuz I've got a suggestion here.

**Comment by ReiFan49** [comment]
nah, it feels empty without looking at exp gained during sortie lol

**Comment by ReiFan49** [comment]
![image](https://cloud.githubusercontent.com/assets/9847780/9377438/443c7ae8-4743-11e5-883d-73460bba9ab5.png)
looks hard for the toggle huh ._.)
