### ISSUE TITLE
[Stretegy Room][Bug] Spring 2015: Past-Event Sortie History

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#583]
Instead of showing empty history, the E2 and E3 on Spring 2015 History shows sortie history from 2-2 and 2-3:
![screen shot 2015-08-11 at 23 18 39](https://cloud.githubusercontent.com/assets/13522800/9199802/7ea70f7e-407f-11e5-99c7-ada32ae281bc.png)
![screen shot 2015-08-11 at 23 20 06](https://cloud.githubusercontent.com/assets/13522800/9199805/89ae102a-407f-11e5-88ab-eab06231e9b0.png)

Not to mention, these two pages also have error that only shows one sortie per page.

**Comment by ReiFan49** [comment]
i hope i still have these to check it around ._.)
twice corrupting KC3Kai these times makes me sad ._.)

**Comment by ReiFan49** [comment]
```HTML
	<div class="world_box hover" data-world_num="2">
		<div class="world_icon"></div>
		<div class="world_text">Spring 2015</div>
	</div>
	<div class="world_box hover active" data-world_num="31">
		<div class="world_icon"></div>
		<div class="world_text">Summer 2015</div>
	</div>
```
it's clear.

world-30 means previous event though... or not?

**Comment by ethrundr** [comment]
@ReiFan49 yes, it's 30

**Comment by dragonjet** [comment]
whoops ill fix that
