### ISSUE TITLE
Combined Fleet doesn't shows up well.

### ISSUE THREAD

**Issue by muazyusof** [dragonjet/KC3Kai#585]
when sortieing with combined fleet, it ended up showing 2 big blocks of colors.

![kc3kai](https://cloud.githubusercontent.com/assets/13151668/9201386/6792b766-407f-11e5-89ce-bb6fce09542a.jpg)

**Comment by bamboo3250** [comment]
Combined fleet in that layout is still a prototype. You'd better use Natsuiro theme or other layout instead.
