### ISSUE TITLE
[Suggestion] Add enemy flagship boss's armor stats.

### ISSUE THREAD

**Issue by LostLogia4** [dragonjet/KC3Kai#587]
Opened this thread in the wake of the Air Defense Princess created the necessity for this information.

According to what we have known thus far, AA Hime (Summer 2015 Event's final boss) has a whooping armor stat of 395, which may be reduced to manageable numbers (as low as 138) when certain conditions are met. While it is up to the frontliners to figure out the puzzle, it is a pretty good idea for us to know the armor value of the enemy flagship nonetheless.

**Comment by bamboo3250** [comment]
Is reducing abyssal's armor even possible? :open_mouth:

**Comment by LostLogia4** [comment]
Not during the battle itself. The Operation FS revolves around the puzzle of reducing the boss armor before it is actually fought.

**Comment by dragonjet** [comment]
how did they even know the boss stats? it is on battle data. coz I'm sure it was removed from master

**Comment by LostLogia4** [comment]
Not sure but there are in-game screenshots comments in "Air Defense Princess" entry in kancolle wiki.

**Comment by dragonjet** [comment]
I'm on my laptop now so I can't sortie, but I checked
`https://github.com/dragonjet/KC3Kai/blob/master/tests/responses/api_req_sortie/battle`

seems `api_eParam` on the battle data is the enemy's firepower, torp, aa, armor

**Comment by LostLogia4** [comment]
A business-use laptop, I surmise?
So that's where we'll be getting the battle data? Okay then...

**Comment by bamboo3250** [comment]
@dragonjet could you assign me this issue? I'll try to show enemy stats by the tooltip like I did with 4 tracking number of Bw1.

**Comment by dragonjet** [comment]
aw nej, can only assign collaborators on repo :cry:

**Comment by bamboo3250** [comment]
oh right, nvm then xD
