### ISSUE TITLE
a map filter for regular/event sortie map

### ISSUE THREAD

**Issue by dustfan** [dragonjet/KC3Kai#59]
this might seem not too important atm, but i'd like to request for this feature.

there are times when i forgot how many times i did 5-4 before the pvp reset, and also how many times i've reach 4-2's boss node to clear the weekly world 4 boss.. having this kind of feature in which you can just filter the sortie screen to only show my sortie data to a certain map would be really helpful to keep track of stuffs..

**Comment by dragonjet** [comment]
this would be resolved now on latest version?

**Comment by dustfan** [comment]
yes, thank you very much jet, it's done right when i was about to do ranking for next month. ^^

**Comment by dragonjet** [comment]
:+1:
