### ISSUE TITLE
[Suggestion] Killed Abyssals

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#590]
Like you can see here:
![screen shot 2015-08-12 at 02 55 15](https://cloud.githubusercontent.com/assets/13522800/9207203/145a4956-40a7-11e5-90e1-b8d09a68e14f.png)

While on the big image, determining between those two killed with the same alive counterpart is a bit difficult. Thus I'd like to suggest to make it more transparent, or add any details (like the red crosses in the default theme) to more emphasise that it was dead for good.

**Comment by dragonjet** [comment]
now looks like this

![ss 2015-08-13 at 07 30 56](https://cloud.githubusercontent.com/assets/557312/9248857/24c51f72-41f2-11e5-8f6c-d4a4e9223cb3.jpg)

**Comment by bamboo3250** [comment]
@dragonjet one problem. The sunk icon (even displayed or not displayed) covers the abyssal icon so that the tooltip cannot appear when we hover the mouse onto it.

**Comment by dragonjet** [comment]
aye, fixed

**Comment by bamboo3250** [comment]
thanks :sparkles:

**Comment by ethrundr** [comment]
lol I loved the sunk icon :sparkling_heart:
