### ISSUE TITLE
Combined Fleet Battle Prediction Bug

### ISSUE THREAD

**Issue by hbhbenny647** [dragonjet/KC3Kai#594]
![screenshot 16](https://cloud.githubusercontent.com/assets/13168067/9219267/92712612-4114-11e5-892f-caaa160db1d5.png)
![screenshot 17](https://cloud.githubusercontent.com/assets/13168067/9219268/92778778-4114-11e5-9071-df6fa3020b8e.png)
![screenshot 18](https://cloud.githubusercontent.com/assets/13168067/9219368/641302a8-4115-11e5-829f-fa0d03c7cd0a.png)
As you can see from these 2 pictures, the damage predictions shows on the wrong ship.

**Comment by alohadude3** [comment]
My guess on this is that the damage taken on your escort fleet seems to be added to your main fleet as opposed to your escort fleet.

**Comment by ethrundr** [comment]
@hbhbenny647 yes, the value is added to the main fleet. I remember this has been addressed somewhere before here..... lemme check it for a while....

**Comment by dragonjet** [comment]
to be tracked on #578
