### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#596]
Happened in 31-4, node E and G (yasen nodes):

31-4-E:
![screen shot 2015-08-12 at 21 07 16](https://cloud.githubusercontent.com/assets/13522800/9223587/6f0cff62-4136-11e5-90ae-6d6caad7b1ff.png)

31-4-G:
![screen shot 2015-08-12 at 21 08 32](https://cloud.githubusercontent.com/assets/13522800/9223591/73863572-4136-11e5-94eb-98ca2df68c17.png)

The battle prediction is not appearing for both party. Hopefully this issue is not a duplicate, since after short glance on newest opened issue, I cannot find the similar one.

I just updated my KC3kai to this commit: 6274c95

**Comment by bamboo3250** [comment]
This bug probably is related to the enemy stat tooltip I added a few hours ago. I'll push a fix for it soon.

**Comment by bamboo3250** [comment]
Oh wait, @ethrundr you are in E4 now? :scream:

**Comment by ethrundr** [comment]
@bamboo3250 yeps I'm on E4 now
though, I'm doing E3 in Medium and E4 now in easy :laughing:

**Comment by bamboo3250** [comment]
omg, now I know clearing this event in All Hard is impossible for most of players out there :scream:

**Comment by ethrundr** [comment]
well, 4 shiplocks and hime as each map bosses
not to mention their escorts are also bosses....

unless you have tons of reserves both in resources and buckets and dmmpoints
all hard is quite impossible for sure.....

**Comment by bamboo3250** [comment]
4 shiplocks is truly the real boss of this event, not RNG-sama nor the cat bomb. Next summer, I will bring 4 high-leveled KTKM-sama to a large-scale operation like this for sure :angry:

**Comment by ethrundr** [comment]
@bamboo3250 suddenly, the next summer map prohibits the use of CLTs :laughing: 
anyway, the fix is just merged, gonna pull it now, and test it~

**Comment by LostLogia4** [comment]
@bamboo3250 Couldn't agree more. The fleet locking system staring at me caused me to delay the sortie by 2 days.
I've personally raised 3 extra CLTs just in case this thing happens, and it has certainly paid off... well, until the last two map that discriminates against CLTs that is.

**Comment by ethrundr** [comment]
@LostLogia4 I even must sacrifices my habit of clearing all-hard due to shiplock, and pick easy for E4 E5 and E7 to avoid the locks.

sadly E6 still need to be done at least in medium for the remodel item :cry:

**Comment by LostLogia4** [comment]
@ethrundr Yeah. In this event we're fighting deep inside the Abyssal territory that gave us a massive fog of war. Not only do we have new and stronger versions of bosses, we couldn't even gather proper intels about them to work it out. The devs have certainly managed to flip us over over this. At least they've informed us about the large-scale event is one month away.

All said, I think I'm gonna get a PTSD over this event...

**Comment by ethrundr** [comment]
Testing Report:

While the enemy formation and prediction is loaded, the prediction for our side is still bugged. Should I keep it here, or make a new ticket? @bamboo3250 @dragonjet 

There is a new error generated as well: `Uncaught ReferenceError: container is not defined`

Here's the screenshot:

Node E:
![screen shot 2015-08-12 at 22 27 28](https://cloud.githubusercontent.com/assets/13522800/9225065/fc878780-4141-11e5-826b-8c396565e980.png)

Node G:
![screen shot 2015-08-12 at 22 28 26](https://cloud.githubusercontent.com/assets/13522800/9225079/152813cc-4142-11e5-93e0-ce49eec9ef27.png)

Btw bonus, E4 boss normal kill in easy mode is sure easy :laughing: 
Hopefully the final is not become far too different with this one....
![screen shot 2015-08-12 at 22 31 02](https://cloud.githubusercontent.com/assets/13522800/9225097/2e6815c6-4142-11e5-9411-9c6e128a413b.png)

**Comment by bamboo3250** [comment]
@ethrundr that error message is the same as #599 I created just now. They happen on different lines but are the same bug. Hopefully @dragonjet will clean it soon. And does the tooltip work properly now?

**Comment by ethrundr** [comment]
@bamboo3250 haven't test about the tooltip yet.
