### ISSUE TITLE
[Strategy Room][Bug] Summer 2015: E-2 and E-3 only show 1 sortie per page (Warning: Lot of Images Ahead)

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#597]
As the title say, history on E2 and E3 only show one sortie per run, as well as the "N" button is showing nothing:

E2 Page:
![screen shot 2015-08-12 at 21 22 00](https://cloud.githubusercontent.com/assets/13522800/9223810/7226cb36-4138-11e5-8f4c-8b6cd1e2628f.png)
![screen shot 2015-08-12 at 21 22 37](https://cloud.githubusercontent.com/assets/13522800/9223811/7328bc10-4138-11e5-8b57-f90f8893aa9a.png)

E3 Page:
![screen shot 2015-08-12 at 21 22 06](https://cloud.githubusercontent.com/assets/13522800/9223812/74a56ce6-4138-11e5-8750-30683f7a2641.png)
![screen shot 2015-08-12 at 21 22 45](https://cloud.githubusercontent.com/assets/13522800/9223813/7660aa64-4138-11e5-81bd-20362ec0425b.png)

Miraculously, E1 and E4 so far is working just fine:

E1 Page:
![screen shot 2015-08-12 at 21 22 16](https://cloud.githubusercontent.com/assets/13522800/9223821/8bffa5a0-4138-11e5-8ee1-014465cc40f2.png)
![screen shot 2015-08-12 at 21 22 28](https://cloud.githubusercontent.com/assets/13522800/9223824/8ed9a12c-4138-11e5-9678-5c58dd7636ba.png)

E4 Page (well this map just have one sortie so far):
![screen shot 2015-08-12 at 21 22 54](https://cloud.githubusercontent.com/assets/13522800/9223826/99ef573c-4138-11e5-9073-6edb81fd8143.png)

**Comment by dragonjet** [comment]
ah the combined fleet nodes. I can only test this when I start E-2 xD

**Comment by ethrundr** [comment]
@dragonjet let me warn you, E3 is truly hellish in this event's main operation.....

**Comment by NicolaosGreene** [comment]
@dragonjet I'm doing E-2 now is there anything you want me to do to help you collect data? It looks like E-2 won't take me long so I wanted to ask before I got more than 1 sortie into it.

**Comment by ethrundr** [comment]
it seems this one hasn't been fixed yet, eh?
since out there more and more people starting to complaint about the combined fleet sortie history....

**Comment by dragonjet** [comment]
oh yes omg I need to sortie E-2 now for this

**Comment by dragonjet** [comment]
there are still missing formation icons though. making them now.
but I'd have to start from scratch, the Flash file for existing white icons are missing xD
