### ISSUE TITLE
Uncaught ReferenceError: container is not defined

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#599]
When crafting an equipment, this error appears. That makes the quest counter not increased. (Natsuiro theme only)

![screen shot 2015-08-12 at 9 15 51 pm](https://cloud.githubusercontent.com/assets/8078323/9224752/60d1643c-4137-11e5-9280-98b36a0c1e1b.png)

**Comment by ethrundr** [comment]
This also happened during the sortie, as my latest reply on #596 
This also make the prediction is not appearing for our ships

**Comment by dragonjet** [comment]
ohhh so this is why craft gear is not being tracked

now removed all `container` from natsuiro
tomorrow will do the crafting notification on natsuiro
