### ISSUE TITLE
Unreadable Text on Resource Nodes

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#604]
Upon arriving to the resource nodes, the text showed is cannot be seen due too dark. It also doesn't give detail about what exactly we got:
![screen shot 2015-08-13 at 04 22 59](https://cloud.githubusercontent.com/assets/13522800/9234447/dd766e38-4173-11e5-993a-94ebdab15651.png)

**Comment by ethrundr** [comment]
Adding details, the blue node "Battle Avoided" also gives unreadable text same with the resources node.
Screenshot will be posted later.

**Comment by dragonjet** [comment]
![nodecolors](https://cloud.githubusercontent.com/assets/557312/9247405/544d7be8-41e5-11e5-897a-ba29d583cd64.png)

**Comment by bamboo3250** [comment]
:+1:
