### ISSUE TITLE
[Github Wiki] No v16 Release Notes

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#605]
Just notice this...
@dragonjet v16 Release note is not there yet on the Github Wiki....
![screen shot 2015-08-13 at 05 01 56](https://cloud.githubusercontent.com/assets/13522800/9235253/8b060c62-4178-11e5-8749-540a5831b37b.png)

**Comment by dragonjet** [comment]
ah yes I didn't write it XD
somebody was asking for it as well down at the facebook page
probably when I get another SR I will write :laughing:

**Comment by ethrundr** [comment]
@dragonjet now I wonder....
would it v17 or SR that comes first :laughing:

**Comment by ReiFan49** [comment]
v16 is bundled with v17 information...

have you passed 25000 pts for current 伊２５ event?
![cmom55cveaaadww](https://cloud.githubusercontent.com/assets/9847780/9249570/48c3bbb0-41f0-11e5-83c5-a79307f304fd.jpg)

**Comment by dragonjet** [comment]
ah good idea, I'll just write the changelog for 16 and 17 together :v

**Comment by ReiFan49** [comment]
nah, looks like @dragonjet already got the SR :v 
close this?

**Comment by ethrundr** [comment]
let's close this, since it's already written down now on the wiki XD
