### ISSUE TITLE
Inconsistency in the night-battle prediction

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#606]
When I doing E-1 I noticed unlike when I was doing doing day battles where sowed the current HP with a bar under it, that it would instantly show my ships final hp without showing what their hp was before the night battle started. This seems to be inconsistent with how the visual theme of KC3Kai is supposed to be and is most probably a bug.

**Comment by dragonjet** [comment]
since this also applies even to single fleets, cannot merge this with #578 so will not mark duplicate, but is heavily related.

will check later on latest Battle Prediction if still not working

**Comment by dragonjet** [comment]
#### Before Fix
Before the fix, we can see that night battle starts with the predicted HP as its official HP

See Kaga, who was still green after day battle, but upon starting night, she instantly became red. Wherein that red HP was supposed to be the prediction for "after-night"

![nightbattleprediction2](https://cloud.githubusercontent.com/assets/557312/9248302/27cefd46-41ed-11e5-9100-e377260a8bad.png)

#### After Fix
On the fix, the prediction bars work again, and the original HPs stay as the "grayed" bars

![nightbattleprediction_fix](https://cloud.githubusercontent.com/assets/557312/9248306/3d0ab10a-41ed-11e5-936b-12d21fdd6e3f.png)

**Comment by NicolaosGreene** [comment]
My report was specifically about the default theme rather than natsuiro would you mind checking it?

**Comment by dragonjet** [comment]
supposedly it will work for both themes
