### ISSUE TITLE
[Bug] Overflowing HP Bar in Night Battle

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#609]
When an abyssal ship's HP reaches negative value upon entering Night Battle, it'll reset the other ships' HP bar to full, making its HP bar to full once again, regardless the situation:
![screen shot 2015-08-13 at 06 45 40](https://cloud.githubusercontent.com/assets/13522800/9237661/56e656da-4187-11e5-8dee-77446d3c4e3d.png)
Those who are exempted from this bug are only those who were sunk during the night battle.

**Comment by dragonjet** [comment]
ohh that's true
