### ISSUE TITLE
FCF Verification

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#611]
has anyone tried using FCF on combined fleet?
does it work? xD
is ship box colored as gray when two ships retreat?
any bugs on implementation?

**Comment by NicolaosGreene** [comment]
I will probably end up using one at some point during this event, if I do do you want me to record my data?

**Comment by dragonjet** [comment]
ah if you can just see the ship boxes being marked that will be all. The API was implemented before the event (using data from E.O.) but wasn't actually tested here

**Comment by dragonjet** [comment]
This just became number 1 priority.

My friend just had his starter Fubuki K2 sunk because of the lack of FCF indicator

**Comment by NicolaosGreene** [comment]
So is the code working to detect it and there is no icon or are both failing?

**Comment by bamboo3250** [comment]
If he is using KC3Kai, he can check the morale to see if the ship is under FCF or not. After using FCF, the ship morale drops dramatically to 15 (+ mins spent on sortie). That's one way to check for FCF.

**Comment by dragonjet** [comment]
yea I also told him here's still this allowance time between the battle result and the next node formation selection. but its done :sob:

**Comment by c933103** [comment]
Can kc3 kai show an icon if first fleet flagship equipped with FCF, and also show a bar that display is there any healthy DD left for the eligible use of FCF?

**Comment by ethrundr** [comment]
I believe we can generate the marker by determining the drop of morale value, can't we?

as long as the ships fulfill these:
- drastic morale drop to 15 or below
- happened to two ships in a single node
- one of the ships is DD from the second fleet
- the other ship has status of "Heavily Damaged"
- the flagship of main fleet is using FCF
we can immediately mark this two ships as "being sent home"

also, @c933103's suggestion is quite necessary. showing an indicator whether FCF is being equipped is vital to the combined fleet, especially there is no equipment details in the combined fleet screen.

**Comment by dragonjet** [comment]
hm I think it's more of like, marking those this already sent back home as gray, same with in-game, with the HP bar not anymore red, and the box having a faint gray background too

in terms of, if FCF is equipped, I think they can just manually check back on fleet 1 if it's equipped. no need for us to go to the extent of adding indicators for eligibility

**Comment by NicolaosGreene** [comment]
Currently, when you use this it marks them grey when they retreat but they don't stay grey after you leave the results screen.

**Comment by bamboo3250** [comment]
Fixed bug mentioned in @NicolaosGreene 's comment in #646
