### ISSUE TITLE
Database Errors

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#612]
I'm using this version https://github.com/dragonjet/KC3Kai/commit/5a3c6cab4a62c01c1f3b9f1124906df765413305

and get this report
![image](https://cloud.githubusercontent.com/assets/13024936/9242017/e7adbcc8-41ad-11e5-9b80-42f1dbc2949d.png)

and this is from console log error
![image](https://cloud.githubusercontent.com/assets/13024936/9242031/12505ff8-41ae-11e5-84fd-3983c0b4ff92.png)

**Comment by dragonjet** [comment]
I'm getting this now after fixing the initial eror
```
Uncaught TypeError: Cannot read property 'add' of undefined
```

**Comment by McDohl** [comment]
and battle mode at default theme is not shown due to error

**Comment by dragonjet** [comment]
There's also @McDohl's #613 on strategy room, but this will all together be fixed along with the Database fixes.

**Comment by ethrundr** [comment]
Adding more details for Strategy Room, there are also Database errors.

The error shown, all have similar error of: `Uncaught TypeError: Cannot read property 'where' of undefined` from `Database.js`
![screen shot 2015-08-13 at 15 05 00](https://cloud.githubusercontent.com/assets/13522800/9243536/c6f48286-41cc-11e5-8f14-9dea62ef622e.png)
![screen shot 2015-08-13 at 15 05 10](https://cloud.githubusercontent.com/assets/13522800/9243537/c6fb69e8-41cc-11e5-8eaa-e8f5a16df24a.png)
The last 6 errors is while trying to load per map on Event Sortie History.

Complete log of working and not working features:
:white_check_mark: Profile
:x: Resources Graph
:x: Consumables Graph
:white_check_mark: Showcase
:white_check_mark: Ship List
:x: Construction History
:x: LSC History
:white_check_mark: Equipment List
:x: Crafting History
:white_check_mark: Current Fleet
:white_check_mark: Export
:white_check_mark: Shiplock Planner
:white_check_mark: Quest Flowchart
:x: Sortie History
:x: Event Sortie History (page loaded, no history shown)

**Comment by ethrundr** [comment]
For the Battle Prediction itself, it is appearing, with the exception of the first node.
However, the display seems to be bugged here....
![screen shot 2015-08-13 at 15 12 46](https://cloud.githubusercontent.com/assets/13522800/9243639/db2cbcc2-41cd-11e5-84fc-46b60f183311.png)

**Comment by McDohl** [comment]
more details for default theme battle mode not active log:

![image](https://cloud.githubusercontent.com/assets/13024936/9243690/58c3782c-41c6-11e5-9924-32c165a850a4.png)

**Comment by dragonjet** [comment]
can try the fix?

**Comment by McDohl** [comment]
sure

**Comment by McDohl** [comment]
@dragonjet more error popping up 
![image](https://cloud.githubusercontent.com/assets/13024936/9244440/c4a191bc-41cd-11e5-9f47-228216b8afe0.png)

**Comment by ethrundr** [comment]
I'm gonna try it on the Strategy Panel

**Comment by dragonjet** [comment]
@McDohl those ones are related to prediction now, outside of the database errors. I don't know where we should put that since we just pulled KanColleHelpers from @Javran . Maybe @bamboo3250 would know more since he is the one working closer on the predictions

**Comment by McDohl** [comment]
ah okay then

**Comment by ethrundr** [comment]
@McDohl imo just make it, so it can be tracked later on

**Comment by bamboo3250** [comment]
@McDohl which node or map does this happen? I can go there to check it.

**Comment by McDohl** [comment]
@bamboo3250 it was from e-4 submarine node for 1st issue and 2nd report from e-4 takoyaki nodes night battle. but somehow after 1st run. and re-run again to that map. it's suddenly fixed w/o any error :sweat: . 

sorry for the trouble :sweat_smile:

**Comment by bamboo3250** [comment]
I'm also running E4 and have seen no error so far. I will run a few times again to make sure it works properly.

**Comment by ReiFan49** [comment]
uh oh, sounds like my algorithm mess up again .___.)
i thought i've tested it correctly though, 
did the database initialization on console.log gives different database structure? or something?

**Comment by McDohl** [comment]
@bamboo3250 i think it's only happening for first time running the extensions. since i'm on lanshop and just load it to this computer. After the error occured, it will works normally. just the very first run

![error](https://cloud.githubusercontent.com/assets/13024936/9249598/ed6713bc-41f8-11e5-9d40-b44de1459e2a.png)

**Comment by bamboo3250** [comment]
@Javran can you think of any reason?

**Comment by dragonjet** [comment]
wait, maybe we should separate @McDohl's issue onto another thread.

@ReiFan49's comment still refers to the original db issue XD

the `ERR_NAME_NOT_RESOLVED` is probably the shop blocking photobucket

the `KanColleHelper` error though, no idea. But I will try later to see if we can find clues on which functions trigger this

**Comment by McDohl** [comment]
@dragonjet no, for the first run only it's blocking :sweat_smile: after first battle mode aka back to base cuz u r rekt'ed and go sortie will working properly (images and kancollehelper too)

**Comment by McDohl** [comment]
@bamboo3250 i download https://github.com/dragonjet/KC3Kai/commit/7593f52c4d2c2641f15c0b4a911a6b221c683c19 and move to other computer and its working properly now

**Comment by dragonjet** [comment]
aye, nice :+1: no need to create new issue xD
