### ISSUE TITLE
Strategy Room Error

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#613]
Map History, Resources History, Consumables history, and Crafting history
will be blank and show this error

![image](https://cloud.githubusercontent.com/assets/13024936/9242233/e64cac74-41b0-11e5-93c9-3a4d4c7916d6.png)

edit i'm using https://github.com/dragonjet/KC3Kai/commit/e7718aa0f1612a18d4366b1831060fc95220b3b1

**Comment by dragonjet** [comment]
ah this is the same as #612 where the local database is getting an error. will track it there
