### ISSUE TITLE
[Suggestion] Battle Rating: S and Perfect S

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#615]
Just to spice things up, how about if we add some glow effect (like in morale when > 53), when the battle rating is Perfect S?

**Comment by ReiFan49** [comment]
it means, it requires afterHp and currentHp is equal with battle prediction off too,
because there's no api data for this

**Comment by dragonjet** [comment]
^ true that :cry:

**Comment by bamboo3250** [comment]
Oh wait, then what is this? xD ![screen shot 2015-08-13 at 7 51 30 pm](https://cloud.githubusercontent.com/assets/8078323/9249120/c6a24d54-41f4-11e5-80b7-c24f30902610.png)

**Comment by ReiFan49** [comment]
well, i just followed the way the previous code...
i wonder why "SS" appeared on the first place.

**Comment by dragonjet** [comment]
yea, it doesn't really return `SS` i just made that up XD

so in the end we still need the HP checks to know if it's perfect S

**Comment by ReiFan49** [comment]
```javascript
  function FleetHP(container, ShipBox, hp, afterHp, rosterId){
    KC3SortieManager.currentNode().isPerfectRun &= hp[0] == afterHp[0];
    if (!ConfigManager.info_battle) {
      afterHp = null;
    }
    afterHp = afterHp || [hp[0], hp[1]];
    // omitted the rest
```

**Comment by dragonjet** [comment]
seems **[Support #615]** on commit message did not close this issue XD

**Comment by ReiFan49** [comment]
well, i'm just testing it, not finalize it :P 
if it's ok, then close

**Comment by dragonjet** [comment]
yea, saw it and i think it's good to go :+1:
