### ISSUE TITLE
Natsuiro level location is incorrect when greater than 99

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#620]
I noticed that when I had a ship of level greater than 99 that the level was wrapping down below the HP bar as can be seen in the picture of my I-19 below. This is probably just an error related to not dealing with triple digit levels.

![error](https://cloud.githubusercontent.com/assets/3627763/9252179/b1744552-419c-11e5-8113-991ecd44d5f7.png)

**Comment by Crazyteitoku** [comment]
Flonnaru (via kancolle.wikia.com) also enquired about the said issue (screenshot attached):
![](http://i.imgur.com/xFcPiJg.png)

Looking forward to a fix! :laughing:

**Comment by dragonjet** [comment]
wait @Crazyteitoku this has been fixed on 1fa2d0cc2a5068de2711ae2418ab0e0edc42d56b XD

**Comment by dragonjet** [comment]
wait I realized that one is vertical

**Comment by Crazyteitoku** [comment]
Yup, but in theory it seems to be a minor fix iinm. :+1:
