### ISSUE TITLE
Morale value more than 100?

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#621]
first time seeing this xD

![lol](https://cloud.githubusercontent.com/assets/13024936/9253107/a68509c0-420e-11e5-9e55-f1feb222f812.JPG)

**Comment by bamboo3250** [comment]
:open_mouth: ............. :scream:

**Comment by ReiFan49** [comment]
is it night battle node?
if yes, basically it's my fault.
for letting +1 on yasen start and -3 on yasen request

**Comment by dragonjet** [comment]
lol at @bamboo3250 reaction

**Comment by McDohl** [comment]
@ReiFan49 yes it's yasen node

**Comment by ReiFan49** [comment]
wait, gonna test another thing and start patch the node thingy (included with... uhh.. why i forget the issue number.)

**Comment by ethrundr** [comment]
101 morale..... :scream: 
if it's real.... will it deal much more damage? XD

**Comment by McDohl** [comment]
@ethrundr she is in the mood for "night battle" ( ͡º ͜ʖ ͡º) :smirk:

**Comment by ethrundr** [comment]
@McDohl LOL :laughing:
