### ISSUE TITLE
PvP Night Battle Issues

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#624]
As stated before in #504 
The current version once again does not give the updated prediction for PvP Night Battles, as shown below:
![screen shot 2015-08-14 at 05 53 57](https://cloud.githubusercontent.com/assets/13522800/9261480/17c4b592-4249-11e5-83ac-a524462ff30d.png)
This error is applied only to the enemy fleet, by the way. Our fleet prediction still working properly.

I believe this already solved on Default theme in v015, so in the upcoming v017 this should working as well in the Natsuiro theme, since everyone is using it right now.

The latest build I was using is the 5ca543e commit

**Comment by ReiFan49** [comment]
oh ... i see why.

PvPNight only handles current fleet state, without updating the state like BattleNight
(nah... this body.... "Sunk -> KO" .... lol)
