### ISSUE TITLE
F5 & F7 tracking does not seem to work in Natsuiro theme

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#626]
When I developed equipment with both F5 & F7 with the Natsuiro theme it did not track the progress of the quests.

**Comment by ethrundr** [comment]
It's working just fine on my side...
But well, might re-check it tomorrow after reset....

**Comment by ReiFan49** [comment]
it updated on my side (on doing F5)

**Comment by NicolaosGreene** [comment]
Hmmm, maybe my KC3kai glitched. I'll let you know if the problem repeats itself tomorrow then.

**Comment by ethrundr** [comment]
@NicolaosGreene try fetching the latest commit, then reload your KC3kai

**Comment by NicolaosGreene** [comment]
How exactly does one do that?

**Comment by NicolaosGreene** [comment]
Never mind, I think I have figured it out

**Comment by NicolaosGreene** [comment]
Seems to be working fine today closing the issue
