### ISSUE TITLE
Overflowing Fighter Power

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#628]
It seems someone working on this forgot to limit the decimals.....
![screen shot 2015-08-14 at 12 04 30](https://cloud.githubusercontent.com/assets/13522800/9266495/b93999a0-427c-11e5-8ff7-a8fe4ce67fa0.png)

Anyone can fix this quick, before the update tonight?

**Comment by McDohl** [comment]
ah, was trying to report this xD

**Comment by dragonjet** [comment]
9ec0de9dfc0b9d8e82a8865f44d3d55f736b964f
aye, can try as of latest XD

**Comment by McDohl** [comment]
it's working properly now

**Comment by dragonjet** [comment]
:+1:

**Comment by bamboo3250** [comment]
Somehow it still persists for Combined Fleet.

![screen shot 2015-08-14 at 6 00 24 pm](https://cloud.githubusercontent.com/assets/8078323/9271714/a7a5cb3c-42ae-11e5-98e5-2de279a43acf.png)

**Comment by dragonjet** [comment]
aye, can try again?

**Comment by bamboo3250** [comment]
It still has 2 digit after the dot, not even in the battle.

![screen shot 2015-08-14 at 6 24 45 pm](https://cloud.githubusercontent.com/assets/8078323/9272103/ce028b1e-42b1-11e5-99af-eb879d9fff23.png)

**Comment by dragonjet** [comment]
yep, supposedly rounded by 2 digits xD
or should we round down?

**Comment by bamboo3250** [comment]
It looks fine to me. I thought it's supposed to be an integer xD If it's intended then it should be fine.

**Comment by dragonjet** [comment]
yea xD
I already uploaded v17 so.. gg :laughing:
