### ISSUE TITLE
Event Priority: Part 3

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#633]
#### Event Priority Series
* Part 1 (v16): #444
* Part 2 (v17): #461
* Part 3 (v18): *this*

#### Contents
:white_check_mark: #582 Natsuiro Tasks
:white_check_mark: #417 Sortie history pagination
:white_check_mark: #493 Prediction for Damecon
:white_check_mark: #28 Support Expedition Power
:white_check_mark: #611 FCF verification
:white_check_mark: #369 Difficulty indicators to associate drops

**Comment by McDohl** [comment]
* there's no hayashui at ship list
* strategy room Maps History (event and normal) still using numbers instead of letters

**Comment by bamboo3250** [comment]
Since the ship type of Hayasui is a new one so KC3Kai cannot catch that. We need to update `stype.json` as well.

**Comment by ReiFan49** [comment]
i thought that Hayasui is AP (same as Wa-class) ....

**Comment by McDohl** [comment]
just realized my comment before is not event priority :cold_sweat:

**Comment by bamboo3250** [comment]
@ReiFan49 The ship type AP is 15 and the newest type CT (Training Ship) from the last event is 21. Meanwhile the ship type of Hayasui is 22. I'm sure it is a new type.

@McDohl It's still related to the current event and we need to fix it eventually :smile:

**Comment by dragonjet** [comment]
@McDohl which comment?

**Comment by ethrundr** [comment]
aside from the discussion, I realized something with the issue number...
the pre-event one is 444
the one that opened after event start is 461
now, the current is 633

just within 5 days of event, we already generate almost 200 issues and pull requests. wow XD

**Comment by ethrundr** [comment]
@ReiFan49 @bamboo3250 officially in the Hull code, as well as the type description in KC, Hayasui is categorized under "Auxiliary, Fleet Oiler" type, and abbreviated as "AO". So, yes, it's a new type.

**Comment by ReiFan49** [comment]
ah i see, i thought with the almost same kanji on the ship type identity (the upper left on the card) means the same with wa-class ... wait... i don't see it for more than 1 second.

i need to get kirito asap (E-1 now)

**Comment by ethrundr** [comment]
Well, Wa-class is "Auxiliary, Transport Vessel" (or AP in short).
In reality, both functions are similar. The only differences that AO only carries refueling supplements (oils), while AP carries almost everything a ship and its crew needed except foods (oils, ammunitions, soldier armaments, ship spare parts, etc.)

**Comment by c933103** [comment]
#369 is it verified ?

**Comment by dragonjet** [comment]
ah yes, for [#369 drop report info] we can now verify drops via difficulty.

@ReiFan49 recently added a marker on Sortie History on each battle done if easy, medium or hard. the drops are also contained.

we don't have reporting mechanism though
