### ISSUE TITLE
5-4 map name displays incorrectly

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#638]
When I was using 5-4 to level some ships I noticed that the map name for 5-4 was displaying incorrectly as is shown below.
![bug](https://cloud.githubusercontent.com/assets/3627763/9276913/6d08b30a-426c-11e5-93c5-0dd99ea545e0.png)

**Comment by dragonjet** [comment]
ah seems it says "5-undefined" xD

**Comment by ethrundr** [comment]
this also applied in every map. just try sortieing to map 2, and it's also give similar output:
![screen shot 2015-08-15 at 06 33 49](https://cloud.githubusercontent.com/assets/13522800/9284541/a1b76ac8-4317-11e5-9072-4f469e99863b.png)

**Comment by NicolaosGreene** [comment]
It seems to be working correctly in E-3 though

**Comment by ethrundr** [comment]
@NicolaosGreene on event maps it's working fine, because there is difficulty ranks
the fault is only on normal map where there is no difficulty there.
