### ISSUE TITLE
Additional Information for Combined Fleet

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#639]
After doing E2, E3 and currently E6, I realized that our Combined Fleet screen is lacking these two important indicator:
- Support Expedition Indicator. 
This one should be displayed whether the normal and boss support expedition is already launched or not. Although this can be found out by switching back to "Basic" tab, it'll be more convenient if there are indicators to tell whether these two support expedition is on their way, or already exhausted.

- FCF Equipped Indicator.
As being discussed in #611, it's become important to add indicator to the Combined Fleet screen, determining whether FCF is equipped and it is eligible to be used. This will be helpful information for those during combined fleet sortie to plan their sortie progress: whether to retreat at that node, or proceed to the next one.

My suggestion is to include a small indicator to let the user know about all of these. There will be three indicator: one for the normal support, one for the boss support and the last is for the FCF eligibility.

<br/>
Here I already try to put some layout examples.
I also made two types of examples: one only dots and the other with short text. Personally, I choose the second one.
- The red dot indicating the normal support indicator
- The blue dot indicating the boss support indicator
- The purple dot indicating the FCF indicator.

![screen shot 2015-08-14 at 05 53 57 copy 2](https://cloud.githubusercontent.com/assets/13522800/9284119/0fa65cd2-4314-11e5-9d8e-9152d39b02b5.png)
![screen shot 2015-08-14 at 05 53 57 copy 3](https://cloud.githubusercontent.com/assets/13522800/9284120/0fa9a1d0-4314-11e5-9a06-c710cce20466.png)
Please note that these dots is just layout examples. If you guys have a better idea, then it's more than welcomed.

**Comment by dragonjet** [comment]
imho this is spoon-feeding the player too much xD

both support expeditions and FCF, although not always identifiable in a glace, can be seen by checking different tabs, but it already exists in the UI. I think they should just check back and do some clicking themselves xD

the original FCF problem with my friend is that he didn;t know which ships were actually sent back home. not the case of whether he had FCF equipped or not.

**Comment by ethrundr** [comment]
Ah okay. I'm closing the thread, then~
