### ISSUE TITLE
Battle Prediction Default Setting

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#640]
There are some input to me via Facebook, that during event the battle prediction should be disabled by default, or maybe, hidden.

Those who suggesting this are comes with reason that being spoiled by this option is somehow making the event lost its essence. Some even feels irritated by being spoiled. Therefore, I think that the setting should be default disabled, and only those who want to be spoiled are the one who enabled it.

**Comment by dragonjet** [comment]
Alright, we can set this disabled by default. However, those already playing will not get overridden. Meaning if they already have it on, will stay on.

The default off only applies to those who will just install the extension
