### ISSUE TITLE
[Strategy Room][Bug] Overflowing Numbers

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#643]
On the event sortie history page, when the number exceeds -99 in the "Enemy" side, it'll overflowed and skipped to the next line, become like this:
![screen shot 2015-08-15 at 14 06 20](https://cloud.githubusercontent.com/assets/13522800/9287569/f8898ae0-4356-11e5-9845-d515c16b49f4.png)

Cannot check on the normal sortie history, since the "One sortie per page" bug is appearing again (yes, again).
edit: Reload the page, and the history comes out.
edit2: This bug also happened on the normal sortie page:
![screen shot 2015-08-15 at 14 11 35](https://cloud.githubusercontent.com/assets/13522800/9287580/99391ec4-4357-11e5-9ae7-606cc3869477.png)

**Comment by ReiFan49** [comment]
i remember, **i almost post the issue about this** lol,
poking @dragonjet in chat is not a good way to report this thing right xD (wtf 5 nodes run...)

**Comment by dragonjet** [comment]
:+1:
