### ISSUE TITLE
[Suggestion] Availability for testing custom alarm sound

### ISSUE THREAD

**Issue by kololz** [dragonjet/KC3Kai#644]
Since I've been streaming, the ding sound sounds strange when I am streaming, so I've got myself a new sound (http://images.wikia.com/kancolle/images/9/96/Verniy-Equipment_3.ogg) to use.

I've set my new sound, but eventually I found that its too loud in 100%, turned it down to 40%, I cannot hear the sound again during the next 8 hours (because I'm going sleep).

I want to get a exact volume I want ASAP, but eventually there is no way to test it other than waiting.

Will you implement a button for testing the alarm sound? This might help others who are having the same situation as me or they might want to see if the link is broken or not.

**Comment by ethrundr** [comment]
Ah, this might be a good idea
I'm personally also support this idea to give a "Test" button upon setting a new custom alarm or reconfigure the alarm volume.

As for placement.... maybe beside the volume setting? There's quite lot of spaces there~

**Comment by c933103** [comment]
how about automatically  ring the alarm once everytime when setting is changed?

**Comment by dragonjet** [comment]
hm that's a good idea
