### ISSUE TITLE
[Translation][ID] Mispelled Words

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#647]
@vrarara 
On quest 158 and 159 (commit 5f906c9)
I think "flagship" should be "Kapal **Sekretaris**", not "Sekertaris" as what are written now....

**Comment by dragonjet** [comment]
maybe we can confirm this with @vrarara

**Comment by ethrundr** [comment]
@dragonjet well I'm Indonesian as well, and as far as I remembered in the dictionary is "Sekretaris"
but, let's wait for vrarara

**Comment by vrarara** [comment]
oh thx @ethrundr i'll change that now

**Comment by dragonjet** [comment]
pulled #648
