### ISSUE TITLE
[Bug] FCF Marker

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#650]
FCF marker is gone once the fleet is proceeding to the next node:
![screen shot 2015-08-16 at 13 26 47](https://cloud.githubusercontent.com/assets/13522800/9292145/c96b4f24-4422-11e5-8988-1058bed4b1ca.png)

Both Amatsukaze and Bismarck was turning white after being sent home using FCF, but turned to normal like shown in SS above after entering the following node.

**Comment by bamboo3250** [comment]
@ethrundr are you using webstore version?

**Comment by ethrundr** [comment]
My latest pull when submitting this was 35d4f79
Haven't test it after that due to resource shortage :cry:

**Comment by bamboo3250** [comment]
@ethrundr that commit precedes my fix for the FCF (43cb9e). Make sure you pull the latest commit  xD

**Comment by ethrundr** [comment]
tested this one, and as @bamboo3250 said, this has been fixed.
closing the issue now~
