### ISSUE TITLE
Add Night battle attack power column in Ship List in Strategy Room

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#654]
In event maps, one of our big concerns is which ship will deal the most damage in night battle. Therefore, there is a need for sorting ships by night attack power, which is the sum of fire power and torpedo stats (with or without equip stats).

**Comment by dragonjet** [comment]
ohhh nice nice, though this is for DA right?
CI is a different story

**Comment by ethrundr** [comment]
@dragonjet isn't DA and CI in night battle just differ in the damage modifier?
the base number still the sum of firepower and torpedo stats?

**Comment by bamboo3250** [comment]
@dragonjet as @ethrundr said, the base damage of both DA and CI depends on Firepower and Torpedo. The only difference is their damage modifier. Here I assume that the wikia is correct http://kancolle.wikia.com/wiki/Combat#Night_Combat

**Comment by dragonjet** [comment]
hm alright, seem I didn't do my homework :v

**Comment by bamboo3250** [comment]
@dragonjet well, I just finished adding another column for yasen power but not enough space for the lockheart xD

![screen shot 2015-08-18 at 7 45 21 pm](https://cloud.githubusercontent.com/assets/8078323/9329151/c3586fd4-45e1-11e5-8bd0-cf48f65ba21e.png)

**Comment by dragonjet** [comment]
ohh that's nice :+1: 
we can drop the heartlock for now, probably just change it back after event.

**Comment by bamboo3250** [comment]
you mean the heartlock or yasen power?

**Comment by dragonjet** [comment]
yasen power after luck, since I'm thinking people would be using both in considering who's who for night battles

**Comment by bamboo3250** [comment]
oh that's right. Luck is also important for yasen. About the color of luck column, is #66FF66 for both odd and even row?

**Comment by bamboo3250** [comment]
Something like this?

![screen shot 2015-08-18 at 8 19 53 pm](https://cloud.githubusercontent.com/assets/8078323/9329703/928f8d92-45e6-11e5-8481-520df132cd1c.png)

**Comment by dragonjet** [comment]
oh yess, excited to pull this, wanna see my own shiplist :v

**Comment by bamboo3250** [comment]
Haha okay, i will create a pull request right after finishing my dinner :3
