### ISSUE TITLE
Air battle prediction works incorrectly

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#660]
@Javran According to the result from the game, there should be 2 abyssal ships sunk in the battle combat.
http://pastebin.com/3nX6MRz3 (E7 - node K)

**Comment by McDohl** [comment]
yea, air battle node only calculate the first wave

**Comment by Javran** [comment]
Is this for surface task force? I thought air battle only happens for carrier task force.

**Comment by bamboo3250** [comment]
We also can use STF for air battle as well. Here I am using Surface task force.

**Comment by Javran** [comment]
Ah I see, an easy fix, will do it immediately after I complete my daily exercise :)
btw for exercise, the ship sunk during night battle is not marked, is there a related issue?

**Comment by bamboo3250** [comment]
There is a different marker for "sunk" ships in exercise since it may not be nice to show sunk icon for other players' ship girls. In case there is no icon shown, it can be that that ship still had 1hp left (not really knock out). Our system can detect the difference between really having 1hp left and being knock out.

**Comment by Javran** [comment]
Does this look like what was happened?

```javascript
> DA.analyzeRawSurfaceTaskForceBattleJS( svdata.api_data )
{ main: 
   [ null,
     { currentHp: 45 },
     { currentHp: 73 },
     { currentHp: 48 },
     { currentHp: 84 },
     { currentHp: 79 },
     { currentHp: 49 } ],
  escort: 
   [ null,
     { currentHp: 45 },
     { currentHp: 28 },
     { currentHp: 32 },
     { currentHp: 84 },
     { currentHp: 55 },
     { currentHp: 44 } ],
  enemy: 
   [ null,
     { currentHp: 160 },
     { currentHp: 74 },
     { currentHp: 12 },
     { currentHp: -13 },
     { currentHp: -30 },
     { currentHp: 28 } ] }
```

**Comment by bamboo3250** [comment]
@Javran Yeah, that's correct. Only number 4 and 5 of the enemy were sunk while other were just scratched and the flagship was untouched :+1:

**Comment by Javran** [comment]
hmm, but the ship sunk during day battles are still using the same sunk marker as abyssal ships. maybe I should open a different issue for this.
