### ISSUE TITLE
Air parity is not displaying on the battle panel

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#664]
When I was at E-4 H I achieved air parity but nothing was displayed on the battle panel as can be seen below.
![ap](https://cloud.githubusercontent.com/assets/3627763/9312014/c4a2539e-44df-11e5-84ff-69df9224c760.png)

**Comment by LostLogia4** [comment]
Uh uh yeah, this happened in default theme as well.

**Comment by NicolaosGreene** [comment]
I had no idea, is this intended? I know I have seen AP in PvP, but does that not work for combat?

**Comment by bamboo3250** [comment]
I also noticed this but didn't know why this happened. It is surely not intended.

**Comment by dragonjet** [comment]
hm I don't know what it is too. never tried parity. need battle data xD

**Comment by NicolaosGreene** [comment]
Will collect it on my next run

**Comment by NicolaosGreene** [comment]
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_dock_id":1,"api_ship_ke":[-1,614,579,592,577,576,576],"api_ship_lv":[-1,1,1,1,1,1,1],"api_nowhps":[-1,83,52,31,30,71,50,96,96,66,38,37,37],"api_maxhps":[-1,83,57,31,31,90,50,96,96,66,38,37,37],"api_midnight_flag":1,"api_eSlot":[[556,548,558,549,-1],[547,548,549,549,-1],[550,550,545,525,-1],[502,515,542,-1,-1],[502,545,542,-1,-1],[502,545,542,-1,-1]],"api_eKyouka":[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],"api_fParam":[[98,0,82,95],[84,84,72,77],[50,84,79,51],[73,93,59,52],[104,0,82,92],[29,0,69,59]],"api_eParam":[[25,0,50,80],[25,0,50,80],[64,92,96,68],[44,72,36,29],[38,66,32,26],[38,66,32,26]],"api_search":[1,1],"api_formation":[1,3,2],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[6],[7,8]],"api_stage1":{"api_f_count":63,"api_f_lostcount":9,"api_e_count":192,"api_e_lostcount":63,"api_disp_seiku":0,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":14,"api_f_lostcount":4,"api_e_count":80,"api_e_lostcount":36},"api_stage3":{"api_frai_flag":[-1,0,1,0,0,0,1],"api_erai_flag":[-1,0,0,0,1,0,0],"api_fbak_flag":[-1,0,1,0,0,0,1],"api_ebak_flag":[-1,0,0,0,0,0,0],"api_fcl_flag":[-1,0,0,0,0,0,0],"api_ecl_flag":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,7,0,0,0,7],"api_edam":[-1,0,0,0,25,0,0]}},"api_support_flag":0,"api_support_info":null,"api_opening_flag":0,"api_opening_atack":null,"api_hourai_flag":[1,1,0,1],"api_hougeki1":{"api_at_list":[-1,1,5,10,2,12,4,11,3,7,6],"api_at_type":[-1,0,0,0,0,0,0,0,0,0,0],"api_df_list":[-1,[9],[8],[6],[10],[4],[12],[2],[11],[1],[8]],"api_si_list":[-1,[9],[9],[502],[90],[502],[122],[502],[-1],[-1],[-1]],"api_cl_list":[-1,[1],[1],[1],[1],[0],[1],[1],[1],[0],[2]],"api_damage":[-1,[68.1],[37.1],[4],[54],[0],[45.1],[3],[18.1],[0],[66]]},"api_hougeki2":{"api_at_list":[-1,1,7,2,3,4,5,6],"api_at_type":[-1,0,0,0,0,0,0,0],"api_df_list":[-1,[7],[1],[11],[7],[7],[7],[7]],"api_si_list":[-1,[9],[-1],[90],[-1],[122],[9],[-1]],"api_cl_list":[-1,[1],[0],[1],[1],[1],[0],[1]],"api_damage":[-1,[38],[0],[62],[6],[6],[0],[22]]},"api_hougeki3":null,"api_raigeki":{"api_frai":[-1,0,1,1,1,0,0],"api_erai":[-1,0,0,0,0,0,0],"api_fdam":[-1,0,0,0,0,0,0],"api_edam":[-1,5,0,0,0,0,0],"api_fydam":[-1,0,2,1,2,0,0],"api_eydam":[-1,0,0,0,0,0,0],"api_fcl":[-1,0,1,1,1,0,0],"api_ecl":[-1,0,0,0,0,0,0]}}}

**Comment by dragonjet** [comment]
hmm seems api_disp_seiku really is `0`.
It should've shown air parity :open_mouth: 

I'm gonna try convert this
`this.airbattle = KC3Meta.airbattle( planePhase.api_disp_seiku || undefined );`

into this
```
if(typeof planePhase.api_disp_seiku != "undefined"){
	this.airbattle = KC3Meta.airbattle( planePhase.api_disp_seiku );
}else{
	this.airbattle = ["?", "", "Unknown"];
}
```

I know it's not much help but maybe the `|| undefined` is killing the script. I know it shouldn't but i dont see anything else

**Comment by NicolaosGreene** [comment]
Alright, let me know when you get that done and i'll pull that and try it

**Comment by dragonjet** [comment]
ah are you using the dev builds?

**Comment by NicolaosGreene** [comment]
yes, been pulling the newest update each time I get on

**Comment by dragonjet** [comment]
pushed the test code

**Comment by NicolaosGreene** [comment]
Pulled and reloaded will let you know the results once I finish sparkling my fleet and run E-4 again

**Comment by dragonjet** [comment]
thanks :+1:

**Comment by NicolaosGreene** [comment]
Appears to work now, closing it.

**Comment by dragonjet** [comment]
ah nice :+1:
