### ISSUE TITLE
Quest reset button for each individual quest

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#665]
When someone try to complete a quest and facing disconnection afterwards, the tracker shows error: the completed quest will not disappear from panel. This will stay for a whole day for daily quests, until the reset timer runs out and resets all the daily quest tracker:
![screen shot 2015-08-18 at 03 18 47](https://cloud.githubusercontent.com/assets/13522800/9312564/5de42e60-4558-11e5-8830-b3fffdabd065.png)
![screen shot 2015-08-18 at 03 18 26](https://cloud.githubusercontent.com/assets/13522800/9312569/60ac1680-4558-11e5-9311-3ee9eddccdeb.png)
![screen shot 2015-08-18 at 03 18 37](https://cloud.githubusercontent.com/assets/13522800/9312570/60e5176e-4558-11e5-973a-35645b16a417.png)

I assume, when this error happened to weekly quest, then it'll last for a whole week, then a whole month for monthly quest. When this happened to one-time-only quests.... well, I do not want to imagine that...

My latest pull was 0f6f52f.

**Comment by NicolaosGreene** [comment]
This bug has existed in some form since at least version 8. You can get similar effects by using the API link and having two computers running and completing the quest on another computer and it will get stuck in the quest log.

**Comment by ethrundr** [comment]
Then it's adding more reason to find a way to fix this.....
When happens on recurring event, this bring less harm, but just imagine if it happens on the one-time quest. It'll be troublesome and rendering the tracker useless.

**Comment by bamboo3250** [comment]
The temporary solution is manually resetting the quest in strategy room. We still can get the quest list again by navigating the quest page but not their trackers. In a long term, ideally, we should have a mechanism to clear the quest individually on the panel.

**Comment by dragonjet** [comment]
ah individual quest reset should be on strategy room. we have more room there.

for now, changing this issue entry to "Quest reset button for each individual quest"

**Comment by dragonjet** [comment]
Added 4 new buttons to strategy room.
* Manual counting overrides (+ and -)
* Quest status override (double arrow) to toggle: disabled, open, active, complete
* Clear quest which will remove the quest from list therefore clearing both status and count

Revisiting quest page will refill the quest list

![ss 2015-08-20 at 09 58 22](https://cloud.githubusercontent.com/assets/557312/9374175/a4a36b1c-4725-11e5-986a-e7820b4c2dbb.png)
