### ISSUE TITLE
Frequent KC3kai crashes when opening the about the developers page

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#666]
When I open the about the about the developers page from the KC3kai menu I frequently get crashes of the entire plugin. What should I do to get a better bug report to get to the bottom of this?

**Comment by dragonjet** [comment]
what does it say when it crashes?
it is chrome's "He's dead, Jim" screen, or does the extension get corrupted?

**Comment by NicolaosGreene** [comment]
It's the "he's dead ,Jim"  and which issue did you mean? You marked this one.

**Comment by NicolaosGreene** [comment]
Haven't been able to get it to crash since the last pull, did you change something related to this?

**Comment by dragonjet** [comment]
hm not that I know of

**Comment by Crazyteitoku** [comment]
Just saying here that it would be easier if you could provide git commit from when you first encountered the bug and from when you have now noticed that it (seems to) has/have been fixed. That way you can backtrace on the commits and see what changes went where.

**Comment by NicolaosGreene** [comment]
sorry, will do that from now on
