### ISSUE TITLE
Reset Quest buttons in Strategy Room do not affect quest list on the panel

### ISSUE THREAD

**Issue by bamboo3250** [dragonjet/KC3Kai#672]
I just tried Dailies and Weeklies buttons in the Strategy Room and they only reset the quests in Strategy Room, not the quest list on the panel. The counters still remain the same even when reloading the panel.

**Comment by ReiFan49** [comment]
those variable across the tabs/pages/panels are not the same one right?
like toggling `info_troll` on settings, does not mean toggling it on the panel,

need messaging across the chrome itself...

**Comment by bamboo3250** [comment]
Yeah, that's what i'm thinking too. For now, the panel and the tabs in Strategy Room are not really connected in real time to each other.

**Comment by dragonjet** [comment]
they should be synced actually. they both pull from `localStorage.quests`

we just need to make sure they do `KC3QuestManager.load();` each time so things done and saved on one side also gets loaded and carried over to the other side

**Comment by dragonjet** [comment]
I've actually been testing and haven't been able to get to the bottom of it

there is one thing on `QuestManager` that fixes half the problem though
`this.list["q"+questId] = new KC3Quest();` without passing any parameter

with that, the panel will update **only is the panel is reloaded**

still haven't figured out why it reverts all quests into active mode, when you just go to the home screen, and not reloading the panel. doing so will also revert the strategy room into active quests.

**Comment by dragonjet** [comment]
update: found it

`checkAndResetQuests` is being executed before any API call, which saves the quest list back into `localStorage`. This means on panel, `save()` is done first before `load()` so whatever data is in the panel persists, regardless if strategy room cleared it earlier.

will try a fix
