### ISSUE TITLE
Prevent refreshing? don't know if it have this function or not.

### ISSUE THREAD

**Issue by c933103** [dragonjet/KC3Kai#679]
I do not have kc3kai herw so i can't check have it include this function already... can it prompt a windows ask user to confirm is the user really wanting to leave kancolle when clicking Ctrl+W/F5/Alt+F4 ?

**Comment by bcc32** [comment]
Yep.  It exists (and is _so_ helpful).

**Comment by NicolaosGreene** [comment]
it's the exit confirmation setting

**Comment by NicolaosGreene** [comment]
However, it appears to only have a setting for the API game screen and not one for DMM website

**Comment by dragonjet** [comment]
ah yes, we have it

![ss 2015-08-19 at 08 21 50](https://cloud.githubusercontent.com/assets/557312/9346124/63845ffe-464b-11e5-826a-6fcfc8f184ff.jpg)
