### ISSUE TITLE
ExpeditionHelper Request

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#683]
With the recent features @Javran added on the helper script, we can now see repair times on HP bar tooltip:

![ss 2015-08-19 at 06 15 56](https://cloud.githubusercontent.com/assets/557312/9353878/6657969e-469e-11e5-8b9c-4cb555475654.jpg)

The thing I'm working on right now is the fleet status indicators below the ships. It shows resupply status, morale, taiha, combine, and the highest docking and akashi time.

![ss 2015-08-19 at 06 14 47](https://cloud.githubusercontent.com/assets/557312/9353848/31be43ec-469e-11e5-96b5-66e8737fde7f.jpg)

The resupply status and morale is from the `ExpeditionHelper`, the one that also gives list of expeditions the fleet is qualified to go to, the one which outputs `{ w:[....], e:[....] }`

So far works well, however, I'd like to add that if morale is on "warning" state, it will become a timer instead of just text. Timer will indicate the time left to regenerate morale to 49. Naturally, it should be based on the ship with lowest morale since it will take the longest to regen.

@Javran my request for the ExpeditionHelper is that

1) if morale is on "warning" state, meaning morale is included in the `result.w`, it will actually also include the value of the lowest morale. It is your choice if you also wanna do the regen calculation as well, being the number of seconds til all ships are 49-morale. If not, I can do it after receiving results.

2) ~~It would also be nice if when there's at least one ship taiha'd, it will also be included on `result.w`. Taiha status does not need any other value, as long as we know yes or no if there is a taiha within the fleet.~~ No need for taiha indicator, I added them to `Fleet.js`

**Comment by Javran** [comment]
Actually I'm thinking about making each expedition have their own morale requirements.
The idea is the expedition will succeed if every fleet member has a morale `>= 30` **after the fleet goes back**. So the actual morale requirement would be `morale - 3 >= 30` for each fleet member.
As you can see, for expeditions that takes more than 33 minutes (or 36 minutes, a little bit safer as the morale bumps every 3 minutes), morale can basically be ignored (I tested this few times on Expedition 21, 37 and 38, it worked fine)

**Comment by dragonjet** [comment]
ah what I meant it for the general fleet status, not as expedition requirement xD

like when the user is check if it is alright to go on sortie, etc. that If anyone is below 40 morale, it will mark as warning.

or did I misunderstand the result of the current ExpeditionHelper? :laughing:

**Comment by Javran** [comment]
@dragonjet never mind, I misunderstood it as things related to expeditions.

but actually the morale status check is just simply a numeric comparison https://github.com/dragonjet/KC3Kai/blob/master/src/library/helpers/ExpeditionHelper.js#L85 you can do it with javascript.

**Comment by NicolaosGreene** [comment]
Just a not here, shouldn't it not show an Akashi time if the ship is medium damage+ since Akashi can't repair that?

**Comment by NicolaosGreene** [comment]
Also another note as of 65b44ee4927718fa93fb31b691cdbf01603d005f it appears to show the Akashi time to be 1 hp per 10 min, but shouldn't it be 1 hp per 20 min? http://kancolle.wikia.com/wiki/Akashi#Anchorage_Repair_.28.E6.B3.8A.E5.9C.B0.E4.BF.AE.E7.90.86.29 seems to agree with this along with the repair times I have gotten using Akashi overnight.

**Comment by NicolaosGreene** [comment]
Also the morale timer currently seems to be non-functional as well

**Comment by NicolaosGreene** [comment]
After more testing it looks like the Akashi timer is very inconsistent with what the actual repair time should be as is shown below. 
![akashibug](https://cloud.githubusercontent.com/assets/3627763/9363730/b0c035a0-466d-11e5-956a-1261f41140c3.png)
Whereas the actual Akashi time should be 2 hours.

**Comment by Javran** [comment]
@NicolaosGreene yeah I've miscalculated Akashi's repair time. I wasn't aware that there is an accurate formula. Will be working on a fix (today is busy for me, will come a little late though)

**Comment by NicolaosGreene** [comment]
No problem, just wanted to get all the bugs I found in it fixed before it got put in live release

**Comment by Javran** [comment]
@NicolaosGreene I'm not sure if I understand the formula on wiki, referring to the screenshot you took, it takes 2385 docking time to repair your I-19, and `2385 / 1200 = 1.9875 ticks`, but 2 ticks are 40 minutes (if not interrupted) isn't it?

**Comment by NicolaosGreene** [comment]
I guess I was wrong about Akashi, I thought she always did 1 hp per tick, guess I just derped and didn't read it carefully enough. I'll test to confirm that I was just being dumb with that though.

**Comment by Javran** [comment]
@NicolaosGreene yeah what I take from the wiki is:

* it's at least 1 hp per tick
* roughly the same as docking time

My Akashi's repair time is calculated by taking the minimum of

* ceil( docking time / 20 mins ) * 20 mins
* lost HP * 20 mins

**Comment by NicolaosGreene** [comment]
Ya looking at it that should work, though I do recall seeing a 10 min Akashi time at one point, not sure what caused that

**Comment by NicolaosGreene** [comment]
Also funny things happen to the repair time when something is in the dock as is seen below.
![timeroddness](https://cloud.githubusercontent.com/assets/3627763/9365973/26c2c9f0-467a-11e5-97f3-b9a71a9dbe43.png)

**Comment by Javran** [comment]
@NicolaosGreene I thought that should have been fixed yesterday by #682

**Comment by NicolaosGreene** [comment]
@Javran If you can check for damage states you might want to include putting a N/A or something on the Akashi for Medium+ damage since she can do nothing with that.

**Comment by NicolaosGreene** [comment]
Does 65b44ee4927718fa93fb31b691cdbf01603d005f include that? How would I go about checking?

**Comment by NicolaosGreene** [comment]
Nevermind, it does, so obviously it still has some issues, do you need me to get you data?

**Comment by Javran** [comment]
Yeah I think it's included, you can click on "Browse files" (as shown below) to browse the repo at that point, check the last modified time of `src/assets/js/KanColleHelper.js`.

![2015-08-19_150424_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9366189/d4b7b5c6-4683-11e5-92ed-76327b9fc993.png)

**Comment by Javran** [comment]
Your screenshot already has enough info for me to figure out, I can reproduce the problem. Will fix it soon.

**Comment by NicolaosGreene** [comment]
I had the same issue a moment ago with my level 33 I-58 her repair time should have been 2:46 but it gave the same 0:30/20:00 that was in the previous SS.

**Comment by Javran** [comment]
I've found the error source, whenever you see 0:30 / 20:00, it's likely to be resulted from a floating number rounding issue.

**Comment by NicolaosGreene** [comment]
Ah that's good that you found it. It can be annoying to track things down when they are broken.

**Comment by Javran** [comment]
it's actually easy for me to troubleshot, because there are only few "unsafe" places to look at in the programming language I'm working with ;)

**Comment by NicolaosGreene** [comment]
Which language is this written in?

**Comment by Javran** [comment]
It's [here](https://github.com/Javran/purescript-kancolle-helpers), written in PureScript.

**Comment by NicolaosGreene** [comment]
Reminds me a little bit of python with its lack of semicolons or some other end of line marker

**Comment by Javran** [comment]
okay, I need some more data, did you remember the docking time shown when you docked your I-168? I believe it should be either 32:22 or 32:23. 

yeah that language is kind of using the indentation.

**Comment by NicolaosGreene** [comment]
Sorry I do not, I can however send her on a run vs 5-5 to get that for you, would that help?

**Comment by Javran** [comment]
I guess I can get some data myself. It's almost time for daily sortie 2-3 xD

btw this bug can only happen on "SS" types ("SSV" is fine), which has a 0.5 repair factor, I forgot to round the result so it failed when converting to integers..

**Comment by NicolaosGreene** [comment]
I am running the crap outta SS at the moment since I am orel cruising to restock for the event do you just want me to give you repair times when I see error text?

**Comment by Javran** [comment]
yeah, sure :)

**Comment by NicolaosGreene** [comment]
E-4 was not very kind to me, i end up getting the boss to sub 20hp over 8 times before she finally went down >< ended up burning around 9k fuel on that map. So after that I've been orel cruising a lot to restock for the rest of the thing.

**Comment by Javran** [comment]
never mind, just done a 3-2a sortie and got the data. it's now fixed, just wait for the PR :)

**Comment by NicolaosGreene** [comment]
Nice, once it goes through I'll update and watch for more errors

**Comment by Javran** [comment]
I'm still spamming E2 medium looking for Taigei and Unryuu. Just started playing 2.5 months ago, limited resource and don't really have a fleet strong enough for higher difficulties :(

**Comment by NicolaosGreene** [comment]
I started playing during the first day of the winter event and managed to clear it to E-4, that was mad dash there. Though E-1 during that was absolutely godly for a new admiral trying to get ships. Resources were nightmares then and I just barely was able to manage.

**Comment by Javran** [comment]
That's exactly why I'm so obsessed about running expeditions xD. and I have to investigate resources wisely into leveling up ships and spamming on events.

**Comment by NicolaosGreene** [comment]
Ya, that's why I ended up using one of my BP's on Abukuma when she got her Kai Ni since I already had 2 landing craft and run 37 constantly for ammo

**Comment by bamboo3250** [comment]
@Javran So that means this is your first event? That's unfortunate. My first event was Fall 2014, much easier than this but I couldn't proceed beyond E3 (the last stage at that time was E4). Let's revenge on Fall 2015 xD

**Comment by Javran** [comment]
@bamboo3250 yeah it's my first event. I have some confidence for going all-easy difficulty. not sure how far I can go though.

My main force is good enough for getting all-S on daily exercises thanks to spamming 2-5 tons of times (really want a Taigei but haven't got one)

![2015-08-19_170938_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/9369235/e08feb90-4695-11e5-9e6a-6bfd2efe83a5.png)

but I think it's worth it even if I can't finish it, at least I've got some rare ships already xD.

**Comment by bamboo3250** [comment]
Yeah, it's worth to make some attempts for the event. Both new ships and EXP are all good. To keep our sanity, I recommend to consider doing event as for training our top ships by doing it over and over again until the boss is defeated. I applied that to myself and still can keep my calm until the end xD

btw, your fleet is quite really something for a 2.5 month player. With some luck, I think you can finish E7 if your resources allow xD

**Comment by Javran** [comment]
@bamboo3250 thanks! I have to admit resource is the biggest issue for me now. Previously I thought I wasn't going to go for the event so I didn't stock up resources. I just hope expeditions + natural regen would keep things going till the end of the event.

**Comment by Crazyteitoku** [comment]
@Javran what you may also want to consider is also getting a friend to help you do your expeditions whilst you sleep/not playing. Whilst the idea in itself can be seen as a double edged sword but that is another alternative to think about.

**Comment by NicolaosGreene** [comment]
I wasn't too shocked by the fleet but then again I have been told that I am somewhat crazy before. I do think you have a solid fleet there that should definitely be able to carry you through easy if you have the resources, but therein lies the rub. Also you may wish to consider keeping some non-remodeled SS for running 2-3 for fuel if you can't get you hands on Ro-500.

**Comment by Javran** [comment]
@Crazyteitoku might be a  good idea, but I enjoy playing it all by myself :)

@NicolaosGreene I actually have 15 submarines in total, so I can even send few to expeditions while keeping others for tanking all 3-2a damages (poor submarines, I start to feel a little bit sorry ...)

**Comment by NicolaosGreene** [comment]
Ah didn't know, could only see some of your fleet after all

**Comment by NicolaosGreene** [comment]
@Javran I assume you don't have access to 5-4 yet?

**Comment by Javran** [comment]
@NicolaosGreene not yet, still need one last hit to clear 4-4. not sure why you ask this?

**Comment by NicolaosGreene** [comment]
Ah I find 5-4A better than 3-2A even if some damage will accumulate over time, but I find that the ammo efficiency that you get from it can make it worthwhile

**Comment by bamboo3250** [comment]
Me neither. I'm stuck at 5-3 :sob: The difficulty/trolling level of 5-3 should be around E6~E7 in this Summer event.

**Comment by Javran** [comment]
@NicolaosGreene thanks for the suggestion, will try when I get there, but it will take a while xD
for now I'm happy with 3-2a since the exp is really decent.

**Comment by NicolaosGreene** [comment]
Ya 3-2A is by no means bad, and it has the advantage of being almost completely safe, and I agree that 5-3 was very trolly, right up there with the dead end on 5-5

**Comment by Javran** [comment]
@dragonjet sorry that this issue is going a littlle bit off-topic... back to the original question, would you mind giving me some more explanation on what to do with morales?

**Comment by dragonjet** [comment]
I'm still reading the thread, but is @NicolaosGreene's issue resolved now as of #689?

About the original request of adding morale, I also thought I could add it via Javascript on `Fleet.js`, the same with taiha indicators, etc, but I figured that you already have an indicator on your script, and I don't want to duplicate functions, meaning if I do it on JS then it would be a waste not to use your existing function, or is that alright? If we move those indicators to js, we might as well move the resupply indicator so it's on a centralized soruce, meaning we can remove the `w` part of expedition helper?

**Comment by NicolaosGreene** [comment]
@Javran that bug didn't just effect SS it could effect FBB too because my Hiei at lvl 93 at 76/83 showed the error as well as again at 68/83 getting ready to load the new version to see if that fixes things though

**Comment by NicolaosGreene** [comment]
The update did fix the problem for FBB as well it appears, I will let you know if I find more irregularities in it

**Comment by Javran** [comment]
@dragonjet both morale and resupply check is actually done in JS, and this part is not moved into my lib, you can check `src/library/helpers/ExpeditionHelper.js` for detail, should be straightforward.

@NicolaosGreene yeah I was very wrong saying it only affects SS, actually FBB, CVL, CAV, CA and AS are all affected - they share the same repair factor `1.5`. Anyway it should have been fixed.

**Comment by dragonjet** [comment]
@Javran Oh! oh~ I see XD
I did not know it was from that file :laughing: 
will close this now, and I'll move some functions into `Fleet.js`

closing this issue now, if @NicolaosGreene encounter more irregularities, just make a new issue thread XD
