### ISSUE TITLE
different boss node letter

### ISSUE THREAD

**Issue by dustfan** [dragonjet/KC3Kai#69]
hey jet, please take a look at this..
![image](https://cloud.githubusercontent.com/assets/12269598/7584549/47c1d1d0-f8d9-11e4-87f3-482bc7d83e73.png)

both of those sorties reached boss node, but the boss node have different letter depending on the route my subs took.. 

the A-G-M route is the southwestern route from the start of the map, through the submarine node - carrier node - boss node

while B-F-I route is the northwestern route from the start of the map, through the surface ship node - (maelstrom) - Submarine node - boss node.. 

![image](https://cloud.githubusercontent.com/assets/12269598/7584683/08314a90-f8da-11e4-96f3-742a5150fbcc.png)

that B-F-L-M route is the longest route possible, through the surface ship node - (maelstrom) - sub node - carrier node - boss node.. looks like the boss node's letter will be different if i enter it through different pre-boss node.. that L node is the carrier node, it seems that it's letter is changing as well..

**Comment by dragonjet** [comment]
hmm very interesting.

I guess we'll need to disable this feature until we can figure out what the node IDs really represent. Right now what the extensions does is just convert numbers into letters.

e.g.
* Node ID 1 = **A**
* Node ID 2 = **B**
*  Node ID 10 = **J**

**Comment by dustfan** [comment]
yeah.. don't rush it though since it's minor for now.. i can still predict where i'd go from repeated sorties in the map.. i'll report again if there's another bug, thanks for the hardwork :+1:

**Comment by Crazyteitoku** [comment]
Good thing this bug isn't happening in just event only maps. The other day I was talking to Alexanderex and he also agreed that this bug happens on E-5 map. 
The boss node gets assigned two different letters. If going from yasen pre-boss node (Node I on the map) the letter for the boss node is correct (Node N). However if going from Node L on the map the boss node (Node N) becomes (Node T).
Please refer to the following screenshot for more information:
![kc3kai-bossnode-erroneous-lettering-bug-chat](https://cloud.githubusercontent.com/assets/12234182/7666696/3b23a9c8-fc29-11e4-88f4-d8e7c0364cf5.png)

**Comment by ReiFan49** [comment]
i guess the bug scope is not on the boss node only.. 
but the other nodes too.. (Freebranch on E-2 CF Route breaks everything)

![image](https://cloud.githubusercontent.com/assets/9847780/7669574/4032cc20-fca4-11e4-94e1-0d6ef9b618a8.png) (KC3Kai generated)
![image](https://scontent-sin.xx.fbcdn.net/hphotos-xfa1/t31.0-8/s2048x2048/10835408_10204129332620176_6744864226190978135_o.jpg) (my own manual log)

**Comment by bamboo3250** [comment]
I think we have misunderstood those IDs. There is no such node ID from the start but, in my opinion, they are Edge/Route IDs. Depending on the route RNG chooses for us, it will show different IDs even though it ends up in the same node. That would make more sense.

For example:
Route [A->B] = Route 1
Route [A->C] = Route 2
Route [A->D] = Route 3
Route [B->D] = Route 4

So if we reach node D from A->B->D or A->D, it will show the ID 4 or 3 respectively.

And now the question is "Should we just leave it like that or create a table manually to map those route IDs to Node IDs according to Wikia to be more user-friendly?"

**Comment by dragonjet** [comment]
hm, this is a good approach.

Though originally I'm planning to leave it as is, but one thing we can do is change its name from "node letter", to somewhere along the lines of "movement code" - just so people won't mistake it with wikia map letters.

although it seems the only thing people wanted from the feature is the enemy formation, not the node letters specifically. so improving on showing enemy encounter on each node rather than identifying the node name, would probably be the best way to go from here.

**Comment by bamboo3250** [comment]
I also want a feature to foresee the enemy fleet before selecting the formation. Maybe I will give it a try first then we will see how we can develop it further?

**Comment by dragonjet** [comment]
sure thing

**Comment by dragonjet** [comment]
one thing though, Electronic Observer has this feature right now and what they do is, remember the enemy ID you got from the compass call, then when you start battle, associate that with the remembered enemy ID, and store it on your local data. Next time you visit, just check if that enemy ID exists in the records and show the formation stored

**Comment by bamboo3250** [comment]
@dragonjet As I noticed, for now the enemy_id is not stored in the database in neither sortie nor battle. Is it stored somewhere else or I missed it? 
Is there anything to take note if I want to change the database like adding more attributes into it?

**Comment by dragonjet** [comment]
ah I was talking about [Electronic Observer](https://github.com/andanteyk/ElectronicObserver) who are the ones already storing enemy IDs and formations on their local database. KC3改 doesn't have it yet. Enemy IDs are just shown, but not remembered currently.

When the database is change, you just need to add another `this.database.version` on the `init()` of `/src/library/classes/Logging.js`. This is to make sure the IndexedDB library, *Dexie* correctly upgrades the local user schema from whatever version he previously had.
