### ISSUE TITLE
[Bug] Critical Icon

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#695]
On the Combined Fleet, when a fleet sortie in combined fleet get taiha'd, the panel will update to "Critical" on below, but the icon still a green checkmark:
![screen shot 2015-08-20 at 18 33 13](https://cloud.githubusercontent.com/assets/13522800/9380426/08382632-476b-11e5-9ff2-1593cbdee73e.png)

While on each individual page, all is working fine:
![screen shot 2015-08-20 at 18 32 38](https://cloud.githubusercontent.com/assets/13522800/9380429/0a628024-476b-11e5-8e3b-4987cd38610c.png)

The icon in Combined Fleet will change depending to the last condition/visited:
![screen shot 2015-08-20 at 18 33 21](https://cloud.githubusercontent.com/assets/13522800/9380431/0f16f1e0-476b-11e5-9eda-1cf621e4287f.png)
![screen shot 2015-08-20 at 18 35 54](https://cloud.githubusercontent.com/assets/13522800/9380432/0f54e4fa-476b-11e5-88ca-e0741c206d87.png)
![screen shot 2015-08-20 at 18 36 05](https://cloud.githubusercontent.com/assets/13522800/9380433/0f82efe4-476b-11e5-946f-ff16d8dae071.png)

In my case, here's the chronology:
- I sortie to E4, to get my 1st fleet damaged. Then the Combined Fleet mode shows like in the first picture
- On the panel, I navigate to the 1st fleet display. Result shown in second picture.
- Getting back to the Combined Fleet mode, we got what displayed in third picture.
- Next, I navigate to the 4th fleet display as shown on the fourth picture.
- Finally, we got what is displayed in the last picture: the icon beside "Critical" changed back into checklist

**Comment by ethrundr** [comment]
@dragonjet that was fast :scream:

**Comment by nicky008** [comment]
@dragonjet just let you, @ethrundr, be a guinea pig.

(Joking... :yum: )
