### ISSUE TITLE
[Quest tracking] Bd2 strange behavior

### ISSUE THREAD

**Issue by bcc32** [dragonjet/KC3Kai#700]
Bd2: Destroy the Main Force of the Enemy Fleet

On the wiki (and in KC3Kai) this is interpreted to mean sinking an enemy flagship (which looks correct), but I noticed that this Quest was being cleared when I was Orel cruising even though I wasn't sinking any flagships.  I'm not really sure what the exact conditions for this quest are, but for what it's worth there seems to be some sort of inaccuracy.

**Comment by NicolaosGreene** [comment]
I believe this is already being talked about in #552

**Comment by bcc32** [comment]
Ah, that's right.  You can go ahead and close this one as a dupe then.
