### ISSUE TITLE
Resources for next node are not showing 

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#702]
When the next node you are proceeding to is a resource node the panel used to tell you how much you were going to get, now it just remains blank, is this is a bug or an intentional change? Version is bb3a3e5e3cbc36d7955374fcd1d81df69fd9328a.

**Comment by dragonjet** [comment]
can you get a screenshot? it's working for me right now, at least for event maps

**Comment by ethrundr** [comment]
It was working for me previously on 2-3 as well.
Gonna test it after this.

**Comment by NicolaosGreene** [comment]
This is what I got at 2-3 when I was running it with Ro-500 with the version I listed earlier.
<img width="551" alt="reserr" src="https://cloud.githubusercontent.com/assets/3627763/9400827/f709dba0-478b-11e5-82b5-e3eb063d871c.png">

**Comment by dragonjet** [comment]
now that you mention it, I remember this happened to me one time during the event, but I figured that it was the battle info for next node even if I was at a resource one, signed it off as a mere confusion from my part.

hm not sure if I can test this for v18 release earlier though. if anyone else interested in checking the bug, that would be great XD

**Comment by NicolaosGreene** [comment]
How would I go about checking it?

**Comment by dragonjet** [comment]
the response data for that node, specifically the **api_req_map/next**

**Comment by NicolaosGreene** [comment]
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_rashin_flg":1,"api_rashin_id":2,"api_maparea_id":2,"api_mapinfo_no":3,"api_no":4,"api_color_no":2,"api_event_id":2,"api_event_kind":0,"api_next":1,"api_bosscell_no":11,"api_bosscomp":1,"api_comment_kind":0,"api_production_kind":0,"api_airsearch":{"api_plane_type":0,"api_result":0},"api_itemget":{"api_usemst":4,"api_id":2,"api_getcount":35,"api_name":"","api_icon_id":2}}}

**Comment by NicolaosGreene** [comment]
let me know if you need more than one

**Comment by dragonjet** [comment]
ah thanks, found the problem :+1:
