### ISSUE TITLE
[Bug?] Regarding Timer in Morale Status

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#704]
As shown below:
![screen shot 2015-08-21 at 14 25 12](https://cloud.githubusercontent.com/assets/13522800/9401845/87e7bdfc-4810-11e5-8a64-ae949c935263.png)
The timer is showing 00:00:33.

I suppose the timer here should track the one with lowest morale, and calculate how long will it need to reach back to at least 40, am I right?

If this is the case, then the timer should show around 00:33:00 instead of 00:00:33, since the lowest is on Haruna (9 morale), and she needs 11 ticks to get back to at least 40, where each tick will recover 3 morale per 3 minutes (not 3 seconds).

Lastest pull: 5cae780

---

ps: OOT question, what is that "Fit" button used for?

**Comment by dragonjet** [comment]
ah you're right it should be number of minutes not seconds. I guess we'll need to multiply it by 60

The fit automatically resizes your window to fit the game screen without borders, try maximize your window and click it. You will need to click multiple times though to get it right

**Comment by ethrundr** [comment]
@dragonjet it works on API only, or DMM as well? since I always play through DMM...

**Comment by dragonjet** [comment]
ah, only works on API

I'm keeping morale timer as open on #582 until I make it countdown.
Though I'm not sure if I can start it by tonight XD
