### ISSUE TITLE
[Bug] Morale Timers: Part 2

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#710]
Since the regenerable morale was capped in 49, when a morale minimum in the setting is being set above 49, the timer should capped at the timer needed from the lowest morale to reach 49. The other alternative is to implement an input filtering on the settings, to reject any input value greater than 49.

In my test case, I-58's morale currently is 6, thus to reach 49, it'll need 15 ticks (45 morale), which will takes 45 minutes to be completed. However, in the timer it was stated 1 hour 36 minutes (96 minutes, or equivalent to 32 ticks), which is the timer needed to reach 100 morale as I set on the menu, assuming it'll stay regenerate by 3 points per 3 minutes after 49:
![screen shot 2015-08-22 at 02 25 46](https://cloud.githubusercontent.com/assets/13522800/9414720/a9cf8aac-4875-11e5-95b3-d27d1f510432.png)

Other test case, now using with fully sparkled fleet, which morale all above 50, and the timer still giving red status with timer to reach the morale 100:
![screen shot 2015-08-22 at 02 46 46](https://cloud.githubusercontent.com/assets/13522800/9415362/b2f20700-4879-11e5-85f8-c09fb4c2a86c.png)

Latest pull at 0276966

**Comment by NicolaosGreene** [comment]
Seems silly, but it accepts negative numbers too, it might want to be filtered 0-49.

**Comment by ethrundr** [comment]
Ah I haven't test with the negatives. So yeah, we should put a filter than, to rejects any number other than 0 to 49.

**Comment by dragonjet** [comment]
ah you;re right, we should filter the settings to be only 1-49

**Comment by dragonjet** [comment]
@ReiFan49  this was fixed as of 67108fa52fd82bbc699784b6253b88473fe04242?

**Comment by ReiFan49** [comment]
@dragonjet umm, it just config interface-based value bounding,
not the full hard-limiting from save and loads though lol,

**Comment by dragonjet** [comment]
It's alright :v
