### ISSUE TITLE
[Bug] Boss HP Bar: Should be hidden upon "No Difficulty Selected"

### ISSUE THREAD

**Issue by ethrundr** [dragonjet/KC3Kai#718]
Based on the report I got from my friend in FB:
![kc3kai9999](https://cloud.githubusercontent.com/assets/13522800/9425570/ea6c0fc4-494f-11e5-8101-1fc02294bd05.jpg)

When you haven't choose a difficulty yet in the event map, the sortie history page will show the boss HP bar as 9999 / 9999. In my opinion, we should not show the bar first before the user select a difficulty to the map. Rather, put a placeholder with some text, like "No Difficulty" or something similar.

**Comment by bamboo3250** [comment]
Actually, it happens when the player goes to the sortie page (even before selecting difficulty). One way we can solve it is not showing the bar when it's 9999 (but if there is a map having a boss HP like that in the future, ...) xD

**Comment by ethrundr** [comment]
Well, from what I see, we can detect whether the player already select the difficulty, aren't we?
Why don't use it as to detect whether a player has picked difficulty or not.
As far as I remember, it's from the `api_selected_rank`, and the value should be 1 (easy), 2 (normal) or 3 (hard). CMIIW

**Comment by bamboo3250** [comment]
Yeah, that also works as long as we know which value the `api_selected_rank` is when the player hasn't selected the difficulty yet. We need someone who hasn't gone to E7 yet.

**Comment by ethrundr** [comment]
We have @ReiFan49. He's still at around E2 or E3 if I'm not mistaken XD

**Comment by bamboo3250** [comment]
Oh that would be perfect then xD

**Comment by NicolaosGreene** [comment]
I haven't started E-6 yet, what do you need?

**Comment by NicolaosGreene** [comment]
Where do I need to go and which network packet am I going to look at?

**Comment by bamboo3250** [comment]
@NicolaosGreene You can go to this screen, select `map_info` then copy the data in `Preview` tab like below.

![screen shot 2015-08-23 at 7 18 04 am](https://cloud.githubusercontent.com/assets/8078323/9426255/44779e68-4967-11e5-8a1c-86f83144ffe4.png)

**Comment by NicolaosGreene** [comment]
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":[{"api_id":11,"api_cleared":1,"api_exboss_flag":0},{"api_id":12,"api_cleared":1,"api_exboss_flag":0},{"api_id":13,"api_cleared":1,"api_exboss_flag":0},{"api_id":14,"api_cleared":1,"api_exboss_flag":0},{"api_id":15,"api_cleared":1,"api_exboss_flag":0},{"api_id":16,"api_cleared":1,"api_exboss_flag":0},{"api_id":21,"api_cleared":1,"api_exboss_flag":0},{"api_id":22,"api_cleared":1,"api_exboss_flag":0},{"api_id":23,"api_cleared":1,"api_exboss_flag":0},{"api_id":24,"api_cleared":1,"api_exboss_flag":0},{"api_id":25,"api_cleared":1,"api_exboss_flag":0},{"api_id":31,"api_cleared":1,"api_exboss_flag":0},{"api_id":32,"api_cleared":1,"api_exboss_flag":0},{"api_id":33,"api_cleared":1,"api_exboss_flag":0},{"api_id":34,"api_cleared":1,"api_exboss_flag":0},{"api_id":35,"api_cleared":1,"api_exboss_flag":0},{"api_id":41,"api_cleared":1,"api_exboss_flag":0},{"api_id":42,"api_cleared":1,"api_exboss_flag":0},{"api_id":43,"api_cleared":1,"api_exboss_flag":0},{"api_id":44,"api_cleared":1,"api_exboss_flag":0},{"api_id":45,"api_cleared":1,"api_exboss_flag":0},{"api_id":51,"api_cleared":1,"api_exboss_flag":0},{"api_id":52,"api_cleared":1,"api_exboss_flag":0},{"api_id":53,"api_cleared":1,"api_exboss_flag":0},{"api_id":54,"api_cleared":1,"api_exboss_flag":0},{"api_id":55,"api_cleared":1,"api_exboss_flag":0},{"api_id":61,"api_cleared":0,"api_exboss_flag":0},{"api_id":311,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":750,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":312,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":1050,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":313,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":2100,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":314,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":3500,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":315,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":2400,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":316,"api_cleared":0,"api_eventmap":{"api_now_maphp":9999,"api_max_maphp":9999,"api_state":1,"api_selected_rank":0},"api_exboss_flag":0}]}
This what you need?

**Comment by ethrundr** [comment]
@NicolaosGreene yeps

@bamboo3250 
<pre><code>{"api_now_maphp":9999,"api_max_maphp":9999,"api_state":1,"api_selected_rank":0},"api_exboss_flag":0}</code></pre>
Yeps, the `api_selected_rank` for the newly unlocked map (without any difficulties selected) is 0. I think we can use it to replace the HP bar with a placeholder.

**Comment by NicolaosGreene** [comment]
Alright since that is what you needed I am going to start E-6 now

**Comment by dragonjet** [comment]
as usual @NicolaosGreene provides :laughing: 
seems any data we need is easily provided in the condition that we need, almost miraculous XD

**Comment by NicolaosGreene** [comment]
I actually almost started E-6 before I read this issue ><, part of why I go through issues before I start new things.

**Comment by ethrundr** [comment]
o.o
but...but... your timing is almost always perfect, when we need the data, you have it XD

**Comment by ReiFan49** [comment]
working on this.. but my E2 is already at Normal, not at "No Diff"
![yee](https://cloud.githubusercontent.com/assets/9847780/9426530/06cf8600-4973-11e5-92e9-77030fc234c9.jpg)

**Comment by NicolaosGreene** [comment]
@ReiFan49 use grab if you want to take an SS

**Comment by NicolaosGreene** [comment]
Will be in utilities in the applications folder

**Comment by NicolaosGreene** [comment]
You will have to use preview to convert it from .tiff to .png so you can post it here. On yours I think the option is file>export as if that is Maverick like I think it is from the picture there.

**Comment by NicolaosGreene** [comment]
Also @ethrundr my timing just happens to be lucky :sweat_smile:. I happen to be on a lot since I have a ton of health issues so I often see some these things and I have enough working knowledge of thing to be able to investigate them. That and I hate leaving things broken that I can help fix.

**Comment by ethrundr** [comment]
@NicolaosGreene lol @ReiFan49 was taking a picture of my laptop, it's not his XD

**Comment by NicolaosGreene** [comment]
Ah misunderstood that ><. Have run into people who have had no idea about grab before though, so I though it was just a case of that. Picture had a lot of junk on it so it was hard to see details.

**Comment by ethrundr** [comment]
Rather than grab, I prefer using Cmd+Shift+4, since it's on png already

**Comment by NicolaosGreene** [comment]
Fair enough, but most the time I'm going to crop my SS so I don't mind using grab

**Comment by NicolaosGreene** [comment]
Course the mac I'm using at this point is almost a relic, it's the MB063LL/B (Macbook Late 2007) with the memory upgraded.

**Comment by ethrundr** [comment]
lol XD pretty much figures then....

**Comment by NicolaosGreene** [comment]
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":[{"api_id":11,"api_cleared":1,"api_exboss_flag":0},{"api_id":12,"api_cleared":1,"api_exboss_flag":0},{"api_id":13,"api_cleared":1,"api_exboss_flag":0},{"api_id":14,"api_cleared":1,"api_exboss_flag":0},{"api_id":15,"api_cleared":1,"api_exboss_flag":0},{"api_id":16,"api_cleared":1,"api_exboss_flag":0},{"api_id":21,"api_cleared":1,"api_exboss_flag":0},{"api_id":22,"api_cleared":1,"api_exboss_flag":0},{"api_id":23,"api_cleared":1,"api_exboss_flag":0},{"api_id":24,"api_cleared":1,"api_exboss_flag":0},{"api_id":25,"api_cleared":1,"api_exboss_flag":0},{"api_id":31,"api_cleared":1,"api_exboss_flag":0},{"api_id":32,"api_cleared":1,"api_exboss_flag":0},{"api_id":33,"api_cleared":1,"api_exboss_flag":0},{"api_id":34,"api_cleared":1,"api_exboss_flag":0},{"api_id":35,"api_cleared":1,"api_exboss_flag":0},{"api_id":41,"api_cleared":1,"api_exboss_flag":0},{"api_id":42,"api_cleared":1,"api_exboss_flag":0},{"api_id":43,"api_cleared":1,"api_exboss_flag":0},{"api_id":44,"api_cleared":1,"api_exboss_flag":0},{"api_id":45,"api_cleared":1,"api_exboss_flag":0},{"api_id":51,"api_cleared":1,"api_exboss_flag":0},{"api_id":52,"api_cleared":1,"api_exboss_flag":0},{"api_id":53,"api_cleared":1,"api_exboss_flag":0},{"api_id":54,"api_cleared":1,"api_exboss_flag":0},{"api_id":55,"api_cleared":1,"api_exboss_flag":0},{"api_id":61,"api_cleared":0,"api_exboss_flag":0},{"api_id":311,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":750,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":312,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":1050,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":313,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":2100,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":314,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":3500,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":315,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":2400,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":316,"api_cleared":1,"api_eventmap":{"api_now_maphp":0,"api_max_maphp":2700,"api_state":2,"api_selected_rank":3},"api_exboss_flag":0},{"api_id":317,"api_cleared":0,"api_eventmap":{"api_now_maphp":9999,"api_max_maphp":9999,"api_state":1,"api_selected_rank":0},"api_exboss_flag":0}]}
Having cleared E-6 I got the same selected rank being 0 E-7 now, just to confirm that this is the case

**Comment by ReiFan49** [comment]
nah, sounds like i need to repatch this back, as 9999 HP should not be shown after selecting a difficulty too... (because the extension caches the `mapinfo` and `mapinfo` is not called for every difficulty selection, only `select_eventmap_rank` that updates the difficulty...)
