### ISSUE TITLE
Panel: Supply Gauges

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#72]
:white_check_mark: Add fuel/ammo supply gauges to ships
:white_large_square: Possibly put flashing animation to unsupplied ships
:white_large_square: Apply gauges on normal mode

or if the battle mode if going to be the main interface, this entry may be closed once it's implemented (refers to #187)

**Comment by McDohl** [comment]
bump, incase forgot

**Comment by dragonjet** [comment]
ah yes you're right I totally forgot these. but im thinking people might still want supply gauges on normal mode, not just during sorties. the problem comes in when im in the middle of going to th exped page but i forgot if I already resupplied the team and want a quick glance. We still need to have a mechanism for normal mode to see supply gauge

**Comment by dragonjet** [comment]
Secondary concern will be addressed on #187 

The main issue of adding supply gauges on panel is done on latest versions.

Closing
