### ISSUE TITLE
[Bug] Toggling eLoS displays the next fleet's values

### ISSUE THREAD

**Issue by arghblargh** [dragonjet/KC3Kai#721]
natsuiro.js Line 78: var fl = (selectedFleet < 5) ? [selectedFleet] : [0,1];

Should be [selectedFleet - 1] instead of [selectedFleet]

**Comment by dragonjet** [comment]
@ReiFan49

**Comment by ethrundr** [comment]
@ReiFan49 is currently cosplaying XD

**Comment by McDohl** [comment]
that's what I Pm'ed u at wikia chat this morning but you not read it :sob: @dragonjet

**Comment by nicky008** [comment]
@McDohl I think I saw this missing since the beginning of Natsuiro-era. Have been waiting someone will post new pics, but... never mind :smirk:

**Comment by dragonjet** [comment]
ah yes, is it because the los icon is cropped into a circle? or does the icon not change at all? xD

It becomes confusing when you click and you don't know which formula you're currently viewing, I experienced this too :v

**Comment by arghblargh** [comment]
The icon doesn't change at all.

Also the los toggle is completely broken for combined fleets, and will only show the los for the 2nd fleet.
The foreach function calculates the los for fleets 1 and 2 separately, but never adds them together, so the text just shows the los for fleet 2.

**Comment by arghblargh** [comment]
Took the liberty of fixing it myself.

From line 75:
```javascript
// eLoS Toggle
$(".summary-eqlos").on("click",function(){
	ConfigManager.scrollElosMode();
	var img = (ConfigManager.elosFormula == 1) ? "lst" :
			  (ConfigManager.elosFormula == 2) ? "lse" :
			  								   "ls";
	$(".summary-eqlos .summary_icon img").attr("src", "../../../../assets/img/stats/"+img+".png");
	var los = (selectedFleet < 5) ? PlayerManager.fleets[selectedFleet-1].eLoS() : 
									PlayerManager.fleets[0].eLoS()+PlayerManager.fleets[1].eLoS();
	$(".summary-eqlos .summary_text").text( Math.round(los * 100) / 100 );
}).addClass("hover");
```

And the unreadable version:

```javascript
// eLoS Toggle
$(".summary-eqlos").on("click",function(){
	ConfigManager.scrollElosMode();
	$(".summary-eqlos .summary_icon img").attr("src", "../../../../assets/img/stats/"+(ConfigManager.elosFormula == 1) ? "lst" : (ConfigManager.elosFormula == 2) ? "lse" : "ls"+".png");
	$(".summary-eqlos .summary_text").text( Math.round(((selectedFleet < 5) ? PlayerManager.fleets[selectedFleet-1].eLoS() : PlayerManager.fleets[0].eLoS()+PlayerManager.fleets[1].eLoS() * 100) / 100 );
}).addClass("hover");
```

**Comment by dragonjet** [comment]
ah thanks~ you can make a pull request anytime :+1:

**Comment by ReiFan49** [comment]
sorry >A<
i cannot connect to internet at my home orz,
after cosplaying yesterday lol, i'll post somewhere on another pull request lol
