### ISSUE TITLE
Strategy Room: Enhanced Help/FAQ

### ISSUE THREAD

**Issue by dragonjet** [dragonjet/KC3Kai#731]
* Create a built-in help/FAQ for each strategy room page, not just a link to the github wiki
* Button toggles the FAQ on/off, default hidden

**Comment by nicky008** [comment]
I wonder who drew that fairy... :smirk:

**Comment by dragonjet** [comment]
ah he is on our dev list for a long time, but the image hasn't been used since forever XD

**Comment by nicky008** [comment]
Oh..Okay... Not bad though... :grin:
