### ISSUE TITLE
KancolleHelpers error while requesting a 夜戦

### ISSUE THREAD

**Issue by ReiFan49** [dragonjet/KC3Kai#732]
![image](https://cloud.githubusercontent.com/assets/9847780/9467484/449107f8-4b66-11e5-96cf-e6945e79941a.png)

(just fetched all of the commit today)

**Comment by dragonjet** [comment]
I'm not sure if this is because of my latest copy of `KanColleHelpers.js` on 44f14ae085a6a49d9eae792ec77f53badd3beb03 I only copied http://javran.github.io/assets/KanColleHelpers.js raw

Maybe @Javran can create pull request of the latest one?

**Comment by Javran** [comment]
@dragonjet that's already the latest version.

for now I have no idea about this error @ReiFan49 do you have some sample data?

**Comment by ReiFan49** [comment]
nah, it's about normal sortie night battle request,

what i have done
```
src/assets/js/KanColleHelpers.js                   |   6 +-
```

orel time indeed
```JSON
{
  "api_result":1,
  "api_result_msg":"Success!",
  "api_data":{
    "api_deck_id":"3",
    "api_nowhps":[-1,9,15,15,-1,-1,-1,88,0,40,0,0,28],
    "api_ship_ke":[-1,525,512,511,509,509,504],
    "api_ship_lv":[-1,1,1,1,1,1,1],
    "api_maxhps":[-1,13,15,15,-1,-1,-1,88,85,90,58,58,28],
    "api_eSlot":[
      [520,517,524,-1,-1],
      [519,523,516,-1,-1],
      [509,512,525,-1,-1],
      [505,513,525,-1,-1],
      [505,513,525,-1,-1],
      [502,513,-1,-1,-1]
    ],
    "api_eKyouka":[
      [0,0,0,0],
      [0,0,0,0],
      [0,0,0,0],
      [0,0,0,0],
      [0,0,0,0],
      [0,0,0,0]
    ],
    "api_fParam":[
      [12,55,0,20],
      [9,69,0,19],
      [11,69,0,18]
    ],
    "api_eParam":[
      [0,0,40,55],
      [0,0,30,40],
      [65,0,70,70],
      [32,32,16,28],
      [32,32,16,28],
      [8,24,8,9]
    ],
    "api_touch_plane":[-1,-1],
    "api_flare_pos":[-1,-1],"api_hougeki":{"api_at_list":[-1,1,2,3,12],"api_df_list":[-1,[7,7],[12],[9,9],[3]],"api_si_list":[-1,[15,15],[15],[15,14],[-1]],"api_cl_list":[-1,[1,1],[0],[1,1],[0]],"api_sp_list":[-1,3,0,3,0],"api_damage":[-1,[89,81],[0],[94,83],[0]]}}}
```

**Comment by ReiFan49** [comment]
now i get it.

i'm having a **Combined Fleet**,
but i sortie with **Orel Runner**.

**Comment by Javran** [comment]
ah I see, maybe my lib was looking for `xxx_combined` fields but failed.
Is it possible to distinguish between combined fleets and normal fleets when going sortie?
my lib is not designed to handle both cases (maybe it's possible, but I need some time to think about it).

**Comment by dragonjet** [comment]
ah dont worry, I'll fix this, saw it

**Comment by dragonjet** [comment]
oh I saw it late but it seems @ReiFan49 already fixed this :open_mouth:
