### ISSUE TITLE
[Feature request] Tooltips on drops in sortie history

### ISSUE THREAD

**Issue by NicolaosGreene** [dragonjet/KC3Kai#739]
If you are not familiar with the face of the shipgirl that dropped it can be difficult to identify just by the portrait in the sortie history and as far I can tell there is no way to tell for certain who the shipgirl is except by the portrait.

**Comment by Javran** [comment]
when crafting ships, if you move over the shipgirl's icon, the tooltip shows her name.
my game server is getting catbombed, cannot verify if the tooltip is also there for battle tab.

**Comment by NicolaosGreene** [comment]
It is there on the panel, I more meant in the strategy room, I was going to fill in some of the holes in the wiki's drop tables for the events but I didn't recognize the portraits in sortie history and I thought this was something of an oversight.

**Comment by McDohl** [comment]
I believe its done already https://github.com/McDohl/KC3Kai/commit/583c5d0494143b8d1f04538c7fb8f354dbf96683

**Comment by NicolaosGreene** [comment]
Indeed, it is working now, closing.
