### ISSUE TITLE
Event sorties history

### ISSUE THREAD

**Issue by McDohl** [dragonjet/KC3Kai#745]
I lost my event history after using friend's API link at kc3kai. 

after get my new API link , only event history was sent to abyssal fleet and never seen again

**Comment by Crazyteitoku** [comment]
You probably should have used an alternative browser when playing your friend's or anyone else's KC really. Just saying. :disappointed:

**Comment by LostLogia4** [comment]
Should've backed up your indexdb directory, iinm your history is stored there.

**Comment by McDohl** [comment]
I don't know what happen but it just re-appear today. will keep it in mind. or maybe I should install another chromium browser :sweat_smile:

**Comment by dragonjet** [comment]
strategy room shows data for currently logged in user, but doesn't delete on new players. it will reappear when you login to your own account :laughing:
