### ISSUE TITLE
api link in incognito 

### ISSUE THREAD

**Issue by c933103** [dragonjet/KC3Kai#749]
soneone in wimia chat mentioned that if he run kc3kai in incognito, click play in api, it would open a new tab/window that is not incognito. Can that be fix?

**Comment by LostLogia4** [comment]
What for? Incognito mode can't use local cache.

**Comment by dragonjet** [comment]
By default, extensions are disabled in incognito, unless you force it to. This is because of unwanted side effects such as that.

![ss 2015-09-04 at 11 53 58](https://cloud.githubusercontent.com/assets/557312/9676279/a89eac7c-52fb-11e5-845a-41e32f6fea17.png)

marking as wontfix
