### ISSUE TITLE
[Bug] Remodelling a flagship, makes whole fleet disappear

### ISSUE THREAD

**Issue by ReiFan49** [dragonjet/KC3Kai#756]
![image](https://cloud.githubusercontent.com/assets/9847780/9701687/bea702b2-545e-11e5-869d-0036cc0aeb69.png)
![image](https://cloud.githubusercontent.com/assets/9847780/9701690/c8f14df4-545e-11e5-8b4f-3d1481de8298.png)

**Comment by dragonjet** [comment]
dupe #680 :laughing:

**Comment by ReiFan49** [comment]
lol xD
