### ISSUE TITLE
Bugs found in Events sortie debrief

### ISSUE THREAD

**Issue by BWinkKeyShellDinkInc** [dragonjet/KC3Kai#81]
The following bugs are found under the Events section of Strategy Room.

* Repeated main fleet composition on pre/boss support fleet in event debrief and wrong fleet composition on pre/boss support fleet

Pictures:
1: http://i.imgur.com/71jMBYy.png
2: http://i.imgur.com/5cuBpN2.png
3: http://i.imgur.com/feM5GLE.png

I suspect it is due to KC3(require confirmation) is coded to read fleet 2 as "PreB Sup" and 3 as "Boss Sup". I deduced this as I remembered that the fleet composition for "Boss Sup" in Pic 1 is actually my fleet for expedition 12#, my actual "PreB Sup" composition is the composition for "Boss Sup" in Pic 3 and actual "Boss Sup" composition is the composition for "PreB Sup" in Pic 2. Hence it may explain the reason for repeated or wrong fleet composition. I will conduct a few tests to confirm on it and I will submit my findings here.

* Repeated fleet composition of older sorties debrief on newer sorties debrief 

I found another bug while writing the report for the one above. The following pictures are the steps I used to recreate it.

1. http://i.imgur.com/evtDy9O.png
2. http://i.imgur.com/HQprdxd.png
3. http://i.imgur.com/prG2CXw.png
4. http://i.imgur.com/G9VDAWg.png

Pic 4 just shows that other debriefs are also affected after opening debrief 5# (the older, if not the oldest, event debrief in my strategy room). This can be fixed just by refreshing the page.

**Comment by BWinkKeyShellDinkInc** [comment]
I conducted two test on "Repeated main fleet composition on pre/boss support fleet in event debrief and wrong fleet composition on pre/boss support fleet" 

Hypothesis: Fleet 2 is read as "PreB Sup", Fleet 3 is read as "Boss Sup" 
Test 1:
* Fleet compositions:

Fleet 2: http://i.imgur.com/DIAlHDL.png (Main Fleet)
Fleet 3: http://i.imgur.com/v6XUJVo.png (PreB Sup)
Fleet 4: http://i.imgur.com/4Ln0A4B.png (Boss Sup)
* Expeditions sent:
http://i.imgur.com/gUePDmL.png
* Sortie Debrief:
http://i.imgur.com/br1CSmm.png

Test 1 does support my hypothesis as Fleet 3 is read as a "Boss Sup" when it is actually sent as a "PreB Sup", Fleet 2 is read also read as "PreB Sup" and Fleet 4 is left out.

Test 2:
* Fleet compositions:

Fleet 1: http://i.imgur.com/y0RSfMJ.png (Main Fleet)
Fleet 2: http://i.imgur.com/5gabcQb.png (PreB Sup)
Fleet 3: http://i.imgur.com/LrQlk7r.png (Expedition Fleet)
Fleet 4: http://i.imgur.com/PiK2Ont.png (Boss Sup)
* Expedition sent:
http://i.imgur.com/zuyv44L.png
* Sortie Debrief:
http://i.imgur.com/zFsIcrP.png

Again, Test 2 does support my hypothesis. However, I was surprised by the repeating Main fleet composition on "PreB Sup" composition even though the fleet 1 is the main fleet. I can't find any reasoning with that. I would have though the repeating Main fleet composition is due to KC3 double reads it as a "Main Fleet" and "PreB Sup" when Fleet 2 is send out to sortie.

That concludes my findings 

On another interesting find, regarding second bug thats listed above. It wasn't due to the old event sortie debrief but any debrief with only the main fleet that is sent out that triggers the bug to occur.

Evidence:
1. http://imgur.com/kVwBcCH.png (Sortie 61 is one of the latest event sortie i did)
2. http://i.imgur.com/Xin2iA1.png (Before)
3. http://i.imgur.com/oNjqOZ8.png
4. http://i.imgur.com/hV3BMpv.png (After)

**Comment by dragonjet** [comment]
ah thank you so much for this great testing, it will take time for me to check and study this though, will try to line it with v11 or v12 after the Quest Flowchart

**Comment by BWinkKeyShellDinkInc** [comment]
Heard you are working on sortie menu. Would bump this so you might fix it while at it.

**Comment by dragonjet** [comment]
ah thanks for the heads up~
