### ISSUE TITLE
[Bug report] Uncaught TypeError: app.Logging.get_event is not a function

### ISSUE THREAD

**Issue by Crazyteitoku** [dragonjet/KC3Kai#83]
**Date Seen**:
17-05-2015

**Version**':

**KC3 Kai v008 (git build) ID**: jljpednjlkddlmahfoljfjlnbollampe 
**KC3 Kai v008 git revision**: f89e960
**Browser**: Chromium 64bit (currently on: 42.0.2311.135 (Developer Build 575981d43c6dc74b1443ca77e015c218daf050dd Linux))
**OS** :Archlinux 64bit (currently on: Linux: 4.0.1-1-ARCH)

**Bug Description**:
Error found during event sortie.

Screenshots are provided below.

**Severity**:
Minor (?).

**Steps to Reproduce**:
1. Sortie your fleet to event maps. Ideally to E-6.

**Actual Behavior**:
Unknown. I do not know what is actually happened other than seeing the error.

**Expected Behavior**:
Unknown - possibly error to not show up.

**Troubleshooting/Testing Steps Attempted**:
Tried to play the game normally which appears to have impacted nothing.

**Workaround**:
None.

**Attachments**:
![kc3kai-008-bug](https://cloud.githubusercontent.com/assets/12234182/7666714/f6aa834c-fc29-11e4-9afb-dc691dc27e47.png)

**Comment by dragonjet** [comment]
wait CT, seem the screenshot is different from the title XD

which error was it xD

**Comment by Crazyteitoku** [comment]
Hi DJ, unfortunately I have no developer console trace of it. The bug hasn't resurfaced but also the event is over so I guess this is pretty much the end of the bug being visible.

The screenshot I do believe is the right one.

**Comment by dragonjet** [comment]
Yep I remember I removed `app.Logging.get_event` then pushed it in one of the commits which are not yet publish-ready. Switched to a different function call later on so should not be a problem now
