### ISSUE TITLE
Minor damage ship border does not change

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#86]
So, if a ship gets moderately or heavily damaged, the little gray "border" around her image turns orange or red to match the new condition; however, if she gets minor damage, the HP bar turns yellow but the border around her image stays gray.

**Comment by dragonjet** [comment]
hm this was actually intended. is it preferrable to have yellow background as well? If that's the case, we should also have the green state as green border for consistency, not the current dark border

**Comment by AlanSchaeffer** [comment]
If it is intentional, then I don't think it is necessary to change. I just thought it was a bug because all the other states (other than ok) would change the border.

**Comment by dragonjet** [comment]
ah sure no prob, will retain it for now as dark borders until one more reports it. thanks~
