### ISSUE TITLE
Learn enemy node compositions

### ISSUE THREAD

**Issue by AlanSchaeffer** [dragonjet/KC3Kai#88]
So, when the compass prediction tells us where we are going, it also includes an enemy ID normally. Is that ID unique?
If it is, then this:
Have KC3 remember the enemy composition associated to that ID; next time you get a node prediction, it could show you a thumbnail of the enemy formation you're going up against.
Now, this seems like it's getting a bit cheaty to be honest, but I have other ideas for this kind of data for the future, this just seemed like an easier, quicker application of this data. The other idea is not cheaty and if you'd rather not have these kinds of cheats on KC3 then lemme know and I'll open an issue for the other idea

**Comment by dragonjet** [comment]
saw this on ElectronicObserver, will add this, probably after the Quest flowcharts
