### ISSUE TITLE
New Developed Item not registered

### ISSUE THREAD

**Issue by ReiFan49** [dragonjet/KC3Kai#89]
i just equipped Type 3 Shell (and it JUST developed) and this happens ?
i wonder why... (i hope you could update the item list after successful scrap/development)
![image](https://cloud.githubusercontent.com/assets/9847780/7669548/314ce346-fca2-11e4-9b5e-4b1ed62e429c.png)

**Comment by dragonjet** [comment]
thanks for noticing this

**Comment by dragonjet** [comment]
tested this myself and can't reproduce, made a tenzan and equipped it immediately and it shows on both the panel and fleets tab on strategy room.

is it possible you have the panel closed when you crafted?

**Comment by ReiFan49** [comment]
no, i'm always watching it,
i only turned "show craft box" off though, ~~(and after digs out your code, the show craft box is required to log these newly developed item though lol)~~

**Comment by dragonjet** [comment]
wow thanks for pointing this out! very good find~ would've taken me longer to look for it myself XD will fix for next version, thanks~
